"""
exporters/mef_igi2/export_gltf.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math



# ========== Functions ==========
def export_to_gltf(model, output_path, base_name, vertices, faces, has_normals=True, has_uv=True):
    """تصدير glTF مع دعم معاملات التصحيح العامة"""
    if not GLTF_AVAILABLE:
        return False
    
    # استخدام المعاملات العامة إذا كانت متوفرة
    debug_params = global_debug_params
    
    try:
        from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
        
        gltf = GLTF2()
        gltf.asset = Asset(generator="IGI1/IGI2 MEF Exporter", version="2.0")
        
        positions = []
        normals = []
        uvs = []
        for v in vertices:
            positions.extend([v['px'], v['py'], v['pz']])
            if has_normals:
                normals.extend([v['nx'], v['ny'], v['nz']])
            if has_uv:
                uvs.extend([v['u'], 1.0 - v['v']])
        
        # إذا كانت معاملات التصحيح متوفرة، يمكن تطبيق تحويل إضافي
        if debug_params:
            # يمكن إضافة معالجة إضافية حسب الحاجة
            pass
        
        binary_data = bytearray()
        
        positions_bytes = np.array(positions, dtype=np.float32).tobytes()
        positions_buffer_view = BufferView(
            buffer=0,
            byteOffset=len(binary_data),
            byteLength=len(positions_bytes),
            target=34962
        )
        gltf.bufferViews.append(positions_buffer_view)
        binary_data.extend(positions_bytes)
        
        positions_accessor = Accessor(
            bufferView=len(gltf.bufferViews) - 1,
            componentType=5126,
            count=len(vertices),
            type="VEC3",
            min=[float(np.min(positions[0::3])), float(np.min(positions[1::3])), float(np.min(positions[2::3]))],
            max=[float(np.max(positions[0::3])), float(np.max(positions[1::3])), float(np.max(positions[2::3]))]
        )
        gltf.accessors.append(positions_accessor)
        
        if has_normals:
            normals_bytes = np.array(normals, dtype=np.float32).tobytes()
            normals_buffer_view = BufferView(
                buffer=0,
                byteOffset=len(binary_data),
                byteLength=len(normals_bytes),
                target=34962
            )
            gltf.bufferViews.append(normals_buffer_view)
            binary_data.extend(normals_bytes)
            
            normals_accessor = Accessor(
                bufferView=len(gltf.bufferViews) - 1,
                componentType=5126,
                count=len(vertices),
                type="VEC3"
            )
            gltf.accessors.append(normals_accessor)
        
        if has_uv:
            uvs_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uvs_buffer_view = BufferView(
                buffer=0,
                byteOffset=len(binary_data),
                byteLength=len(uvs_bytes),
                target=34962
            )
            gltf.bufferViews.append(uvs_buffer_view)
            binary_data.extend(uvs_bytes)
            
            uvs_accessor = Accessor(
                bufferView=len(gltf.bufferViews) - 1,
                componentType=5126,
                count=len(vertices),
                type="VEC2"
            )
            gltf.accessors.append(uvs_accessor)
        
        indices = []
        for face in faces:
            indices.extend([face[0], face[1], face[2]])
        
        indices_bytes = np.array(indices, dtype=np.uint32).tobytes()
        indices_buffer_view = BufferView(
            buffer=0,
            byteOffset=len(binary_data),
            byteLength=len(indices_bytes),
            target=34963
        )
        gltf.bufferViews.append(indices_buffer_view)
        binary_data.extend(indices_bytes)
        
        indices_accessor = Accessor(
            bufferView=len(gltf.bufferViews) - 1,
            componentType=5125,
            count=len(indices),
            type="SCALAR"
        )
        gltf.accessors.append(indices_accessor)
        
        gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_name}.bin"))
        
        attributes = Attributes(POSITION=0)
        if has_normals:
            attributes.NORMAL = 1
        if has_uv:
            attributes.TEXCOORD_0 = 2
        
        primitive = Primitive(
            attributes=attributes,
            indices=len(gltf.accessors) - 1,
            material=0
        )
        
        mesh = Mesh(primitives=[primitive])
        gltf.meshes.append(mesh)
        
        node = Node(mesh=0)
        gltf.nodes.append(node)
        scene = Scene(nodes=[0])
        gltf.scenes.append(scene)
        gltf.scene = 0
        
        gltf.save(f"{output_path}.gltf")
        
        with open(f"{os.path.splitext(output_path)[0]}.bin", 'wb') as f:
            f.write(binary_data)
        
        print(f"   Exported glTF with debug_params={debug_params is not None}")
        return True
    except Exception as e:
        print(f"      Error exporting to glTF: {e}")
        return False

def export_to_gltf_full(model, output_path, base_name, vertices, faces, has_normals=True, has_uv=True, has_skinning=False, bones=None):                     
    debug_params = get_global_debug_params()
    
    # استخدام debug_params إذا كانت متوفرة
    if debug_params:
        print(f"   Exporting glTF with debug scale: {debug_params.v_scale}")
        # يمكن تطبيق تحويل إضافي على الرؤوس إذا لزم الأمر
        # مثلاً: إذا أردت تطبيق swizzle إضافي على البيانات قبل التصدير
        # vertices = apply_additional_transform(vertices, debug_params)
        
    if not GLTF_AVAILABLE:
        return False
    
    try:
        from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
        
        gltf = GLTF2()
        gltf.asset = Asset(generator="IGI1/IGI2 MEF Exporter", version="2.0")
        
        # تجميع البيانات
        positions = []
        normals = []
        uvs = []
        weights = []
        joints = []
        
        for i, v in enumerate(vertices):
            positions.extend([v['px'], v['py'], v['pz']])
            if has_normals:
                normals.extend([v['nx'], v['ny'], v['nz']])
            if has_uv:
                uvs.extend([v['u'], 1.0 - v['v']])
            
            # جمع بيانات التزين (إذا وجدت)
            if has_skinning:
                # padding إلى 4 قيم (أقصى 4 عظام لكل رأس)
                w = [0.0, 0.0, 0.0, 0.0]
                j = [0, 0, 0, 0]
                
                if 'weight' in v.dtype.names:
                    w_val = v['weight']
                    if isinstance(w_val, np.ndarray):
                        w[0] = float(w_val[0]) if len(w_val) > 0 else 0.0
                    else:
                        w[0] = float(w_val)
                
                if 'bone_id' in v.dtype.names:
                    j_val = v['bone_id']
                    if isinstance(j_val, np.ndarray):
                        j[0] = int(j_val[0]) if len(j_val) > 0 else 0
                    else:
                        j[0] = int(j_val)
                
                weights.extend(w)
                joints.extend(j)
        
        binary_data = bytearray()
        
        # Positions
        pos_bytes = np.array(positions, dtype=np.float32).tobytes()
        pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
        gltf.bufferViews.append(pos_bv)
        binary_data.extend(pos_bytes)
        
        pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126, 
                           count=len(vertices), type="VEC3",
                           min=[float(np.min(positions[0::3])), float(np.min(positions[1::3])), float(np.min(positions[2::3]))],
                           max=[float(np.max(positions[0::3])), float(np.max(positions[1::3])), float(np.max(positions[2::3]))])
        gltf.accessors.append(pos_acc)
        
        # Normals
        if has_normals and normals:
            norm_bytes = np.array(normals, dtype=np.float32).tobytes()
            norm_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(norm_bytes), target=34962)
            gltf.bufferViews.append(norm_bv)
            binary_data.extend(norm_bytes)
            
            norm_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126, 
                                count=len(vertices), type="VEC3")
            gltf.accessors.append(norm_acc)
        
        # UVs
        if has_uv and uvs:
            uv_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126, 
                              count=len(vertices), type="VEC2")
            gltf.accessors.append(uv_acc)
        
        # Weights & Joints (للعظام)
        if has_skinning and weights and joints:
            weights_bytes = np.array(weights, dtype=np.float32).tobytes()
            weights_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(weights_bytes), target=34962)
            gltf.bufferViews.append(weights_bv)
            binary_data.extend(weights_bytes)
            
            weights_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126, 
                                   count=len(vertices), type="VEC4")
            gltf.accessors.append(weights_acc)
            
            joints_bytes = np.array(joints, dtype=np.uint16).tobytes()
            joints_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(joints_bytes), target=34962)
            gltf.bufferViews.append(joints_bv)
            binary_data.extend(joints_bytes)
            
            joints_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5123, 
                                  count=len(vertices), type="VEC4")
            gltf.accessors.append(joints_acc)
        
        # Indices
        indices_list = []
        for face in faces:
            indices_list.extend([face[0], face[1], face[2]])
        
        indices_bytes = np.array(indices_list, dtype=np.uint32).tobytes()
        indices_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(indices_bytes), target=34963)
        gltf.bufferViews.append(indices_bv)
        binary_data.extend(indices_bytes)
        
        indices_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125, 
                               count=len(indices_list), type="SCALAR")
        gltf.accessors.append(indices_acc)
        
        # Buffer
        gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_name}.bin"))
        
        # Primitive - بناء السمات حسب المتوفرة
        attribute_offset = 0
        attributes = Attributes(POSITION=attribute_offset)
        attribute_offset += 1
        
        if has_normals and normals:
            attributes.NORMAL = attribute_offset
            attribute_offset += 1
        if has_uv and uvs:
            attributes.TEXCOORD_0 = attribute_offset
            attribute_offset += 1
        if has_skinning and weights and joints:
            attributes.WEIGHTS_0 = attribute_offset
            attribute_offset += 1
            attributes.JOINTS_0 = attribute_offset
            attribute_offset += 1
        
        primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
        mesh = Mesh(primitives=[primitive])
        gltf.meshes.append(mesh)
        
        # عظام
        if has_skinning and bones:
            # إضافة العظام كـ nodes
            bone_nodes = []
            for bone in bones:
                node = Node(name=bone.name if hasattr(bone, 'name') else f'bone_{len(bone_nodes)}')
                gltf.nodes.append(node)
                bone_nodes.append(len(gltf.nodes)-1)
            
            # إنشاء الهيكل الهرمي
            for i, bone in enumerate(bones):
                parent_id = bone.parent_id if hasattr(bone, 'parent_id') else -1
                if parent_id >= 0 and parent_id < len(bone_nodes):
                    if gltf.nodes[bone_nodes[i]].children is None:
                        gltf.nodes[bone_nodes[i]].children = []
                    gltf.nodes[bone_nodes[i]].children.append(bone_nodes[parent_id])
            
            # Skin
            skin = Skin(joints=bone_nodes)
            gltf.skins.append(skin)
            
            # ربط الـ skin بالـ mesh
            node = Node(mesh=0, skin=len(gltf.skins)-1)
            gltf.nodes.append(node)
            scene = Scene(nodes=[len(gltf.nodes)-1])
        else:
            node = Node(mesh=0)
            gltf.nodes.append(node)
            scene = Scene(nodes=[0])
        
        gltf.scenes.append(scene)
        gltf.scene = 0
        
        # حفظ
        gltf.save(f"{output_path}.gltf")
        with open(f"{os.path.splitext(output_path)[0]}.bin", 'wb') as f:
            f.write(binary_data)
        
        print(f"   Exported glTF with full data (skinning: {has_skinning}, vertices: {len(vertices)}, weights: {len(weights) > 0})")
        return True
        
    except Exception as e:
        print(f"      Error exporting to glTF: {e}")
        import traceback
        traceback.print_exc()
        return False
