"""
exporters/mef_igi2/export_extra.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math



# ========== Functions ==========
def bake_skinning_improved(vertices, bone_global, inverse_bind, root_inv=None, 
                           debug_params: Optional['MefDebugParams'] = None,
                           extra_weights: Optional[List['XTRWEntry']] = None):
    """
    تحسين التزين مع دعم XTRW و bone_id_bias و bone_mode
    """
    if root_inv is None and len(bone_global) > 0:
        root_inv = np.linalg.inv(bone_global[0])
    
    if debug_params is None:
        debug_params = MefDebugParams()
    
    has_weight = "weight" in vertices.dtype.names
    has_bone_id = "bone_id" in vertices.dtype.names
    
    # بناء قاموس للأوزان الإضافية من XTRW
    xtrw_weights = {}
    if extra_weights:
        for ew in extra_weights:
            xtrw_weights[ew.vertex_id] = (ew.bone_id, ew.weight)
    
    vertex_count = len(vertices)
    result = np.zeros(vertex_count, dtype=[
        ("px", np.float32), ("py", np.float32), ("pz", np.float32),
        ("nx", np.float32), ("ny", np.float32), ("nz", np.float32),
        ("u", np.float32), ("v", np.float32),
        ("weight", np.float32), ("bone_id", np.uint16)
    ])
    
    for i in range(vertex_count):
        v = vertices[i]
        
        # استخراج الموقع
        if "pos" in v.dtype.names:
            pos = v["pos"]
            px, py, pz = float(pos[0]), float(pos[1]), float(pos[2])
        else:
            px = float(v["px"]) if "px" in v.dtype.names else 0.0
            py = float(v["py"]) if "py" in v.dtype.names else 0.0
            pz = float(v["pz"]) if "pz" in v.dtype.names else 0.0
        
        # استخراج الطبيعية
        if "normal" in v.dtype.names:
            normal = v["normal"]
            nx, ny, nz = float(normal[0]), float(normal[1]), float(normal[2])
        else:
            nx = float(v["nx"]) if "nx" in v.dtype.names else 0.0
            ny = float(v["ny"]) if "ny" in v.dtype.names else 0.0
            nz = float(v["nz"]) if "nz" in v.dtype.names else 0.0
        
        # استخراج UV
        if "uv0" in v.dtype.names:
            uv = v["uv0"]
            u, vt = float(uv[0]), float(uv[1])
        else:
            u = float(v["u"]) if "u" in v.dtype.names else 0.0
            vt = float(v["v"]) if "v" in v.dtype.names else 0.0
        
        # استخراج بيانات التزين (مع دعم XTRW و bone_id_bias)
        weight_val = 1.0
        bone_id_val = 0
        
        # أولاً: استخدام أوزان XTRW إذا كانت متوفرة
        if i in xtrw_weights:
            bone_id_val, weight_val = xtrw_weights[i]
        # ثانياً: استخدام الأوزان المضمنة في الرأس
        elif has_weight and has_bone_id:
            w = v["weight"]
            if isinstance(w, np.ndarray):
                weight_val = float(w[0]) if len(w) > 0 else 1.0
            else:
                weight_val = float(w)
            
            b = v["bone_id"]
            if isinstance(b, np.ndarray):
                bone_id_val = int(b[0]) if len(b) > 0 else 0
            else:
                bone_id_val = int(b)
        elif has_bone_id:
            b = v["bone_id"]
            if isinstance(b, np.ndarray):
                bone_id_val = int(b[0]) if len(b) > 0 else 0
            else:
                bone_id_val = int(b)
        
        # تطبيق bone_id_bias
        bone_id_val += debug_params.bone_id_bias
        
        # تطبيق التحويل حسب bone_mode
        pos_vec = np.array([px, py, pz, 1.0])
        
        if bone_id_val >= 0 and bone_id_val < len(bone_global) and weight_val > 0:
            G = bone_global[bone_id_val]
            pos_world = G @ pos_vec
            
            if debug_params.bone_mode == "ROOT" and len(bone_global) > 0:
                # تطبيق تحويل العظمة الجذرية
                root_matrix = bone_global[0]
                pos_model = np.linalg.inv(root_matrix) @ pos_world
            elif debug_params.bone_mode == "ABS":
                # تجاهل التسلسل الهرمي
                pos_model = pos_world
            else:  # "REL" أو الوضع الافتراضي
                pos_model = root_inv @ pos_world if root_inv is not None else pos_world
        else:
            pos_model = pos_vec[:3]
        
        # تطبيق swizzle على الإحداثيات
        px_out, py_out, pz_out = debug_params.swizzle(pos_model[0], pos_model[1], pos_model[2], debug_params.v_scale)
        nx_out, ny_out, nz_out = debug_params.swizzle(nx, ny, nz, 1.0)
        
        result[i]["px"] = px_out
        result[i]["py"] = py_out
        result[i]["pz"] = pz_out
        result[i]["nx"] = nx_out
        result[i]["ny"] = ny_out
        result[i]["nz"] = nz_out
        result[i]["u"] = u
        result[i]["v"] = vt
        result[i]["weight"] = weight_val
        result[i]["bone_id"] = bone_id_val if bone_id_val >= 0 else 0
    
    return result

def build_bone_matrices(bone_positions, child_counts):
    bone_count = len(bone_positions)
    if bone_count == 0:
        return [], [], []
    
    parents = build_parent_indices(child_counts)
    bind_local = np.array([make_translation_matrix(p.x, p.y, p.z) for p in bone_positions])
    bind_global = np.zeros((bone_count, 4, 4), dtype=np.float32)
    
    for i in range(bone_count):
        parent = parents[i] if i < len(parents) else -1
        if parent == -1:
            bind_global[i] = bind_local[i]
        else:
            bind_global[i] = bind_global[parent] @ bind_local[i]
    
    inverse_bind = np.array([np.linalg.inv(m) for m in bind_global])
    return bind_global, inverse_bind, parents

def build_parent_indices(child_counts):
    bone_count = len(child_counts)
    parents = [-1] * bone_count
    if bone_count == 0:
        return parents
    
    stack = [(0, int(child_counts[0]))]
    for i in range(1, bone_count):
        while stack and stack[-1][1] == 0:
            stack.pop()
        if not stack:
            break
        parent = stack[-1][0]
        parents[i] = parent
        stack[-1] = (stack[-1][0], stack[-1][1] - 1)
        stack.append((i, int(child_counts[i])))
    return parents

        def create_bone(parent_id: int, name: str, position: Vector3, child_count: int):
            # ✅ تم إزالة swizzle من العظام - سيتم تطبيقه عند التزين فقط
            bone = Bone(name, position, parent_id)
            next_parent_id = len(self.bones)
            self.bones.append(bone)
            for _ in range(child_count):
                if not bone_queue and not (child_counts and bone_names and bone_positions):
                    break
                cnt = child_counts.pop(0) if child_counts else 0
                nm = bone_names.pop(0) if bone_names else ""
                pos_raw = bone_positions.pop(0) if bone_positions else Vector3(0, 0, 0)
                bone_queue.append((next_parent_id, nm, pos_raw, cnt))

    def debug_uv_transform(self, atlas: TextureAtlas, material_name: str, vt_indices: List[int], orig_texture: str):
        """دالة تشخيصية لطباعة UVs قبل وبعد التحويل"""
        print(f"\n   🔍 DEBUG: Material '{material_name}' (texture: {orig_texture})")
        for vt_idx in vt_indices[:5]:
            if 0 <= vt_idx < len(self._all_texture_vertices):
                vt = self._all_texture_vertices[vt_idx]
                print(f"     VT {vt_idx}: original=({vt.u:.4f}, {vt.v:.4f})")
                
                # تطبيق التحويل
                uvs_array = np.array([[vt.u, vt.v]])
                new_uvs = atlas.get_uv_transform(orig_texture, uvs_array)
                print(f"       after atlas=({new_uvs[0,0]:.4f}, {new_uvs[0,1]:.4f})")
