"""
exporters/mef_igi2/export_directx.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class DXFrame:
    """هيكل الإطار (Frame) في DirectX - يمثل عظمة"""
    name: str
    parent_name: str = ""
    parent_id: int = -1
    matrix: List[List[float]] = field(default_factory=lambda: [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
    position: Tuple[float, float, float] = (0, 0, 0)
    rotation: Tuple[float, float, float, float] = (0, 0, 0, 1)  # Quaternion
    scale: Tuple[float, float, float] = (1, 1, 1)
    mesh_name: str = ""
    vertices: List[Tuple[float, float, float]] = field(default_factory=list)
    normals: List[Tuple[float, float, float]] = field(default_factory=list)
    uvs: List[Tuple[float, float]] = field(default_factory=list)
    faces: List[Tuple[int, int, int]] = field(default_factory=list)
    materials: List[Dict] = field(default_factory=list)

class DXSkinWeight:
    """وزن عظمة (Skin Weight) في DirectX"""
    bone_name: str
    vertex_index: int
    weight: float

class DXAnimationKey:
    """إطار مفتاحي للحركة"""
    time: float
    matrix: List[List[float]]

class DXAnimation:
    """حركة كاملة في DirectX"""
    name: str
    frame_name: str
    keys: List[DXAnimationKey]

class DirectXExporter:
    """
    مصدر نماذج DirectX (.X) مع دعم كامل لـ:
    - العظام (Frame Hierarchy)
    - التزين (Skin Weights)
    - الرسوم المتحركة (Animations)
    - المواد والقوام (Materials & Textures)
    """
    
    def __init__(self):
        self.frames: List[DXFrame] = []
        self.skin_weights: List[DXSkinWeight] = []
        self.animations: List[DXAnimation] = []
        self.materials: List[Dict] = []
        self.textures: List[str] = []
        
    def fix_directx_bone_extraction():
        """تصحيح استخراج العظام من MEF لـ DirectXExporter"""
    
    def from_mef_model(self, model, debug_params: 'MefDebugParams' = None):
        """
        استخراج البيانات من نموذج MEF (IGI1/IGI2) - نسخة مصلحة
        """
        if debug_params is None:
            debug_params = MefDebugParams()
        
        # ========== 1. استخراج العظام ==========
        if hasattr(model, 'bones') and model.bones:
            for i, bone in enumerate(model.bones):
                # الحصول على اسم الأب
                parent_name = ""
                if hasattr(bone, 'parent_id') and bone.parent_id >= 0:
                    parent_name = model.bones[bone.parent_id].name if bone.parent_id < len(model.bones) else ""
                
                frame = DXFrame(
                    name=bone.name,
                    parent_id=bone.parent_id if hasattr(bone, 'parent_id') else -1,
                    parent_name=parent_name,
                    position=(bone.pos.x, bone.pos.y, bone.pos.z)
                )
                self.frames.append(frame)
            
            print(f"   🦴 Extracted {len(self.frames)} bones/frames")
        
        # ========== 2. استخراج بيانات التزين (Skin Weights) ==========
        if hasattr(model, 'render_mesh_data') and model.render_mesh_data:
            mesh_data = model.render_mesh_data
            
            if hasattr(mesh_data, 'vertices'):
                vertices = mesh_data.vertices
                
                # البحث عن الأوزان
                for i, v in enumerate(vertices):
                    bone_id = None
                    weight = None
                    
                    # محاولة استخراج bone_id بعدة طرق
                    if "bone_id" in v.dtype.names:
                        bid = v["bone_id"]
                        if isinstance(bid, np.ndarray):
                            bone_id = int(bid[0]) if len(bid) > 0 else None
                        else:
                            bone_id = int(bid) if bid is not None else None
                    
                    # محاولة استخراج weight
                    if "weight" in v.dtype.names:
                        w = v["weight"]
                        if isinstance(w, np.ndarray):
                            weight = float(w[0]) if len(w) > 0 else None
                        else:
                            weight = float(w) if w is not None else None
                    
                    if bone_id is not None and weight is not None and weight > 0:
                        if bone_id < len(model.bones):
                            self.skin_weights.append(DXSkinWeight(
                                bone_name=model.bones[bone_id].name,
                                vertex_index=i,
                                weight=weight
                            ))
                
                print(f"   🎨 Extracted {len(self.skin_weights)} skin weights")
        
        # ========== 3. استخراج الشبكة (Mesh) ==========
        self._extract_mesh_from_mef(model, debug_params)
        
        # ========== 4. استخراج المواد ==========
        self._extract_materials_from_mef(model)
        
        # ========== 5. استخراج الرسوم المتحركة ==========
        self._extract_animations_from_mef(model)
        
        return self
    
    def fix_directx_mdl_extraction():
        """تصحيح استخراج العظام من MDL لـ DirectXExporter"""
    
    def from_mdl_model(self, model):
        """
        استخراج البيانات من نموذج MDL (StudioHeader)
        """
        # ========== 1. استخراج العظام ==========
        if hasattr(model, 'bones') and model.bones:
            for i, bone in enumerate(model.bones):
                # استخدام parent وليس parent_id (التصحيح)
                parent_id = bone.parent if hasattr(bone, 'parent') else -1
                
                frame = DXFrame(
                    name=bone.name,
                    parent_id=parent_id,
                    parent_name=model.bones[parent_id].name if parent_id >= 0 and parent_id < len(model.bones) else "",
                    position=(bone.value[0] if len(bone.value) > 0 else 0,
                             bone.value[1] if len(bone.value) > 1 else 0,
                             bone.value[2] if len(bone.value) > 2 else 0)
                )
                self.frames.append(frame)
            
            # بناء التسلسل الهرمي
            for i, bone in enumerate(model.bones):
                parent_id = bone.parent if hasattr(bone, 'parent') else -1
                if parent_id >= 0 and parent_id < len(self.frames):
                    self.frames[i].parent_id = parent_id
            
            print(f"   🦴 Extracted {len(self.frames)} bones/frames from MDL")
        
        # ========== 2. استخراج الشبكة ==========
        self._extract_mesh_from_mdl(model)
        
        # ========== 3. استخراج المواد ==========
        if hasattr(model, 'header') and hasattr(model.header, 'numtextures') and model.header.numtextures > 0:
            for i in range(min(model.header.numtextures, 10)):
                self.materials.append({
                    "name": f"material_{i}",
                    "texture": f"texture_{i}.bmp"
                })
            print(f"   🎨 Extracted {len(self.materials)} materials from MDL")
        
        return self
    
    def _extract_mesh_from_mdl(self, model):
        """استخراج الشبكة من نموذج MDL"""
        if not hasattr(model, 'vertices') or not model.vertices:
            return
        
        # تحويل الرؤوس
        for i, v in enumerate(model.vertices):
            px, py, pz = v.x, v.z, v.y  # تحويل Y-up إلى Z-up
            self.frames[0].vertices.append((px, py, pz))
            self.frames[0].normals.append((0, 0, 0))
            self.frames[0].uvs.append((0, 0))
        
        # استخراج الوجوه
        for tri in model.triangles:
            if len(tri.vertindex) >= 3:
                self.frames[0].faces.append((tri.vertindex[0], tri.vertindex[1], tri.vertindex[2]))
        
        print(f"   📦 Extracted mesh from MDL: {len(self.frames[0].vertices)} vertices, {len(self.frames[0].faces)} faces")
    
    def from_smd_model(self, smd: SMDExporter):
        """
        استخراج البيانات من نموذج SMD
        """
        # ========== 1. استخراج العظام ==========
        for node in smd.nodes:
            frame = DXFrame(
                name=node.name,
                parent_id=node.parent_id,
                parent_name=self._find_parent_name(smd.nodes, node.parent_id),
                position=(0, 0, 0)
            )
            self.frames.append(frame)
        
        print(f"   🦴 Extracted {len(self.frames)} bones/frames from SMD")
        
        # ========== 2. استخراج الشبكة ==========
        self._extract_mesh_from_smd(smd)
        
        # ========== 3. استخراج المواد ==========
        if hasattr(smd, 'materials') and smd.materials:
            for mat_name in smd.materials:
                self.materials.append({
                    "name": mat_name,
                    "texture": mat_name
                })
            print(f"   🎨 Extracted {len(self.materials)} materials from SMD")
        
        return self
    
    def from_obj_model(self, obj: OBJExporter, base_name: str = "model"):
        """
        استخراج البيانات من نموذج OBJ
        """
        # ========== 1. إنشاء عظمة افتراضية ==========
        self.frames.append(DXFrame(name="root", parent_id=-1))
        
        # ========== 2. استخراج الشبكة ==========
        vertices, faces = obj.to_unified_vertices(apply_swizzle=True)
        
        for v in vertices:
            self.frames[0].vertices.append((v['px'], v['py'], v['pz']))
            self.frames[0].normals.append((v['nx'], v['ny'], v['nz']))
            self.frames[0].uvs.append((v['u'], v['v']))
        
        for face in faces:
            if len(face) == 3:
                self.frames[0].faces.append((face[0], face[1], face[2]))
        
        # ========== 3. استخراج المواد ==========
        for name, mat in obj.materials.items():
            self.materials.append({
                "name": name,
                "texture": mat.diffuse_texture,
                "ambient": mat.ambient,
                "diffuse": mat.diffuse,
                "specular": mat.specular
            })
        
        print(f"   📦 Extracted mesh: {len(self.frames[0].vertices)} vertices, {len(self.frames[0].faces)} faces")
        print(f"   🎨 Extracted {len(self.materials)} materials from OBJ")
        
        return self
    
    def fix_directx_mesh_extraction():
        """تصحيح استخراج الشبكة من MEF لـ DirectXExporter"""
    
    def _extract_mesh_from_mef(self, model, debug_params):
        """استخراج الشبكة من نموذج MEF - نسخة مصلحة"""
        if not hasattr(model, 'render_mesh_data') or not model.render_mesh_data:
            return
        
        mesh_data = model.render_mesh_data
        
        # تحويل الرؤوس
        if hasattr(mesh_data, 'vertices'):
            vertices = mesh_data.vertices
            
            for i, v in enumerate(vertices):
                # استخراج الموقع - التصحيح هنا
                if "pos" in v.dtype.names:
                    px, py, pz = float(v["pos"][0]), float(v["pos"][1]), float(v["pos"][2])
                elif "px" in v.dtype.names:
                    px, py, pz = float(v["px"]), float(v["py"]), float(v["pz"])
                else:
                    px, py, pz = 0.0, 0.0, 0.0
                
                # تطبيق swizzle
                px, py, pz = debug_params.swizzle(px, py, pz, debug_params.v_scale)
                
                # استخراج الطبيعية
                if "normal" in v.dtype.names:
                    normal = v["normal"]
                    nx, ny, nz = float(normal[0]), float(normal[1]), float(normal[2])
                elif "nx" in v.dtype.names:
                    nx, ny, nz = float(v["nx"]), float(v["ny"]), float(v["nz"])
                else:
                    nx, ny, nz = 0.0, 0.0, 0.0
                
                nx, ny, nz = debug_params.swizzle(nx, ny, nz, 1.0)
                
                # استخراج UV
                if "uv0" in v.dtype.names:
                    uv = v["uv0"]
                    u, vt = float(uv[0]), float(uv[1])
                elif "u" in v.dtype.names and "v" in v.dtype.names:
                    u, vt = float(v["u"]), float(v["v"])
                else:
                    u, vt = 0.0, 0.0
                
                # إضافة الرأس إلى الإطار المناسب
                frame_idx = 0
                if hasattr(v, 'bone_id') and self.frames:
                    bone_id_val = v["bone_id"]
                    if isinstance(bone_id_val, np.ndarray):
                        bone_id = int(bone_id_val[0]) if len(bone_id_val) > 0 else 0
                    else:
                        bone_id = int(bone_id_val)
                    if 0 <= bone_id < len(self.frames):
                        frame_idx = bone_id
                
                # التأكد من وجود الإطار
                while frame_idx >= len(self.frames):
                    self.frames.append(DXFrame(name=f"bone_{len(self.frames)}"))
                
                self.frames[frame_idx].vertices.append((px, py, pz))
                self.frames[frame_idx].normals.append((nx, ny, nz))
                self.frames[frame_idx].uvs.append((u, vt))
            
            # استخراج الوجوه
            if hasattr(mesh_data, 'faces'):
                for face in mesh_data.faces:
                    if len(face) >= 3:
                        self.frames[0].faces.append((int(face[0]), int(face[1]), int(face[2])))
            
            print(f"   📦 Extracted mesh: {len(self.frames[0].vertices)} vertices, {len(self.frames[0].faces)} faces")

    def _extract_mesh_from_smd(self, smd: SMDExporter):
        """استخراج الشبكة من نموذج SMD"""
        vertices, faces = smd.to_vertices_array()
        
        for i, v in enumerate(vertices):
            frame_idx = 0
            if hasattr(smd, 'nodes') and smd.nodes:
                bone_id = v['bone_id']
                if 0 <= bone_id < len(smd.nodes):
                    frame_idx = bone_id
            
            while frame_idx >= len(self.frames):
                self.frames.append(DXFrame(name=f"bone_{len(self.frames)}"))
            
            self.frames[frame_idx].vertices.append((v['px'], v['py'], v['pz']))
            self.frames[frame_idx].normals.append((v['nx'], v['ny'], v['nz']))
            self.frames[frame_idx].uvs.append((v['u'], v['v']))
        
        for face in faces:
            if len(face) == 3:
                self.frames[0].faces.append((face[0], face[1], face[2]))
        
        print(f"   📦 Extracted mesh from SMD: {len(self.frames[0].vertices)} vertices, {len(self.frames[0].faces)} faces")
    
    def _extract_materials_from_mef(self, model):
        """استخراج المواد من نموذج MEF"""
        if not hasattr(model, 'render_mesh_data') or not model.render_mesh_data:
            return
        
        if hasattr(model.render_mesh_data, 'primitives') and model.render_mesh_data.primitives:
            for i, prim in enumerate(model.render_mesh_data.primitives):
                texture_index = prim.diffuse_texture if hasattr(prim, 'diffuse_texture') else 0
                texture_name = get_texture_name(texture_index, "model", i, 
                                                getattr(model, 'texture_references', None))
                
                self.materials.append({
                    "name": f"material_{i}",
                    "texture": texture_name,
                    "transparency": prim.transparency if hasattr(prim, 'transparency') else 1.0,
                    "shininess": prim.shininess if hasattr(prim, 'shininess') else 10
                })
        
        print(f"   🎨 Extracted {len(self.materials)} materials from MEF")
    
    def _extract_animations_from_mef(self, model):
        """استخراج الرسوم المتحركة من نموذج MEF"""
        if not hasattr(model, 'txan_data') or not model.txan_data:
            return
        
        bone_count = len(self.frames) if self.frames else 0
        
        for txan_idx, txan in enumerate(model.txan_data):
            fields = txan.unknown_fields
            
            if len(fields) >= 28:
                frame_count = fields[1] if fields[1] < 1000 else 0
                duration_ms = fields[2] if fields[2] > 0 else 1000
                duration = duration_ms / 1000.0
                
                for frame in range(min(frame_count, 100)):
                    frame_time = frame / max(frame_count, 1) * duration
                    
                    for bone in range(min(bone_count, 10)):
                        idx = 4 + (frame * bone_count + bone) * 6
                        
                        if idx + 5 < len(fields):
                            # بناء مصفوفة التحويل من البيانات
                            matrix = [
                                [1, 0, 0, fields[idx] / 100.0],
                                [0, 1, 0, fields[idx+1] / 100.0],
                                [0, 0, 1, fields[idx+2] / 100.0],
                                [0, 0, 0, 1]
                            ]
                            
                            animation = DXAnimation(
                                name=f"anim_{txan_idx}",
                                frame_name=self.frames[bone].name if bone < len(self.frames) else f"bone_{bone}",
                                keys=[DXAnimationKey(time=frame_time, matrix=matrix)]
                            )
                            self.animations.append(animation)
        
        print(f"   🎬 Extracted {len(self.animations)} animations from TXAN")
    
    def _find_parent_name(self, nodes: List, parent_id: int) -> str:
        """العثور على اسم العظمة الأب"""
        for node in nodes:
            if node.id == parent_id:
                return node.name
        return ""
    
    def export_to_file(self, output_path: str):
        """تصدير كل البيانات إلى ملف DirectX (.X) - نسخة مصلحة"""
        with open(output_path, 'w', encoding='utf-8') as f:
            # رأس الملف
            f.write("xof 0303txt 0032\n")
            f.write("\n")
            
            # الرأس
            f.write("Header {\n")
            f.write("    1;\n")
            f.write("    0;\n")
            f.write("    1;\n")
            f.write("}\n")
            f.write("\n")
            
            # المواد
            self._write_materials(f)
            
            # الإطارات (العظام) - العقد الجذرية فقط
            root_frames = [f for f in self.frames if f.parent_id == -1]
            for frame in root_frames:
                self._write_frame_hierarchy(f, frame, 0)
            
            # أوزان التزين
            if self.skin_weights:
                self._write_skin_weights(f)
            
            # الرسوم المتحركة
            if self.animations:
                self._write_animations(f)

    def _write_frame_hierarchy(self, f, frame: DXFrame, level: int):
        """كتابة إطار وأبنائه بشكل هرمي"""
        indent = "    " * level
        
        f.write(f"{indent}Frame {frame.name} {{\n")
        
        # مصفوفة التحويل
        mat = frame.matrix
        f.write(f"{indent}    FrameTransformMatrix {{\n")
        f.write(f"{indent}        {mat[0][0]:.6f}, {mat[0][1]:.6f}, {mat[0][2]:.6f}, {mat[0][3]:.6f},\n")
        f.write(f"{indent}        {mat[1][0]:.6f}, {mat[1][1]:.6f}, {mat[1][2]:.6f}, {mat[1][3]:.6f},\n")
        f.write(f"{indent}        {mat[2][0]:.6f}, {mat[2][1]:.6f}, {mat[2][2]:.6f}, {mat[2][3]:.6f},\n")
        f.write(f"{indent}        {mat[3][0]:.6f}, {mat[3][1]:.6f}, {mat[3][2]:.6f}, {mat[3][3]:.6f};;\n")
        f.write(f"{indent}    }}\n")
        
        # الشبكة
        if frame.vertices and frame.faces:
            self._write_mesh(f, frame, id(frame), indent + "    ")
        
        # إطارات الأبناء
        children = [f for f in self.frames if f.parent_id == id(frame)]
        for child in children:
            self._write_frame_hierarchy(f, child, level + 1)
        
        f.write(f"{indent}}}\n")
        
    def _write_materials(self, f):
        """كتابة المواد إلى ملف DirectX"""
        if not self.materials:
            # مادة افتراضية
            f.write("Material default_material {\n")
            f.write("    0.8; 0.8; 0.8; 1.0;;\n")
            f.write("    10.0;\n")
            f.write("    0.0; 0.0; 0.0;;\n")
            f.write("    0.0; 0.0; 0.0;;\n")
            f.write("}\n")
            f.write("\n")
            return
        
        for i, mat in enumerate(self.materials):
            color = mat.get("diffuse", (1.0, 1.0, 1.0))
            shininess = mat.get("shininess", 10)
            texture = mat.get("texture", "")
            
            f.write(f"Material {mat['name']} {{\n")
            f.write(f"    {color[0]:.3f}; {color[1]:.3f}; {color[2]:.3f}; 1.0;;\n")
            f.write(f"    {shininess:.1f};\n")
            f.write(f"    0.0; 0.0; 0.0;;\n")
            f.write(f"    0.0; 0.0; 0.0;;\n")
            
            if texture:
                f.write(f"    TextureFilename {{\n")
                f.write(f"        \"{texture}\";\n")
                f.write(f"    }}\n")
            
            f.write("}\n")
            f.write("\n")
    
    def _write_frames(self, f):
        """كتابة الإطارات (العظام) إلى ملف DirectX"""
        for i, frame in enumerate(self.frames):
            f.write(f"Frame {frame.name} {{\n")
            
            # مصفوفة التحويل
            mat = frame.matrix
            f.write(f"    FrameTransformMatrix {{\n")
            f.write(f"        {mat[0][0]:.6f}, {mat[0][1]:.6f}, {mat[0][2]:.6f}, {mat[0][3]:.6f}, \n")
            f.write(f"        {mat[1][0]:.6f}, {mat[1][1]:.6f}, {mat[1][2]:.6f}, {mat[1][3]:.6f}, \n")
            f.write(f"        {mat[2][0]:.6f}, {mat[2][1]:.6f}, {mat[2][2]:.6f}, {mat[2][3]:.6f}, \n")
            f.write(f"        {mat[3][0]:.6f}, {mat[3][1]:.6f}, {mat[3][2]:.6f}, {mat[3][3]:.6f};;\n")
            f.write(f"    }}\n")
            
            # الشبكة (Mesh) إن وجدت
            if frame.vertices and frame.faces:
                self._write_mesh(f, frame, i)
            
            f.write("}\n")
            f.write("\n")
            
            # إطارات الأبناء
            children = [f for f in self.frames if f.parent_id == i]
            for child in children:
                self._write_child_frame(f, child)
    
    def _write_child_frame(self, f, frame: DXFrame, level: int = 1):
        """كتابة إطار ابن"""
        indent = "    " * level
        
        f.write(f"{indent}Frame {frame.name} {{\n")
        
        # مصفوفة التحويل
        mat = frame.matrix
        f.write(f"{indent}    FrameTransformMatrix {{\n")
        f.write(f"{indent}        {mat[0][0]:.6f}, {mat[0][1]:.6f}, {mat[0][2]:.6f}, {mat[0][3]:.6f}, \n")
        f.write(f"{indent}        {mat[1][0]:.6f}, {mat[1][1]:.6f}, {mat[1][2]:.6f}, {mat[1][3]:.6f}, \n")
        f.write(f"{indent}        {mat[2][0]:.6f}, {mat[2][1]:.6f}, {mat[2][2]:.6f}, {mat[2][3]:.6f}, \n")
        f.write(f"{indent}        {mat[3][0]:.6f}, {mat[3][1]:.6f}, {mat[3][2]:.6f}, {mat[3][3]:.6f};;\n")
        f.write(f"{indent}    }}\n")
        
        # الشبكة إن وجدت
        if frame.vertices and frame.faces:
            self._write_mesh(f, frame, id(frame), indent + "    ")
        
        f.write(f"{indent}}}\n")
    
    def _write_mesh(self, f, frame: DXFrame, mesh_id: int, indent: str = "    "):
        """كتابة الشبكة (Mesh) إلى ملف DirectX - نسخة مصلحة"""
        if not frame.vertices:
            return
        
        f.write(f"{indent}Mesh {frame.name}_mesh {{\n")
        
        # ========== الرؤوس ==========
        f.write(f"{indent}    {len(frame.vertices)};\n")
        for v in frame.vertices:
            # الصيغة الصحيحة: x; y; z;,
            f.write(f"{indent}    {v[0]:.6f}; {v[1]:.6f}; {v[2]:.6f};,\n")
        
        # ========== الوجوه ==========
        f.write(f"{indent}    {len(frame.faces)};\n")
        for face in frame.faces:
            # الصيغة الصحيحة: 3; a, b, c;;
            f.write(f"{indent}    3; {face[0]}, {face[1]}, {face[2]};;\n")
        
        # ========== الطبيعيات (Normals) ==========
        if frame.normals:
            f.write(f"{indent}    MeshNormals {{\n")
            f.write(f"{indent}        {len(frame.normals)};\n")
            for n in frame.normals:
                f.write(f"{indent}        {n[0]:.6f}; {n[1]:.6f}; {n[2]:.6f};,\n")
            f.write(f"{indent}        {len(frame.faces)};\n")
            for i, face in enumerate(frame.faces):
                # كل وجه له 3 طبيعيات (عادة نفس الفهرس)
                f.write(f"{indent}        3; {i}, {i}, {i};;\n")
            f.write(f"{indent}    }}\n")
        
        # ========== إحداثيات النسيج (UVs) ==========
        if frame.uvs:
            f.write(f"{indent}    MeshTextureCoords {{\n")
            f.write(f"{indent}        {len(frame.uvs)};\n")
            for uv in frame.uvs:
                f.write(f"{indent}        {uv[0]:.6f}; {1.0 - uv[1]:.6f};;\n")
            f.write(f"{indent}    }}\n")
        
        # ========== قائمة المواد (MeshMaterialList) ==========
        if self.materials:
            # حساب عدد الوجوه لكل مادة
            face_count = len(frame.faces)
            
            f.write(f"{indent}    MeshMaterialList {{\n")
            f.write(f"{indent}        {len(self.materials)};\n")  # عدد المواد
            f.write(f"{indent}        {face_count};\n")  # عدد الوجوه
            
            # توزيع الوجوه على المواد (هنا كل الوجوه للمادة 0 كمثال)
            for i in range(face_count):
                f.write(f"{indent}        {i % len(self.materials)},\n")
            
            # أسماء المواد
            for mat in self.materials:
                f.write(f"{indent}        {mat['name']};\n")
            
            f.write(f"{indent}    }}\n")
        
        f.write(f"{indent}}}\n")
    
    def _write_skin_weights(self, f):
        """كتابة أوزان التزين (Skin Weights) إلى ملف DirectX"""
        f.write("SkinWeights {\n")
        
        # تجميع الأوزان حسب العظمة
        weights_by_bone = {}
        for w in self.skin_weights:
            if w.bone_name not in weights_by_bone:
                weights_by_bone[w.bone_name] = []
            weights_by_bone[w.bone_name].append(w)
        
        for bone_name, weights in weights_by_bone.items():
            f.write(f"    \"{bone_name}\",\n")
            f.write(f"    {len(weights)};\n")
            
            # مؤشرات الرؤوس
            f.write("    ")
            for w in weights:
                f.write(f"{w.vertex_index}, ")
            f.write(";\n")
            
            # الأوزان
            f.write("    ")
            for w in weights:
                f.write(f"{w.weight:.6f}, ")
            f.write(";\n")
            
            # مصفوفة الإزاحة
            f.write("    1.0, 0.0, 0.0, 0.0,\n")
            f.write("    0.0, 1.0, 0.0, 0.0,\n")
            f.write("    0.0, 0.0, 1.0, 0.0,\n")
            f.write("    0.0, 0.0, 0.0, 1.0;;\n")
        
        f.write("}\n")
        f.write("\n")
    
    def _write_animations(self, f):
        """كتابة الرسوم المتحركة إلى ملف DirectX"""
        # تجميع الحركات حسب الإطار
        anims_by_frame = {}
        for anim in self.animations:
            if anim.frame_name not in anims_by_frame:
                anims_by_frame[anim.frame_name] = []
            anims_by_frame[anim.frame_name].append(anim)
        
        for frame_name, anims in anims_by_frame.items():
            f.write(f"Animation {{\n")
            f.write(f"    {{ {frame_name} }}\n")
            
            for anim in anims:
                f.write(f"    AnimationKey {{\n")
                f.write(f"        0;\n")  # 0 = Matrix key
                f.write(f"        {len(anim.keys)};\n")
                
                for key in anim.keys:
                    mat = key.matrix
                    f.write(f"        {key.time:.6f};")
                    f.write(f" {mat[0][0]:.6f}, {mat[0][1]:.6f}, {mat[0][2]:.6f}, {mat[0][3]:.6f},")
                    f.write(f" {mat[1][0]:.6f}, {mat[1][1]:.6f}, {mat[1][2]:.6f}, {mat[1][3]:.6f},")
                    f.write(f" {mat[2][0]:.6f}, {mat[2][1]:.6f}, {mat[2][2]:.6f}, {mat[2][3]:.6f},")
                    f.write(f" {mat[3][0]:.6f}, {mat[3][1]:.6f}, {mat[3][2]:.6f}, {mat[3][3]:.6f};;\n")
                
                f.write(f"    }}\n")
            
            f.write(f"    AnimationOptions {{\n")
            f.write(f"        0;\n")  # openclosed
            f.write(f"        0;\n")  # positionquality
            f.write(f"    }}\n")
            f.write(f"}}\n")
            f.write(f"\n")


# ========== Functions ==========
    def export_to_directx(self, output_path: str):
        """تصدير النموذج إلى DirectX (.X)"""
        from mef_igi2_export import export_to_directx as dx_export
        return dx_export(self, output_path, "igi2", self.debug_params)

    def fixed_export_to_directx(model, output_path: str, model_type: str = "auto", debug_params: 'MefDebugParams' = None):
        """
        تصدير نموذج (MEF, SMD, OBJ, MDL) إلى ملف DirectX (.X) - نسخة مصلحة
        """
        print(f"   DEBUG: export_to_directx called with model_type={model_type}, output_path={output_path}")
        if debug_params is None:
            debug_params = MefDebugParams()
        
        exporter = DirectXExporter()
        
        # تحديد نوع النموذج
        if model_type == "auto":
            if hasattr(model, 'txan_data') or hasattr(model, 'render_mesh_data'):
                model_type = "igi2"
            elif hasattr(model, 'nodes') and hasattr(model, 'triangles'):
                model_type = "smd"
            elif hasattr(model, 'materials'):
                model_type = "obj"
            elif hasattr(model, 'bones'):
                model_type = "igi1"
            elif hasattr(model, 'header') and hasattr(model.header, 'numbones'):
                model_type = "mdl"
        
        # التصدير حسب النوع
        if model_type in ["igi1", "igi2"]:
            exporter.from_mef_model(model, debug_params)
        elif model_type == "smd":
            exporter.from_smd_model(model)
        elif model_type == "obj":
            exporter.from_obj_model(model)
        elif model_type == "mdl":
            # استخدام الدالة الجديدة لـ MDL
            if hasattr(exporter, 'from_mdl_model'):
                exporter.from_mdl_model(model)
            else:
                # طريقة بديلة
                for i, bone in enumerate(model.bones):
                    parent_id = bone.parent if hasattr(bone, 'parent') else -1
                    frame = DXFrame(
                        name=bone.name,
                        parent_id=parent_id,
                        position=(bone.value[0] if len(bone.value) > 0 else 0,
                                 bone.value[2] if len(bone.value) > 2 else 0,
                                 bone.value[1] if len(bone.value) > 1 else 0)
                    )
                    exporter.frames.append(frame)
                
                # استخراج الشبكة
                for v in model.vertices:
                    exporter.frames[0].vertices.append((v.x, v.z, v.y))
                for tri in model.triangles:
                    if len(tri.vertindex) >= 3:
                        exporter.frames[0].faces.append((tri.vertindex[0], tri.vertindex[1], tri.vertindex[2]))
                
                print(f"   📦 Extracted mesh from MDL: {len(exporter.frames[0].vertices)} vertices, {len(exporter.frames[0].faces)} faces")
                print(f"   🦴 Extracted {len(exporter.frames)} bones/frames from MDL")
        else:
            raise ValueError(f"Unsupported model type: {model_type}")
        
        # حفظ الملف
        exporter.export_to_file(output_path)
        
        print(f"\n✅ Exported to DirectX: {output_path}")
        print(f"   📊 Frames: {len(exporter.frames)}")
        print(f"   🎨 Skin Weights: {len(exporter.skin_weights)}")
        print(f"   🎬 Animations: {len(exporter.animations)}")
        
        return True

def fix_export_to_directx_in_main(input_path, output_subdir, file_type, model, export_formats):
    """دالة مساعدة لتصدير DirectX من main()"""
    if "directx" not in export_formats:
        return
    
    print(f"   DEBUG: DirectX export triggered for {file_type}")
    try:
        dx_path = os.path.join(output_subdir, f"{Path(input_path).stem}.x")
        
        if file_type == "MEF":
            # تحديد إصدار IGI
            if hasattr(model, 'txan_data') or hasattr(model, 'render_mesh_data'):
                version = "IGI2"
            else:
                version = "IGI1"
            export_to_directx(model, dx_path, "igi2" if version == "IGI2" else "igi1")
        elif file_type == "MDL":
            export_to_directx(model, dx_path, "auto")
        elif file_type == "SMD":
            export_to_directx(model, dx_path, "smd")
        elif file_type == "OBJ":
            export_to_directx(model, dx_path, "obj")
        else:
            print(f"   ⚠️ DirectX export not supported for {file_type}")
            return
        
        print(f"   ✅ DirectX export completed: {dx_path}")
    except Exception as e:
        print(f"   ⚠️ DirectX export failed: {e}")
        import traceback
        traceback.print_exc()

    def from_mef_model_fixed(self, model, debug_params: 'MefDebugParams' = None):
        if debug_params is None:
            debug_params = MefDebugParams()
        
        if hasattr(model, 'bones') and model.bones:
            for i, bone in enumerate(model.bones):
                parent_name = ""
                if hasattr(bone, 'parent_id') and bone.parent_id >= 0:
                    parent_name = model.bones[bone.parent_id].name if bone.parent_id < len(model.bones) else ""
                
                frame = DXFrame(
                    name=bone.name,
                    parent_id=bone.parent_id if hasattr(bone, 'parent_id') else -1,
                    parent_name=parent_name,
                    position=(bone.pos.x, bone.pos.y, bone.pos.z)
                )
                self.frames.append(frame)
            
            print(f"   🦴 Extracted {len(self.frames)} bones/frames")
        
        if hasattr(model, 'render_mesh_data') and model.render_mesh_data:
            mesh_data = model.render_mesh_data
            
            if hasattr(mesh_data, 'vertices'):
                vertices = mesh_data.vertices
                
                for i, v in enumerate(vertices):
                    bone_id = None
                    weight = None
                    
                    if "bone_id" in v.dtype.names:
                        bid = v["bone_id"]
                        if isinstance(bid, np.ndarray):
                            bone_id = int(bid[0]) if len(bid) > 0 else None
                        else:
                            bone_id = int(bid) if bid is not None else None
                    
                    if "weight" in v.dtype.names:
                        w = v["weight"]
                        if isinstance(w, np.ndarray):
                            weight = float(w[0]) if len(w) > 0 else None
                        else:
                            weight = float(w) if w is not None else None
                    
                    if bone_id is not None and weight is not None and weight > 0:
                        if bone_id < len(model.bones):
                            self.skin_weights.append(DXSkinWeight(
                                bone_name=model.bones[bone_id].name,
                                vertex_index=i,
                                weight=weight
                            ))
                
                print(f"   🎨 Extracted {len(self.skin_weights)} skin weights")
        
        self._extract_mesh_from_mef(model, debug_params)
        self._extract_materials_from_mef(model)
        self._extract_animations_from_mef(model)
        
        return self

    def _extract_mesh_from_mef_fixed(self, model, debug_params):
        """استخراج الشبكة من نموذج MEF - نسخة مصلحة"""
        if not hasattr(model, 'render_mesh_data') or not model.render_mesh_data:
            return
        
        mesh_data = model.render_mesh_data
        
        if hasattr(mesh_data, 'vertices'):
            vertices = mesh_data.vertices
            
            for i, v in enumerate(vertices):
                # استخراج الموقع
                if "pos" in v.dtype.names:
                    px, py, pz = float(v["pos"][0]), float(v["pos"][1]), float(v["pos"][2])
                elif "px" in v.dtype.names:
                    px, py, pz = float(v["px"]), float(v["py"]), float(v["pz"])
                else:
                    px, py, pz = 0.0, 0.0, 0.0
                
                px, py, pz = debug_params.swizzle(px, py, pz, debug_params.v_scale)
                
                # استخراج الطبيعية
                if "normal" in v.dtype.names:
                    nx, ny, nz = float(v["normal"][0]), float(v["normal"][1]), float(v["normal"][2])
                elif "nx" in v.dtype.names:
                    nx, ny, nz = float(v["nx"]), float(v["ny"]), float(v["nz"])
                else:
                    nx, ny, nz = 0.0, 0.0, 0.0
                
                nx, ny, nz = debug_params.swizzle(nx, ny, nz, 1.0)
                
                # استخراج UV
                if "uv0" in v.dtype.names:
                    u, vt = float(v["uv0"][0]), float(v["uv0"][1])
                elif "u" in v.dtype.names and "v" in v.dtype.names:
                    u, vt = float(v["u"]), float(v["v"])
                else:
                    u, vt = 0.0, 0.0
                
                frame_idx = 0
                if hasattr(v, 'bone_id') and self.frames:
                    bone_id_val = v["bone_id"]
                    if isinstance(bone_id_val, np.ndarray):
                        bone_id = int(bone_id_val[0]) if len(bone_id_val) > 0 else 0
                    else:
                        bone_id = int(bone_id_val)
                    if 0 <= bone_id < len(self.frames):
                        frame_idx = bone_id
                
                while frame_idx >= len(self.frames):
                    self.frames.append(DXFrame(name=f"bone_{len(self.frames)}"))
                
                self.frames[frame_idx].vertices.append((px, py, pz))
                self.frames[frame_idx].normals.append((nx, ny, nz))
                self.frames[frame_idx].uvs.append((u, vt))
            
            if hasattr(mesh_data, 'faces'):
                for face in mesh_data.faces:
                    if len(face) >= 3:
                        self.frames[0].faces.append((int(face[0]), int(face[1]), int(face[2])))
            
            print(f"   📦 Extracted mesh: {len(self.frames[0].vertices)} vertices, {len(self.frames[0].faces)} faces")

def fix_directx_bone_extraction():
    """تصحيح استخراج العظام من MEF لـ DirectXExporter"""
    
    def from_mef_model_fixed(self, model, debug_params: 'MefDebugParams' = None):
        if debug_params is None:
            debug_params = MefDebugParams()
        
        if hasattr(model, 'bones') and model.bones:
            for i, bone in enumerate(model.bones):
                parent_name = ""
                if hasattr(bone, 'parent_id') and bone.parent_id >= 0:
                    parent_name = model.bones[bone.parent_id].name if bone.parent_id < len(model.bones) else ""
                
                frame = DXFrame(
                    name=bone.name,
                    parent_id=bone.parent_id if hasattr(bone, 'parent_id') else -1,
                    parent_name=parent_name,
                    position=(bone.pos.x, bone.pos.y, bone.pos.z)
                )
                self.frames.append(frame)
            
            print(f"   🦴 Extracted {len(self.frames)} bones/frames")
        
        if hasattr(model, 'render_mesh_data') and model.render_mesh_data:
            mesh_data = model.render_mesh_data
            
            if hasattr(mesh_data, 'vertices'):
                vertices = mesh_data.vertices
                
                for i, v in enumerate(vertices):
                    bone_id = None
                    weight = None
                    
                    if "bone_id" in v.dtype.names:
                        bid = v["bone_id"]
                        if isinstance(bid, np.ndarray):
                            bone_id = int(bid[0]) if len(bid) > 0 else None
                        else:
                            bone_id = int(bid) if bid is not None else None
                    
                    if "weight" in v.dtype.names:
                        w = v["weight"]
                        if isinstance(w, np.ndarray):
                            weight = float(w[0]) if len(w) > 0 else None
                        else:
                            weight = float(w) if w is not None else None
                    
                    if bone_id is not None and weight is not None and weight > 0:
                        if bone_id < len(model.bones):
                            self.skin_weights.append(DXSkinWeight(
                                bone_name=model.bones[bone_id].name,
                                vertex_index=i,
                                weight=weight
                            ))
                
                print(f"   🎨 Extracted {len(self.skin_weights)} skin weights")
        
        self._extract_mesh_from_mef(model, debug_params)
        self._extract_materials_from_mef(model)
        self._extract_animations_from_mef(model)
        
        return self
    
    DirectXExporter.from_mef_model = from_mef_model_fixed
    print("✅ Fixed bone extraction for DirectXExporter")

def fix_directx_mesh_extraction():
    """تصحيح استخراج الشبكة من MEF لـ DirectXExporter"""
    
    def _extract_mesh_from_mef_fixed(self, model, debug_params):
        """استخراج الشبكة من نموذج MEF - نسخة مصلحة"""
        if not hasattr(model, 'render_mesh_data') or not model.render_mesh_data:
            return
        
        mesh_data = model.render_mesh_data
        
        if hasattr(mesh_data, 'vertices'):
            vertices = mesh_data.vertices
            
            for i, v in enumerate(vertices):
                # استخراج الموقع
                if "pos" in v.dtype.names:
                    px, py, pz = float(v["pos"][0]), float(v["pos"][1]), float(v["pos"][2])
                elif "px" in v.dtype.names:
                    px, py, pz = float(v["px"]), float(v["py"]), float(v["pz"])
                else:
                    px, py, pz = 0.0, 0.0, 0.0
                
                px, py, pz = debug_params.swizzle(px, py, pz, debug_params.v_scale)
                
                # استخراج الطبيعية
                if "normal" in v.dtype.names:
                    nx, ny, nz = float(v["normal"][0]), float(v["normal"][1]), float(v["normal"][2])
                elif "nx" in v.dtype.names:
                    nx, ny, nz = float(v["nx"]), float(v["ny"]), float(v["nz"])
                else:
                    nx, ny, nz = 0.0, 0.0, 0.0
                
                nx, ny, nz = debug_params.swizzle(nx, ny, nz, 1.0)
                
                # استخراج UV
                if "uv0" in v.dtype.names:
                    u, vt = float(v["uv0"][0]), float(v["uv0"][1])
                elif "u" in v.dtype.names and "v" in v.dtype.names:
                    u, vt = float(v["u"]), float(v["v"])
                else:
                    u, vt = 0.0, 0.0
                
                frame_idx = 0
                if hasattr(v, 'bone_id') and self.frames:
                    bone_id_val = v["bone_id"]
                    if isinstance(bone_id_val, np.ndarray):
                        bone_id = int(bone_id_val[0]) if len(bone_id_val) > 0 else 0
                    else:
                        bone_id = int(bone_id_val)
                    if 0 <= bone_id < len(self.frames):
                        frame_idx = bone_id
                
                while frame_idx >= len(self.frames):
                    self.frames.append(DXFrame(name=f"bone_{len(self.frames)}"))
                
                self.frames[frame_idx].vertices.append((px, py, pz))
                self.frames[frame_idx].normals.append((nx, ny, nz))
                self.frames[frame_idx].uvs.append((u, vt))
            
            if hasattr(mesh_data, 'faces'):
                for face in mesh_data.faces:
                    if len(face) >= 3:
                        self.frames[0].faces.append((int(face[0]), int(face[1]), int(face[2])))
            
            print(f"   📦 Extracted mesh: {len(self.frames[0].vertices)} vertices, {len(self.frames[0].faces)} faces")
    
    # تطبيق الدالة المُصححة
    DirectXExporter._extract_mesh_from_mef = _extract_mesh_from_mef_fixed
    print("✅ Fixed mesh extraction for DirectXExporter")

def fix_export_to_directx():
    """تحديث export_to_directx لدعم جميع أنواع النماذج بشكل صحيح"""
    
    original_export_to_directx = export_to_directx
    
    def fixed_export_to_directx(model, output_path: str, model_type: str = "auto", debug_params: 'MefDebugParams' = None):
        """
        تصدير نموذج (MEF, SMD, OBJ, MDL) إلى ملف DirectX (.X) - نسخة مصلحة
        """
        print(f"   DEBUG: export_to_directx called with model_type={model_type}, output_path={output_path}")
        if debug_params is None:
            debug_params = MefDebugParams()
        
        exporter = DirectXExporter()
        
        # تحديد نوع النموذج
        if model_type == "auto":
            if hasattr(model, 'txan_data') or hasattr(model, 'render_mesh_data'):
                model_type = "igi2"
            elif hasattr(model, 'nodes') and hasattr(model, 'triangles'):
                model_type = "smd"
            elif hasattr(model, 'materials'):
                model_type = "obj"
            elif hasattr(model, 'bones'):
                model_type = "igi1"
            elif hasattr(model, 'header') and hasattr(model.header, 'numbones'):
                model_type = "mdl"
        
        # التصدير حسب النوع
        if model_type in ["igi1", "igi2"]:
            exporter.from_mef_model(model, debug_params)
        elif model_type == "smd":
            exporter.from_smd_model(model)
        elif model_type == "obj":
            exporter.from_obj_model(model)
        elif model_type == "mdl":
            # استخدام الدالة الجديدة لـ MDL
            if hasattr(exporter, 'from_mdl_model'):
                exporter.from_mdl_model(model)
            else:
                # طريقة بديلة
                for i, bone in enumerate(model.bones):
                    parent_id = bone.parent if hasattr(bone, 'parent') else -1
                    frame = DXFrame(
                        name=bone.name,
                        parent_id=parent_id,
                        position=(bone.value[0] if len(bone.value) > 0 else 0,
                                 bone.value[2] if len(bone.value) > 2 else 0,
                                 bone.value[1] if len(bone.value) > 1 else 0)
                    )
                    exporter.frames.append(frame)
                
                # استخراج الشبكة
                for v in model.vertices:
                    exporter.frames[0].vertices.append((v.x, v.z, v.y))
                for tri in model.triangles:
                    if len(tri.vertindex) >= 3:
                        exporter.frames[0].faces.append((tri.vertindex[0], tri.vertindex[1], tri.vertindex[2]))
                
                print(f"   📦 Extracted mesh from MDL: {len(exporter.frames[0].vertices)} vertices, {len(exporter.frames[0].faces)} faces")
                print(f"   🦴 Extracted {len(exporter.frames)} bones/frames from MDL")
        else:
            raise ValueError(f"Unsupported model type: {model_type}")
        
        # حفظ الملف
        exporter.export_to_file(output_path)
        
        print(f"\n✅ Exported to DirectX: {output_path}")
        print(f"   📊 Frames: {len(exporter.frames)}")
        print(f"   🎨 Skin Weights: {len(exporter.skin_weights)}")
        print(f"   🎬 Animations: {len(exporter.animations)}")
        
        return True
    
    # استبدال الدالة
    globals()['export_to_directx'] = fixed_export_to_directx
    print("✅ Fixed export_to_directx function")

def apply_all_directx_fixes():
    """تطبيق جميع إصلاحات DirectX"""
    print("\n🔧 Applying DirectX fixes...")
    fix_directx_mesh_extraction()
    fix_directx_bone_extraction()
    fix_directx_mdl_extraction()
    fix_export_to_directx()
    print("✅ All DirectX fixes applied successfully")

def convert_to_directx(input_path: str, output_path: str = None, 
                       debug_params: 'MefDebugParams' = None) -> bool:
    """
    تحويل ملف MEF أو SMD أو OBJ إلى DirectX (.X)
    
    Args:
        input_path: مسار ملف الإدخال
        output_path: مسار ملف الإخراج (اختياري)
        debug_params: معاملات التصحيح
    
    Returns:
        True إذا نجح التحويل، False إذا فشل
    """
    if debug_params is None:
        debug_params = MefDebugParams()
    
    if output_path is None:
        output_path = Path(input_path).with_suffix('.x')
    
    try:
        with open(input_path, "rb") as f:
            data = f.read()
        
        buffer = Buffer(data)
        file_type = detect_file_type(buffer, input_path)
        
        if file_type == "MEF":
            version = detect_mef_version(buffer)
            if version == "IGI2":
                model = MefModelIGI2(buffer, export_mode="multi")
            else:
                model = MefModelIGI1(buffer, export_mode="multi")
            
            export_to_directx(model, str(output_path), 
                            "igi2" if version == "IGI2" else "igi1", 
                            debug_params)
        
        elif file_type == "SMD":
            with open(input_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            model = SMDExporter.from_string(content)
            
            export_to_directx(model, str(output_path), "smd", debug_params)
        
        elif file_type == "OBJ":
            model = OBJExporter.from_file(input_path)
            
            export_to_directx(model, str(output_path), "obj", debug_params)
        
        else:
            print(f"❌ Unsupported file type: {file_type}")
            return False
        
        print(f"✅ Successfully converted to DirectX: {output_path}")
        return True
        
    except Exception as e:
        print(f"❌ Error converting to DirectX: {e}")
        import traceback
        traceback.print_exc()
        return False

def batch_convert_to_directx(input_dir: str, output_dir: str = None,
                             debug_params: 'MefDebugParams' = None) -> dict:
    """
    تحويل جميع ملفات MEF و SMD و OBJ في مجلد إلى DirectX (.X)
    
    Args:
        input_dir: مجلد الإدخال
        output_dir: مجلد الإخراج (اختياري)
        debug_params: معاملات التصحيح
    
    Returns:
        قاموس بنتائج التحويل
    """
    if debug_params is None:
        debug_params = MefDebugParams()
    
    if output_dir is None:
        output_dir = input_dir + "_directx"
    
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    # البحث عن الملفات
    extensions = ['*.mef', '*.MEF', '*.mdl', '*.MDL', '*.smd', '*.SMD', '*.obj', '*.OBJ']
    files = []
    for ext in extensions:
        files.extend(Path(input_dir).glob(ext))
    
    if not files:
        print(f"No supported files found in {input_dir}")
        return {"total": 0, "successful": 0, "failed": 0}
    
    print(f"\n📁 Found {len(files)} files to convert to DirectX")
    print("=" * 60)
    
    successful = 0
    failed = 0
    
    for file_path in files:
        output_path = Path(output_dir) / f"{file_path.stem}.x"
        
        print(f"\n🔄 Converting: {file_path.name}")
        
        if convert_to_directx(str(file_path), str(output_path), debug_params):
            successful += 1
            print(f"   ✅ Output: {output_path}")
        else:
            failed += 1
    
    print("\n" + "=" * 60)
    print("📊 DIRECTX BATCH CONVERSION REPORT")
    print("=" * 60)
    print(f"   Total files    : {len(files)}")
    print(f"   Successful     : {successful}")
    print(f"   Failed         : {failed}")
    print(f"   Output folder  : {output_dir}")
    print("=" * 60)
    
    return {"total": len(files), "successful": successful, "failed": failed}
