"""
exporters/mef_igi2/export_atlas.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math

# ========== Constants ==========
ENABLE_TEXTURE_ATLAS_SMD = False   # تفعيل الأطلس لـ SMD
ENABLE_TEXTURE_ATLAS_OBJ = True   # تفعيل الأطلس لـ OBJ  
ENABLE_TEXTURE_ATLAS_MDL = True   # تفعيل الأطلس لـ MDL
ATLAS_MODE = "preserve"  # القيمة الافتراضية: preserve

# ========== Classes ==========
class TextureAtlas:
    """يدمج عدة صور في صورة واحدة كبيرة (Texture Atlas) مع تتبع مواقعها"""
    
    def __init__(self, texture_dir: str, max_size: int = 8192):
        """
        Args:
            texture_dir: المجلد الذي يحتوي على ملفات القوام
            max_size: الحد الأقصى لأبعاد الأطلس (عرض وارتفاع)
        """
        self.texture_dir = texture_dir
        self.max_size = max_size
        self.texture_paths = []  # مسارات ملفات القوام
        self.texture_names = []  # أسماء الملفات (للمطابقة)
        self.positions = []      # مواقع القوام في الأطلس (x, y, width, height)
        self.atlas_image = None
        self.atlas_size = (0, 0)
        self.texture_indices = {}  # اسم القوام -> الرقم التسلسلي
        
    def _next_power_of_two(self, n: int) -> int:
        """تقريب الرقم إلى أقرب قوة للعدد 2"""
        return 1 << (n - 1).bit_length()    
    
    def find_texture_file(self, texture_name: str) -> str:
        """البحث عن ملف القوام في texture_dir بالصيغ المدعومة"""
        # قائمة الصيغ المدعومة
        extensions = ['.png', '.PNG', '.tga', '.TGA', '.jpg', '.JPG', '.jpeg', '.JPEG', '.bmp', '.BMP']
        
        # إذا كان الملف موجوداً بالاسم الكامل
        full_path = os.path.join(self.texture_dir, texture_name)
        if os.path.exists(full_path):
            return full_path
        
        # جرب إضافة صيغ مختلفة
        base_name = os.path.splitext(texture_name)[0]
        for ext in extensions:
            test_path = os.path.join(self.texture_dir, base_name + ext)
            if os.path.exists(test_path):
                return test_path
        
        return None
    
    def add_texture(self, texture_name: str) -> bool:
        """إضافة قوام إلى قائمة الانتظار للدمج"""
        file_path = self.find_texture_file(texture_name)
        if file_path:
            self.texture_paths.append(file_path)
            self.texture_names.append(texture_name)
            self.texture_indices[texture_name] = len(self.texture_paths) - 1
            return True
        else:
            print(f"   Warning: Texture '{texture_name}' not found in {self.texture_dir}")
            return False
    
    def pack_textures(self) -> bool:
        """ترتيب القوام في شبكة ودمجها في صورة واحدة"""
        if not self.texture_paths:
            return False
        
        # تحميل جميع الصور
        images = []
        widths = []
        heights = []
        
        for path in self.texture_paths:
            if not os.path.exists(path):
                print(f"   Error: Texture file not found: {path}")
                return False
            try:
                img = Image.open(path)
                if img.mode != 'RGBA':
                    img = img.convert('RGBA')
                images.append(img)
                widths.append(img.width)
                heights.append(img.height)
            except Exception as e:
                print(f"   Error loading {path}: {e}")
                return False
        
        # حالة صورة واحدة فقط
        if len(images) == 1:
            self.atlas_image = images[0]
            self.positions = [(0, 0, images[0].width, images[0].height)]
            self.atlas_size = (images[0].width, images[0].height)
            return True
        
        # حساب أفضل ترتيب (بسيط: ترتيب تنازلي حسب المساحة)
        indices = list(range(len(images)))
        indices.sort(key=lambda i: -widths[i] * heights[i])
        
        # محاولة الترتيب في شبكة
        # أولاً: جرب ترتيباً أفقياً
        total_width = sum(widths[i] for i in indices)
        max_height = max(heights[i] for i in indices)
        
        if total_width <= self.max_size and max_height <= self.max_size:
            # ترتيب أفقي
            atlas_width = self._next_power_of_two(total_width)
            atlas_height = self._next_power_of_two(max_height)
            
            self.atlas_image = Image.new('RGBA', (atlas_width, atlas_height), (0, 0, 0, 0))
            
            x = 0
            positions = [None] * len(images)
            for idx in indices:
                img = images[idx]
                self.atlas_image.paste(img, (x, 0))
                positions[idx] = (x, 0, img.width, img.height)
                x += img.width
            
            self.positions = positions
            self.atlas_size = (atlas_width, atlas_height)
            return True
        
        # ثانياً: ترتيب في شبكة (تقدير عدد الأعمدة)
        import math
        num_images = len(images)
        cols = int(math.ceil(math.sqrt(num_images)))
        rows = int(math.ceil(num_images / cols))
        
        # حساب أبعاد الخلايا (نأخذ أكبر عرض وارتفاع)
        cell_width = max(widths)
        cell_height = max(heights)
        
        atlas_width = cols * cell_width
        atlas_height = rows * cell_height
        
        # تقريب الأبعاد إلى أقرب قوة للعدد 2
        atlas_width = self._next_power_of_two(atlas_width)
        atlas_height = self._next_power_of_two(atlas_height)
        
        if atlas_width <= self.max_size and atlas_height <= self.max_size:
            self.atlas_image = Image.new('RGBA', (atlas_width, atlas_height), (0, 0, 0, 0))
            
            positions = [None] * len(images)
            for i, idx in enumerate(indices):
                col = i % cols
                row = i // cols
                x = col * cell_width
                y = row * cell_height
                
                img = images[idx]
                # توسيط الصورة في الخلية
                x_offset = (cell_width - img.width) // 2
                y_offset = (cell_height - img.height) // 2
                
                self.atlas_image.paste(img, (x + x_offset, y + y_offset))
                positions[idx] = (x + x_offset, y + y_offset, img.width, img.height)
            
            self.positions = positions
            self.atlas_size = (atlas_width, atlas_height)
            return True
        
        print(f"   Warning: Could not pack textures within {self.max_size}x{self.max_size}")
        return False
    
    def get_uv_transform(self, texture_name: str, original_uvs: np.ndarray) -> np.ndarray:
        """
        تحويل إحداثيات UV من مساحة القوام الأصلي إلى مساحة الأطلس
        """
        import math
        
        if texture_name not in self.texture_indices:
            return original_uvs
        
        idx = self.texture_indices[texture_name]
        if idx >= len(self.positions):
            return original_uvs
        
        x, y, w, h = self.positions[idx]
        atlas_w, atlas_h = self.atlas_size
        
        # ========== التصحيح: تطبيع UVs إلى النطاق [0, 1] ==========
        # إذا كانت UVs خارج النطاق [0,1]، نقوم بتطبيعها باستخدام modulo
        # هذا يحافظ على التكرار (tiling) الصحيح للقوام
        normalized_uvs = original_uvs.copy()
        
        # تطبيع U: نأخذ الجزء الكسري فقط
        # هذا يحافظ على سلوك التكرار (wrap) للقوام عند تجاوز الحدود
        normalized_uvs[:, 0] = normalized_uvs[:, 0] - np.floor(normalized_uvs[:, 0])
        # تطبيع V: نفس الشيء
        normalized_uvs[:, 1] = normalized_uvs[:, 1] - np.floor(normalized_uvs[:, 1])
        
        # أو بدلاً من ذلك، استخدام modulo:
        # normalized_uvs[:, 0] = normalized_uvs[:, 0] % 1.0
        # normalized_uvs[:, 1] = normalized_uvs[:, 1] % 1.0
        # =========================================================
        
        # تحويل الإحداثيات المطبعة
        u_min = x / atlas_w
        v_min = y / atlas_h
        u_max = (x + w) / atlas_w
        v_max = (y + h) / atlas_h
        
        # تطبيق التحويل على كل نقطة مع استخدام UVs المطبعة
        transformed = np.zeros_like(normalized_uvs)
        transformed[:, 0] = u_min + normalized_uvs[:, 0] * (u_max - u_min)
        transformed[:, 1] = v_min + normalized_uvs[:, 1] * (v_max - v_min)
        
        return transformed
    
    def get_texture_index(self, texture_name: str) -> int:
        """الحصول على الرقم التسلسلي للقوام"""
        return self.texture_indices.get(texture_name, -1)
    
    def save_atlas(self, output_path: str, format: str = 'PNG') -> bool:
        """حفظ صورة الأطلس"""
        if self.atlas_image:
            self.atlas_image.save(output_path, format)
            return True
        return False
    
    def has_multiple_textures(self) -> bool:
        """هل هناك أكثر من قوام واحد؟"""
        return len(self.texture_paths) > 1


# ========== Functions ==========
    def export_all_with_atlas(self, output_dir: str, base_name: str, export_formats: List[str] = None):
        """تصدير SMD إلى جميع الصيغ مع دعم الأطلس"""
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt"]
        
        self.ensure_dir(output_dir)
        
        print(f"\nExporting SMD to {output_dir}")
        print("-" * 50)
        
        if "obj" in export_formats:
            export_obj_with_atlas(self, os.path.join(output_dir, base_name))
        
        if "gltf" in export_formats:
            export_gltf_with_atlas(self, os.path.join(output_dir, base_name))
        
        if "json" in export_formats:
            self.export_json(os.path.join(output_dir, f"{base_name}.json"))
        
        if "txt" in export_formats:
            self.export_txt(os.path.join(output_dir, f"{base_name}_info.txt"))
        
        print("-" * 50)
        print("Export completed successfully!")

    def export_gltf_with_atlas(self, output_path: str):
        """تصدير SMD إلى glTF مع دعم الأطلس"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available, skipping glTF export")
            return
        
        vertices, faces = self.to_vertices_array()
        
        if len(vertices) == 0:
            print("No vertices to export")
            return
        
        base_name = os.path.splitext(output_path)[0]
        
        # التحقق من تفعيل الأطلس
        use_atlas = ENABLE_TEXTURE_ATLAS_SMD and PIL_AVAILABLE
        atlas = None
        
        if use_atlas:
            texture_dir = os.path.dirname(output_path)
            atlas = create_atlas_for_model(self, texture_dir, os.path.basename(base_name))
            use_atlas = atlas and atlas.has_multiple_textures()
            
            if use_atlas and atlas:
                # ========== 🔴 تحديث UVs مباشرة في مصفوفة vertices ==========
                print(f"\n   🔧 Updating SMD UVs for atlas (glTF)...")
                all_uvs = np.array([[v['u'], v['v']] for v in vertices])
                first_texture = list(atlas.texture_names)[0] if atlas.texture_names else "texture.png"
                new_uvs = atlas.get_uv_transform(first_texture, all_uvs)
                for i, v in enumerate(vertices):
                    v['u'] = new_uvs[i, 0]
                    v['v'] = new_uvs[i, 1]
                print(f"   ✅ Updated {len(vertices)} vertices UVs")
        
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="SMD Exporter (Crowbar)", version="2.0")
            
            positions = []
            normals = []
            uvs = []
            weights = []
            joints = []
            
            for v in vertices:
                positions.extend([v['px'], v['py'], v['pz']])
                normals.extend([v['nx'], v['ny'], v['nz']])
                uvs.extend([v['u'], 1.0 - v['v']])
                weights.extend([v['weight'], 0.0, 0.0, 0.0])
                joints.extend([v['bone_id'], 0, 0, 0])
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(vertices), type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # Normals
            norm_bytes = np.array(normals, dtype=np.float32).tobytes()
            norm_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(norm_bytes), target=34962)
            gltf.bufferViews.append(norm_bv)
            binary_data.extend(norm_bytes)
            
            norm_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                count=len(vertices), type="VEC3")
            gltf.accessors.append(norm_acc)
            
            # UVs
            uv_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                              count=len(vertices), type="VEC2")
            gltf.accessors.append(uv_acc)
            
            # Weights
            weights_bytes = np.array(weights, dtype=np.float32).tobytes()
            weights_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(weights_bytes), target=34962)
            gltf.bufferViews.append(weights_bv)
            binary_data.extend(weights_bytes)
            
            weights_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                   count=len(vertices), type="VEC4")
            gltf.accessors.append(weights_acc)
            
            # Joints
            joints_bytes = np.array(joints, dtype=np.uint16).tobytes()
            joints_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(joints_bytes), target=34962)
            gltf.bufferViews.append(joints_bv)
            binary_data.extend(joints_bytes)
            
            joints_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5123,
                                  count=len(vertices), type="VEC4")
            gltf.accessors.append(joints_acc)
            
            # Indices
            indices_list = []
            for face in faces:
                indices_list.extend([face[0], face[1], face[2]])
            
            indices_bytes = np.array(indices_list, dtype=np.uint32).tobytes()
            indices_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(indices_bytes), target=34963)
            gltf.bufferViews.append(indices_bv)
            binary_data.extend(indices_bytes)
            
            indices_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                                   count=len(indices_list), type="SCALAR")
            gltf.accessors.append(indices_acc)
            
            # Buffer
            base_filename = os.path.splitext(os.path.basename(output_path))[0]
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_filename}.bin"))
            
            attributes = Attributes(POSITION=0, NORMAL=1, TEXCOORD_0=2, WEIGHTS_0=3, JOINTS_0=4)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            # العظام
            if self.nodes:
                bone_nodes = []
                for node in self.nodes:
                    gltf_node = Node(name=node.name)
                    gltf.nodes.append(gltf_node)
                    bone_nodes.append(len(gltf.nodes)-1)
                
                for i, node in enumerate(self.nodes):
                    if node.parent_id >= 0:
                        parent_idx = None
                        for j, n in enumerate(self.nodes):
                            if n.id == node.parent_id:
                                parent_idx = bone_nodes[j]
                                break
                        if parent_idx is not None:
                            if gltf.nodes[parent_idx].children is None:
                                gltf.nodes[parent_idx].children = []
                            gltf.nodes[parent_idx].children.append(bone_nodes[i])
                
                skin = Skin(joints=bone_nodes)
                gltf.skins.append(skin)
                
                node = Node(mesh=0, skin=len(gltf.skins)-1)
                gltf.nodes.append(node)
                scene = Scene(nodes=[len(gltf.nodes)-1])
            else:
                node = Node(mesh=0)
                gltf.nodes.append(node)
                scene = Scene(nodes=[0])
            
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            gltf.save(f"{output_path}.gltf")
            with open(f"{os.path.splitext(output_path)[0]}.bin", 'wb') as f:
                f.write(binary_data)
            
            if use_atlas:
                print(f"   glTF: {output_path}.gltf (using texture atlas)")
            else:
                print(f"   glTF: {output_path}.gltf")
            print(f"   glTF binary: {os.path.splitext(output_path)[0]}.bin")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
            import traceback
            traceback.print_exc()

    def export_obj_with_atlas(self, output_path: str):
        """تصدير SMD إلى OBJ مع دعم المواد المتعددة - نسخة محسنة"""
        vertices, faces = self.to_vertices_array()
        
        if len(vertices) == 0:
            print("No vertices to export")
            return
        
        base_name = os.path.splitext(output_path)[0]
        obj_path = f"{base_name}.obj"
        mtl_path = f"{base_name}.mtl"
        
        # ========== استخدام المواد المستخرجة من SMD ==========
        material_names = []
        face_to_material = {}
        
        if hasattr(self, 'materials') and self.materials:
            material_names = self.materials
            print(f"   Using {len(material_names)} materials from SMD: {material_names}")
            
            # بناء تعيين من مؤشر الوجه إلى اسم المادة
            if hasattr(self, 'material_triangle_indices') and self.material_triangle_indices:
                for mat_name, tri_indices in self.material_triangle_indices.items():
                    for tri_idx in tri_indices:
                        face_to_material[tri_idx] = mat_name
                print(f"   Mapped {len(face_to_material)} faces to materials")
        else:
            material_names = ["smd_material"]
            print(f"   No materials found in SMD, using default material")
        
        # ========== تجميع الوجوه حسب المادة ==========
        material_faces_map = {}
        for mat_name in material_names:
            material_faces_map[mat_name] = []
        
        if face_to_material:
            for face_idx, face in enumerate(faces):
                mat_name = face_to_material.get(face_idx, material_names[0])
                if mat_name not in material_faces_map:
                    material_faces_map[mat_name] = []
                material_faces_map[mat_name].append(face)
        else:
            material_faces_map[material_names[0]] = faces
        
        # ========== التحقق من تفعيل الأطلس ==========
        use_atlas = ENABLE_TEXTURE_ATLAS_SMD and PIL_AVAILABLE
        atlas = None
        
        if use_atlas and len(material_names) > 1:
            texture_dir = os.path.dirname(output_path)
            atlas = create_atlas_for_model(self, texture_dir, os.path.basename(base_name), material_names)
            use_atlas = atlas and atlas.has_multiple_textures()
        
        # ========== كتابة ملف MTL ==========
        with open(mtl_path, 'w', encoding='utf-8') as f:
            for mat_name in material_names:
                # تنظيف اسم المادة
                clean_mat_name = mat_name.replace('\\', '/').split('/')[-1]
                clean_mat_name = clean_mat_name.split('.')[0] if '.' in clean_mat_name else clean_mat_name
                clean_mat_name = clean_mat_name.replace(' ', '_').replace('-', '_')
                if not clean_mat_name:
                    clean_mat_name = f"material_{material_names.index(mat_name)}"
                
                # اسم ملف القوام
                if use_atlas and atlas:
                    tex_file = f"{os.path.basename(base_name)}_atlas.png"
                else:
                    tex_file = mat_name
                    if not tex_file.endswith('.tga') and not tex_file.endswith('.png') and not tex_file.endswith('.bmp'):
                        tex_file = f"{clean_mat_name}.png"
                
                f.write(f"newmtl {clean_mat_name}\n")
                f.write("Ns 10.0000\n")
                f.write("Ka 1.0000 1.0000 1.0000\n")
                f.write("Kd 1.0000 1.0000 1.0000\n")
                f.write("Ks 0.0000 0.0000 0.0000\n")
                f.write(f"map_Kd {tex_file}\n")
                f.write("\n")
        
        # ========== تحديث UVs إذا كان الأطلس مفعلاً ==========
        if use_atlas and atlas:
            print(f"\n   🔧 Updating SMD UVs for atlas...")
            all_uvs = np.array([[v['u'], v['v']] for v in vertices])
            # استخدام أول مادة للأطلس
            first_texture = list(material_names)[0] if material_names else "texture.png"
            new_uvs = atlas.get_uv_transform(first_texture, all_uvs)
            for i, v in enumerate(vertices):
                v['u'] = new_uvs[i, 0]
                v['v'] = new_uvs[i, 1]
            print(f"   ✅ Updated {len(vertices)} vertices UVs")
        
        # ========== كتابة ملف OBJ ==========
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write(f"mtllib {os.path.basename(mtl_path)}\n")
            f.write(f"o {os.path.basename(base_name)}\n")
            
            # كتابة الرؤوس
            for v in vertices:
                f.write(f"v {v['px']:.6f} {v['py']:.6f} {v['pz']:.6f}\n")
            
            # كتابة إحداثيات النسيج
            for v in vertices:
                f.write(f"vt {v['u']:.6f} {1.0 - v['v']:.6f}\n")
            
            # كتابة الطبيعيات
            for v in vertices:
                f.write(f"vn {v['nx']:.6f} {v['ny']:.6f} {v['nz']:.6f}\n")
            
            # كتابة الوجوه حسب المادة
            total_faces_written = 0
            for mat_name, material_faces in material_faces_map.items():
                if not material_faces:
                    continue
                
                # تنظيف اسم المادة
                clean_mat_name = mat_name.replace('\\', '/').split('/')[-1]
                clean_mat_name = clean_mat_name.split('.')[0] if '.' in clean_mat_name else clean_mat_name
                clean_mat_name = clean_mat_name.replace(' ', '_').replace('-', '_')
                if not clean_mat_name:
                    clean_mat_name = f"material_{material_names.index(mat_name)}"
                
                f.write(f"usemtl {clean_mat_name}\n")
                
                for face in material_faces:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
                    total_faces_written += 1
            
            # Fallback إذا لم يتم كتابة أي وجه
            if total_faces_written == 0:
                f.write(f"usemtl smd_material\n")
                for face in faces:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
        
        print(f"   OBJ: {obj_path} (with {len(material_names)} materials)")
        print(f"   MTL: {mtl_path} (with {len(material_names)} materials)")
        
        # طباعة ملخص المواد للتحقق
        print(f"\n   📋 Materials summary:")
        for mat_name in material_names:
            face_count = len(material_faces_map.get(mat_name, []))
            print(f"      - {mat_name}: {face_count} faces")

def collect_textures_from_materials(materials: List[Dict], base_name: str) -> List[str]:
    """
    جمع أسماء ملفات القوام من قائمة المواد
    
    Args:
        materials: قائمة المواد (كل مادة تحتوي على texture_name أو texture_index)
        base_name: الاسم الأساسي للنموذج
    
    Returns:
        قائمة بأسماء ملفات القوام الفريدة
    """
    texture_names = set()
    
    for i, mat in enumerate(materials):
        # محاولة استخراج اسم القوام بطرق مختلفة
        tex_name = None
        
        if isinstance(mat, dict):
            tex_name = mat.get('texture_name')
            if not tex_name and 'diffuse_texture' in mat:
                tex_name = mat.get('diffuse_texture')
            if not tex_name and 'texture_index' in mat:
                tex_idx = mat.get('texture_index', 0)
                tex_name = get_texture_name(tex_idx, base_name, i, None)
        
        if tex_name:
            # تنظيف اسم الملف
            tex_name = os.path.basename(tex_name)
            # إزالة المسار إذا وجد
            tex_name = tex_name.replace('\\', '/').split('/')[-1]
            texture_names.add(tex_name)
    
    # إذا لم يتم العثور على أي قوام، نضيف افتراضياً
    if not texture_names:
        texture_names.add(f"{base_name}.tga")
    
    return list(texture_names)

def create_atlas_for_model(model_obj, texture_dir: str, base_name: str, 
                           texture_names: List[str] = None) -> Optional[TextureAtlas]:
    """
    إنشاء أطلس قوام لنموذج معين
    
    Args:
        model_obj: كائن النموذج (SMDExporter, OBJExporter, StudioHeader, أو MdlModel)
        texture_dir: المجلد الذي يحتوي على ملفات القوام
        base_name: الاسم الأساسي للنموذج
        texture_names: قائمة بأسماء القوام (إذا كانت None، سيتم جمعها تلقائياً)
    
    Returns:
        كائن TextureAtlas أو None إذا فشل الإنشاء
    """
    if not PIL_AVAILABLE:
        print("   ⚠️ PIL not available, cannot create texture atlas")
        return None
    
    # جمع أسماء القوام
    if texture_names is None:
        if hasattr(model_obj, 'get_texture_names'):
            texture_names = model_obj.get_texture_names()
        elif hasattr(model_obj, 'materials'):
            texture_names = collect_textures_from_materials(model_obj.materials, base_name)
        else:
            # محاولة استخراج من خصائص مختلفة
            texture_names = []
            if hasattr(model_obj, 'textures'):
                for tex in model_obj.textures:
                    if hasattr(tex, 'name'):
                        texture_names.append(tex.name)
    
    if not texture_names:
        print("   ⚠️ No textures found for atlas creation")
        return None
    
    # إذا كان هناك قوام واحد فقط، لا حاجة للأطلس
    if len(texture_names) == 1:
        print(f"   ℹ️ Single texture only, skipping atlas creation")
        return None
    
    # البحث عن مجلد القوام
    texture_dirs = [
        texture_dir,
        os.path.join(texture_dir, "textures"),
        os.path.join(os.path.dirname(texture_dir), "textures"),
        os.getcwd(),
        os.path.join(os.getcwd(), "textures")
    ]
    
    atlas = None
    for tex_dir in texture_dirs:
        if os.path.exists(tex_dir):
            atlas = TextureAtlas(tex_dir)
            break
    
    if atlas is None:
        atlas = TextureAtlas(texture_dir)
    
    # إضافة القوام إلى الأطلس
    for tex_name in texture_names:
        atlas.add_texture(tex_name)
    
    # دمج القوام
    if atlas.has_multiple_textures():
        if atlas.pack_textures():
            atlas_path = os.path.join(texture_dir, f"{base_name}_atlas.png")
            atlas.save_atlas(atlas_path, 'PNG')
            print(f"   ✅ Created texture atlas: {atlas_path} ({atlas.atlas_size[0]}x{atlas.atlas_size[1]})")
            print(f"      Textures merged: {len(atlas.texture_paths)} → 1")
            return atlas
    
    return None

def update_uvs_with_atlas(uvs: np.ndarray, atlas: TextureAtlas, texture_name: str) -> np.ndarray:
    """
    تحديث إحداثيات UV لاستخدام الأطلس
    
    Args:
        uvs: مصفوفة الإحداثيات الأصلية (N, 2)
        atlas: كائن TextureAtlas
        texture_name: اسم القوام الأصلي
    
    Returns:
        مصفوفة الإحداثيات الجديدة
    """
    if atlas is None or not atlas.has_multiple_textures():
        return uvs
    
    if texture_name not in atlas.texture_indices:
        return uvs
    
    return atlas.get_uv_transform(texture_name, uvs)

def update_mtl_to_use_atlas(mtl_path: str, atlas_name: str):
    """
    تحديث ملف MTL لاستخدام الأطلس بدلاً من القوام الفردية
    """
    if not os.path.exists(mtl_path):
        return
    
    with open(mtl_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # استبدال جميع map_Kd و map_Ke بالإشارة إلى الأطلس
    lines = content.split('\n')
    new_lines = []
    
    for line in lines:
        if line.startswith('map_Kd ') or line.startswith('map_Ke '):
            new_lines.append(f"map_Kd {atlas_name}")
        else:
            new_lines.append(line)
    
    with open(mtl_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(new_lines))
    
    print(f"   Updated MTL to use atlas: {mtl_path}")

def enable_texture_atlas_for_all(enable: bool = True):
    """تفعيل أو إيقاف ميزة دمج القوام لجميع الصيغ"""
    global ENABLE_TEXTURE_ATLAS_SMD, ENABLE_TEXTURE_ATLAS_OBJ, ENABLE_TEXTURE_ATLAS_MDL
    ENABLE_TEXTURE_ATLAS_SMD = enable
    ENABLE_TEXTURE_ATLAS_OBJ = enable
    ENABLE_TEXTURE_ATLAS_MDL = enable
    print(f"✅ Texture Atlas for all formats: {'ENABLED' if enable else 'DISABLED'}")

def add_atlas_support_to_smd():
    """إضافة دوال دعم الأطلس إلى SMDExporter"""
    
    # حفظ المراجع الأصلية
    original_export_obj = SMDExporter.export_obj
    original_export_gltf = SMDExporter.export_gltf
    original_export_all = SMDExporter.export_all
    
    def get_texture_names_from_smd(self) -> List[str]:
        """استخراج أسماء القوام من SMD"""
        # SMD لا يحتوي على معلومات مباشرة عن القوام، نستخدم اسم افتراضي
        return ["texture.png"]
    
    def export_obj_with_atlas(self, output_path: str):
        """تصدير SMD إلى OBJ مع دعم المواد المتعددة - نسخة محسنة"""
        vertices, faces = self.to_vertices_array()
        
        if len(vertices) == 0:
            print("No vertices to export")
            return
        
        base_name = os.path.splitext(output_path)[0]
        obj_path = f"{base_name}.obj"
        mtl_path = f"{base_name}.mtl"
        
        # ========== استخدام المواد المستخرجة من SMD ==========
        material_names = []
        face_to_material = {}
        
        if hasattr(self, 'materials') and self.materials:
            material_names = self.materials
            print(f"   Using {len(material_names)} materials from SMD: {material_names}")
            
            # بناء تعيين من مؤشر الوجه إلى اسم المادة
            if hasattr(self, 'material_triangle_indices') and self.material_triangle_indices:
                for mat_name, tri_indices in self.material_triangle_indices.items():
                    for tri_idx in tri_indices:
                        face_to_material[tri_idx] = mat_name
                print(f"   Mapped {len(face_to_material)} faces to materials")
        else:
            material_names = ["smd_material"]
            print(f"   No materials found in SMD, using default material")
        
        # ========== تجميع الوجوه حسب المادة ==========
        material_faces_map = {}
        for mat_name in material_names:
            material_faces_map[mat_name] = []
        
        if face_to_material:
            for face_idx, face in enumerate(faces):
                mat_name = face_to_material.get(face_idx, material_names[0])
                if mat_name not in material_faces_map:
                    material_faces_map[mat_name] = []
                material_faces_map[mat_name].append(face)
        else:
            material_faces_map[material_names[0]] = faces
        
        # ========== التحقق من تفعيل الأطلس ==========
        use_atlas = ENABLE_TEXTURE_ATLAS_SMD and PIL_AVAILABLE
        atlas = None
        
        if use_atlas and len(material_names) > 1:
            texture_dir = os.path.dirname(output_path)
            atlas = create_atlas_for_model(self, texture_dir, os.path.basename(base_name), material_names)
            use_atlas = atlas and atlas.has_multiple_textures()
        
        # ========== كتابة ملف MTL ==========
        with open(mtl_path, 'w', encoding='utf-8') as f:
            for mat_name in material_names:
                # تنظيف اسم المادة
                clean_mat_name = mat_name.replace('\\', '/').split('/')[-1]
                clean_mat_name = clean_mat_name.split('.')[0] if '.' in clean_mat_name else clean_mat_name
                clean_mat_name = clean_mat_name.replace(' ', '_').replace('-', '_')
                if not clean_mat_name:
                    clean_mat_name = f"material_{material_names.index(mat_name)}"
                
                # اسم ملف القوام
                if use_atlas and atlas:
                    tex_file = f"{os.path.basename(base_name)}_atlas.png"
                else:
                    tex_file = mat_name
                    if not tex_file.endswith('.tga') and not tex_file.endswith('.png') and not tex_file.endswith('.bmp'):
                        tex_file = f"{clean_mat_name}.png"
                
                f.write(f"newmtl {clean_mat_name}\n")
                f.write("Ns 10.0000\n")
                f.write("Ka 1.0000 1.0000 1.0000\n")
                f.write("Kd 1.0000 1.0000 1.0000\n")
                f.write("Ks 0.0000 0.0000 0.0000\n")
                f.write(f"map_Kd {tex_file}\n")
                f.write("\n")
        
        # ========== تحديث UVs إذا كان الأطلس مفعلاً ==========
        if use_atlas and atlas:
            print(f"\n   🔧 Updating SMD UVs for atlas...")
            all_uvs = np.array([[v['u'], v['v']] for v in vertices])
            # استخدام أول مادة للأطلس
            first_texture = list(material_names)[0] if material_names else "texture.png"
            new_uvs = atlas.get_uv_transform(first_texture, all_uvs)
            for i, v in enumerate(vertices):
                v['u'] = new_uvs[i, 0]
                v['v'] = new_uvs[i, 1]
            print(f"   ✅ Updated {len(vertices)} vertices UVs")
        
        # ========== كتابة ملف OBJ ==========
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write(f"mtllib {os.path.basename(mtl_path)}\n")
            f.write(f"o {os.path.basename(base_name)}\n")
            
            # كتابة الرؤوس
            for v in vertices:
                f.write(f"v {v['px']:.6f} {v['py']:.6f} {v['pz']:.6f}\n")
            
            # كتابة إحداثيات النسيج
            for v in vertices:
                f.write(f"vt {v['u']:.6f} {1.0 - v['v']:.6f}\n")
            
            # كتابة الطبيعيات
            for v in vertices:
                f.write(f"vn {v['nx']:.6f} {v['ny']:.6f} {v['nz']:.6f}\n")
            
            # كتابة الوجوه حسب المادة
            total_faces_written = 0
            for mat_name, material_faces in material_faces_map.items():
                if not material_faces:
                    continue
                
                # تنظيف اسم المادة
                clean_mat_name = mat_name.replace('\\', '/').split('/')[-1]
                clean_mat_name = clean_mat_name.split('.')[0] if '.' in clean_mat_name else clean_mat_name
                clean_mat_name = clean_mat_name.replace(' ', '_').replace('-', '_')
                if not clean_mat_name:
                    clean_mat_name = f"material_{material_names.index(mat_name)}"
                
                f.write(f"usemtl {clean_mat_name}\n")
                
                for face in material_faces:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
                    total_faces_written += 1
            
            # Fallback إذا لم يتم كتابة أي وجه
            if total_faces_written == 0:
                f.write(f"usemtl smd_material\n")
                for face in faces:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
        
        print(f"   OBJ: {obj_path} (with {len(material_names)} materials)")
        print(f"   MTL: {mtl_path} (with {len(material_names)} materials)")
        
        # طباعة ملخص المواد للتحقق
        print(f"\n   📋 Materials summary:")
        for mat_name in material_names:
            face_count = len(material_faces_map.get(mat_name, []))
            print(f"      - {mat_name}: {face_count} faces")
    
    def export_gltf_with_atlas(self, output_path: str):
        """تصدير SMD إلى glTF مع دعم الأطلس"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available, skipping glTF export")
            return
        
        vertices, faces = self.to_vertices_array()
        
        if len(vertices) == 0:
            print("No vertices to export")
            return
        
        base_name = os.path.splitext(output_path)[0]
        
        # التحقق من تفعيل الأطلس
        use_atlas = ENABLE_TEXTURE_ATLAS_SMD and PIL_AVAILABLE
        atlas = None
        
        if use_atlas:
            texture_dir = os.path.dirname(output_path)
            atlas = create_atlas_for_model(self, texture_dir, os.path.basename(base_name))
            use_atlas = atlas and atlas.has_multiple_textures()
            
            if use_atlas and atlas:
                # ========== 🔴 تحديث UVs مباشرة في مصفوفة vertices ==========
                print(f"\n   🔧 Updating SMD UVs for atlas (glTF)...")
                all_uvs = np.array([[v['u'], v['v']] for v in vertices])
                first_texture = list(atlas.texture_names)[0] if atlas.texture_names else "texture.png"
                new_uvs = atlas.get_uv_transform(first_texture, all_uvs)
                for i, v in enumerate(vertices):
                    v['u'] = new_uvs[i, 0]
                    v['v'] = new_uvs[i, 1]
                print(f"   ✅ Updated {len(vertices)} vertices UVs")
        
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="SMD Exporter (Crowbar)", version="2.0")
            
            positions = []
            normals = []
            uvs = []
            weights = []
            joints = []
            
            for v in vertices:
                positions.extend([v['px'], v['py'], v['pz']])
                normals.extend([v['nx'], v['ny'], v['nz']])
                uvs.extend([v['u'], 1.0 - v['v']])
                weights.extend([v['weight'], 0.0, 0.0, 0.0])
                joints.extend([v['bone_id'], 0, 0, 0])
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(vertices), type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # Normals
            norm_bytes = np.array(normals, dtype=np.float32).tobytes()
            norm_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(norm_bytes), target=34962)
            gltf.bufferViews.append(norm_bv)
            binary_data.extend(norm_bytes)
            
            norm_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                count=len(vertices), type="VEC3")
            gltf.accessors.append(norm_acc)
            
            # UVs
            uv_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                              count=len(vertices), type="VEC2")
            gltf.accessors.append(uv_acc)
            
            # Weights
            weights_bytes = np.array(weights, dtype=np.float32).tobytes()
            weights_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(weights_bytes), target=34962)
            gltf.bufferViews.append(weights_bv)
            binary_data.extend(weights_bytes)
            
            weights_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                   count=len(vertices), type="VEC4")
            gltf.accessors.append(weights_acc)
            
            # Joints
            joints_bytes = np.array(joints, dtype=np.uint16).tobytes()
            joints_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(joints_bytes), target=34962)
            gltf.bufferViews.append(joints_bv)
            binary_data.extend(joints_bytes)
            
            joints_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5123,
                                  count=len(vertices), type="VEC4")
            gltf.accessors.append(joints_acc)
            
            # Indices
            indices_list = []
            for face in faces:
                indices_list.extend([face[0], face[1], face[2]])
            
            indices_bytes = np.array(indices_list, dtype=np.uint32).tobytes()
            indices_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(indices_bytes), target=34963)
            gltf.bufferViews.append(indices_bv)
            binary_data.extend(indices_bytes)
            
            indices_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                                   count=len(indices_list), type="SCALAR")
            gltf.accessors.append(indices_acc)
            
            # Buffer
            base_filename = os.path.splitext(os.path.basename(output_path))[0]
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_filename}.bin"))
            
            attributes = Attributes(POSITION=0, NORMAL=1, TEXCOORD_0=2, WEIGHTS_0=3, JOINTS_0=4)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            # العظام
            if self.nodes:
                bone_nodes = []
                for node in self.nodes:
                    gltf_node = Node(name=node.name)
                    gltf.nodes.append(gltf_node)
                    bone_nodes.append(len(gltf.nodes)-1)
                
                for i, node in enumerate(self.nodes):
                    if node.parent_id >= 0:
                        parent_idx = None
                        for j, n in enumerate(self.nodes):
                            if n.id == node.parent_id:
                                parent_idx = bone_nodes[j]
                                break
                        if parent_idx is not None:
                            if gltf.nodes[parent_idx].children is None:
                                gltf.nodes[parent_idx].children = []
                            gltf.nodes[parent_idx].children.append(bone_nodes[i])
                
                skin = Skin(joints=bone_nodes)
                gltf.skins.append(skin)
                
                node = Node(mesh=0, skin=len(gltf.skins)-1)
                gltf.nodes.append(node)
                scene = Scene(nodes=[len(gltf.nodes)-1])
            else:
                node = Node(mesh=0)
                gltf.nodes.append(node)
                scene = Scene(nodes=[0])
            
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            gltf.save(f"{output_path}.gltf")
            with open(f"{os.path.splitext(output_path)[0]}.bin", 'wb') as f:
                f.write(binary_data)
            
            if use_atlas:
                print(f"   glTF: {output_path}.gltf (using texture atlas)")
            else:
                print(f"   glTF: {output_path}.gltf")
            print(f"   glTF binary: {os.path.splitext(output_path)[0]}.bin")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
            import traceback
            traceback.print_exc()
    
    def export_all_with_atlas(self, output_dir: str, base_name: str, export_formats: List[str] = None):
        """تصدير SMD إلى جميع الصيغ مع دعم الأطلس"""
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt"]
        
        self.ensure_dir(output_dir)
        
        print(f"\nExporting SMD to {output_dir}")
        print("-" * 50)
        
        if "obj" in export_formats:
            export_obj_with_atlas(self, os.path.join(output_dir, base_name))
        
        if "gltf" in export_formats:
            export_gltf_with_atlas(self, os.path.join(output_dir, base_name))
        
        if "json" in export_formats:
            self.export_json(os.path.join(output_dir, f"{base_name}.json"))
        
        if "txt" in export_formats:
            self.export_txt(os.path.join(output_dir, f"{base_name}_info.txt"))
        
        print("-" * 50)
        print("Export completed successfully!")
    
    # تطبيق الدوال الجديدة
    SMDExporter.export_obj = export_obj_with_atlas
    SMDExporter.export_gltf = export_gltf_with_atlas
    SMDExporter.export_all = export_all_with_atlas
    SMDExporter.get_texture_names = get_texture_names_from_smd

def add_atlas_support_to_obj():
    """إضافة دوال دعم الأطلس إلى OBJExporter"""
    
    # حفظ المراجع الأصلية
    original_export_obj = OBJExporter.export_obj
    original_export_gltf = OBJExporter.export_gltf
    original_export_all = OBJExporter.export_all
    
    def get_texture_names_from_obj(self) -> List[str]:
        texture_names = []
        # الحفاظ على الترتيب كما هو في المواد
        for mat in self.materials.values():
            if mat.diffuse_texture:
                tex_name = os.path.basename(mat.diffuse_texture)
                tex_name = tex_name.replace('\\', '/').split('/')[-1]
                if tex_name not in texture_names:
                    texture_names.append(tex_name)
        if not texture_names:
            texture_names.append("texture.png")
        return texture_names  # يحافظ على الترتيب الأصلي
    
    def debug_uv_transform(self, atlas: TextureAtlas, material_name: str, vt_indices: List[int], orig_texture: str):
        """دالة تشخيصية لطباعة UVs قبل وبعد التحويل"""
        print(f"\n   🔍 DEBUG: Material '{material_name}' (texture: {orig_texture})")
        for vt_idx in vt_indices[:5]:
            if 0 <= vt_idx < len(self._all_texture_vertices):
                vt = self._all_texture_vertices[vt_idx]
                print(f"     VT {vt_idx}: original=({vt.u:.4f}, {vt.v:.4f})")
                
                # تطبيق التحويل
                uvs_array = np.array([[vt.u, vt.v]])
                new_uvs = atlas.get_uv_transform(orig_texture, uvs_array)
                print(f"       after atlas=({new_uvs[0,0]:.4f}, {new_uvs[0,1]:.4f})")

    def export_obj_with_atlas(self, output_path: str):
        """تصدير OBJ مع دعم الأطلس - مع تحديث UVs بشكل صحيح"""
        base_name = os.path.splitext(output_path)[0]
        obj_path = f"{base_name}.obj"
        mtl_path = f"{base_name}.mtl"
        
        # التحقق من تفعيل الأطلس ووضعه
        use_atlas = ENABLE_TEXTURE_ATLAS_OBJ and PIL_AVAILABLE
        atlas_mode = ATLAS_MODE  # استخدام الوضع العام
        atlas = None
        updated_texture_vertices = None
        
        if use_atlas:
            texture_dir = os.path.dirname(output_path)
            texture_names = self.get_texture_names()
            atlas = create_atlas_for_model(self, texture_dir, os.path.basename(base_name), texture_names)
            use_atlas = atlas and atlas.has_multiple_textures()
            
            if use_atlas:
                # ========== 🔴 التصحيح: بناء قائمة vt محدثة ==========
                print(f"\n   🔧 Building updated UV coordinates for atlas... (mode: {atlas_mode})")
                updated_texture_vertices = []
                
                # إنشاء cache لتحويلات UV لكل VT ومادة
                vt_transform_cache = {}  # (vt_index, material_name) -> (new_u, new_v)
                
                # أولاً: تجميع كل الوجوه لمعرفة أي VT يستخدم مع أي مادة
                for obj in self.objects:
                    for face in obj.faces:
                        mat_name = face.material_name
                        for i in range(len(face.texture_indices)):
                            vt_idx = face.texture_indices[i] - 1 if i < len(face.texture_indices) else -1
                            if vt_idx >= 0:
                                key = (vt_idx, mat_name)
                                if key not in vt_transform_cache:
                                    # الحصول على القوام الأصلي للمادة
                                    orig_texture = "texture.png"
                                    if mat_name in self.materials and self.materials[mat_name].diffuse_texture:
                                        orig_texture = os.path.basename(self.materials[mat_name].diffuse_texture)
                                        orig_texture = orig_texture.replace('\\', '/').split('/')[-1]
                                    
                                    # الحصول على UV الأصلي
                                    if 0 <= vt_idx < len(self._all_texture_vertices):
                                        vt = self._all_texture_vertices[vt_idx]
                                        u_orig, v_orig = vt.u, vt.v
                                        
                                        # تطبيع UVs إلى النطاق [0, 1]
                                        import math
                                        u_orig = u_orig - math.floor(u_orig)
                                        v_orig = v_orig - math.floor(v_orig)
                                    else:
                                        u_orig, v_orig = 0, 0
                                    
                                    # تطبيق تحويل الأطلس
                                    if orig_texture in atlas.texture_indices:
                                        uvs_array = np.array([[u_orig, v_orig]])
                                        new_uvs = atlas.get_uv_transform(orig_texture, uvs_array)
                                        vt_transform_cache[key] = (new_uvs[0, 0], new_uvs[0, 1])
                                    else:
                                        vt_transform_cache[key] = (u_orig, v_orig)
                
                # بناء قائمة vt المحدثة (نحافظ على نفس الترتيب)
                for vt_idx, vt in enumerate(self._all_texture_vertices):
                    # نأخذ أول مادة تستخدم هذا vt (افتراضي)
                    new_u, new_v = vt.u, vt.v
                    
                    # البحث عن تحويل لهذا vt
                    for (cached_vt_idx, mat_name), (u_new, v_new) in vt_transform_cache.items():
                        if cached_vt_idx == vt_idx:
                            new_u, new_v = u_new, v_new
                            break
                    
                    # الحفاظ على w إذا كانت موجودة
                    if vt.w != 0.0:
                        updated_texture_vertices.append(OBJTextureVertex(new_u, new_v, vt.w))
                    else:
                        updated_texture_vertices.append(OBJTextureVertex(new_u, new_v))
                
                print(f"   ✅ Built {len(updated_texture_vertices)} updated UV coordinates")
        
         # كتابة ملف MTL حسب الوضع المختار
        with open(mtl_path, 'w', encoding='utf-8') as f:
            if use_atlas and atlas:
                atlas_name = f"{os.path.basename(base_name)}_atlas.png"
                
                if atlas_mode == "merge":
                    # ========== وضع الدمج: مادة واحدة ==========
                    f.write(f"newmtl atlas_material\n")
                    f.write("Ns 10.0000\n")
                    f.write("Ka 1.0000 1.0000 1.0000\n")
                    f.write("Kd 1.0000 1.0000 1.0000\n")
                    f.write("Ks 0.0000 0.0000 0.0000\n")
                    f.write(f"map_Kd {atlas_name}\n")
                    print(f"   ✅ MTL mode: MERGE (single 'atlas_material')")
                    
                else:  # atlas_mode == "preserve"
                    # ========== وضع الحفاظ على المواد ==========
                    for name, mat in self.materials.items():
                        f.write(f"newmtl {mat.name}\n")
                        f.write(f"Ns {mat.shininess:.6f}\n")
                        f.write(f"Ka {mat.ambient[0]:.6f} {mat.ambient[1]:.6f} {mat.ambient[2]:.6f}\n")
                        f.write(f"Kd {mat.diffuse[0]:.6f} {mat.diffuse[1]:.6f} {mat.diffuse[2]:.6f}\n")
                        f.write(f"Ks {mat.specular[0]:.6f} {mat.specular[1]:.6f} {mat.specular[2]:.6f}\n")
                        f.write(f"map_Kd {atlas_name}\n")  # فقط تغيير مسار الصورة
                        f.write("\n")
                    print(f"   ✅ MTL mode: PRESERVE (keeping {len(self.materials)} materials, using atlas)")
            else:
                # مواد متعددة بدون أطلس
                for name, mat in self.materials.items():
                    f.write(f"newmtl {mat.name}\n")
                    f.write(f"Ns {mat.shininess:.6f}\n")
                    f.write(f"Ka {mat.ambient[0]:.6f} {mat.ambient[1]:.6f} {mat.ambient[2]:.6f}\n")
                    f.write(f"Kd {mat.diffuse[0]:.6f} {mat.diffuse[1]:.6f} {mat.diffuse[2]:.6f}\n")
                    f.write(f"Ks {mat.specular[0]:.6f} {mat.specular[1]:.6f} {mat.specular[2]:.6f}\n")
                    if mat.diffuse_texture:
                        f.write(f"map_Kd {mat.diffuse_texture}\n")
                    f.write("\n")
        
        # كتابة ملف OBJ
        with open(obj_path, 'w', encoding='utf-8') as f:
            if self.material_libs:
                for lib in self.material_libs:
                    f.write(f"mtllib {lib}\n")
            elif self.materials:
                f.write(f"mtllib {os.path.basename(mtl_path)}\n")
            
            # كتابة الرؤوس (بدون تغيير)
            for v in self._all_vertices:
                f.write(f"v {v.x:.6f} {v.y:.6f} {v.z:.6f}\n")
            
            # ========== 🔴 كتابة إحداثيات النسيج المحدثة ==========
            if use_atlas and atlas and updated_texture_vertices:
                for vt in updated_texture_vertices:
                    if vt.w != 0.0:
                        f.write(f"vt {vt.u:.6f} {vt.v:.6f} {vt.w:.6f}\n")
                    else:
                        f.write(f"vt {vt.u:.6f} {vt.v:.6f}\n")
            else:
                # الوضع العادي
                for vt in self._all_texture_vertices:
                    if vt.w != 0.0:
                        f.write(f"vt {vt.u:.6f} {vt.v:.6f} {vt.w:.6f}\n")
                    else:
                        f.write(f"vt {vt.u:.6f} {vt.v:.6f}\n")
            
            # كتابة الطبيعيات (بدون تغيير)
            for vn in self._all_normals:
                f.write(f"vn {vn.x:.6f} {vn.y:.6f} {vn.z:.6f}\n")
            
            # كتابة الكائنات والوجوه
            if use_atlas and atlas and atlas_mode == "merge":
                # ========== وضع الدمج: usemtl واحد فقط ==========
                f.write(f"usemtl atlas_material\n")
                for obj in self.objects:
                    if obj.name:
                        f.write(f"o {obj.name}\n")
                    for face in obj.faces:
                        f.write("f")
                        for i in range(len(face.vertex_indices)):
                            v_idx = face.vertex_indices[i]
                            vt_idx = face.texture_indices[i] if i < len(face.texture_indices) else 0
                            vn_idx = face.normal_indices[i] if i < len(face.normal_indices) else 0
                            
                            if vt_idx > 0 and vn_idx > 0:
                                f.write(f" {v_idx}/{vt_idx}/{vn_idx}")
                            elif vt_idx > 0:
                                f.write(f" {v_idx}/{vt_idx}")
                            elif vn_idx > 0:
                                f.write(f" {v_idx}//{vn_idx}")
                            else:
                                f.write(f" {v_idx}")
                        f.write("\n")
            else:
                # ========== الوضع العادي أو وضع الحفاظ ==========
                for obj in self.objects:
                    if obj.name:
                        f.write(f"o {obj.name}\n")
                    
                    current_mat = None
                    for face in obj.faces:
                        if use_atlas and atlas:
                            # في وضع الحفاظ، نستخدم اسم المادة الأصلي
                            mat_name = face.material_name
                        else:
                            mat_name = face.material_name
                        
                        if mat_name != current_mat:
                            current_mat = mat_name
                            f.write(f"usemtl {current_mat}\n")
                        
                        f.write("f")
                        for i in range(len(face.vertex_indices)):
                            v_idx = face.vertex_indices[i]
                            vt_idx = face.texture_indices[i] if i < len(face.texture_indices) else 0
                            vn_idx = face.normal_indices[i] if i < len(face.normal_indices) else 0
                            
                            if vt_idx > 0 and vn_idx > 0:
                                f.write(f" {v_idx}/{vt_idx}/{vn_idx}")
                            elif vt_idx > 0:
                                f.write(f" {v_idx}/{vt_idx}")
                            elif vn_idx > 0:
                                f.write(f" {v_idx}//{vn_idx}")
                            else:
                                f.write(f" {v_idx}")
                        f.write("\n")
        
        if use_atlas:
            print(f"   OBJ (with atlas, UVs updated): {obj_path}")
        else:
            print(f"   OBJ: {obj_path}")
        print(f"   MTL: {mtl_path}")
    
    def export_gltf_with_atlas(self, output_path: str):
        """تصدير OBJ إلى glTF مع دعم الأطلس - نسخة محسنة مع تتبع VT"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available, skipping glTF export")
            return
        
        base_name = os.path.splitext(output_path)[0]
        
        # التحقق من تفعيل الأطلس
        use_atlas = ENABLE_TEXTURE_ATLAS_OBJ and PIL_AVAILABLE
        atlas = None
        
        # جمع أسماء القوام (بحاجة للتشخيص)
        texture_names = self.get_texture_names()
        print(f"   Found textures: {texture_names}")
        
        if use_atlas and len(texture_names) > 1:
            texture_dir = os.path.dirname(output_path)
            atlas = create_atlas_for_model(self, texture_dir, os.path.basename(base_name), texture_names)
            use_atlas = atlas and atlas.has_multiple_textures()
            
            if use_atlas and atlas:
                print(f"\n   📊 ATLAS DIAGNOSTIC:")
                print(f"   Atlas size: {atlas.atlas_size[0]}x{atlas.atlas_size[1]}")
                print(f"   Atlas positions: {atlas.positions}")
                print(f"   Texture indices: {atlas.texture_indices}")
                print(f"\n   📍 Texture regions in atlas:")
                for tex_name, idx in atlas.texture_indices.items():
                    x, y, w, h = atlas.positions[idx]
                    u_min = x / atlas.atlas_size[0]
                    u_max = (x + w) / atlas.atlas_size[0]
                    v_min = y / atlas.atlas_size[1]
                    v_max = (y + h) / atlas.atlas_size[1]
                    print(f"     {tex_name}: pos=({x},{y}), size=({w},{h})")
                    print(f"       -> UV range: u=[{u_min:.3f}-{u_max:.3f}], v=[{v_min:.3f}-{v_max:.3f}]")
        
        # ========== بناء cache لتحويلات VT ==========
        vt_transform_cache = {}  # (vt_idx, material_name) -> (new_u, new_v)
        material_vt_map = {}     # material_name -> list of vt_idx (للتشخيص)
        
        for obj in self.objects:
            for face in obj.faces:
                mat_name = face.material_name
                
                # اسم القوام الأصلي للمادة
                orig_texture = "texture.png"
                if mat_name in self.materials and self.materials[mat_name].diffuse_texture:
                    orig_texture = os.path.basename(self.materials[mat_name].diffuse_texture)
                    orig_texture = orig_texture.replace('\\', '/').split('/')[-1]
                
                for i in range(len(face.texture_indices)):
                    vt_idx = face.texture_indices[i] - 1 if i < len(face.texture_indices) else -1
                    if vt_idx >= 0:
                        # تجميع VT لكل مادة للتشخيص
                        if mat_name not in material_vt_map:
                            material_vt_map[mat_name] = []
                        if vt_idx not in material_vt_map[mat_name]:
                            material_vt_map[mat_name].append(vt_idx)
                        
                        key = (vt_idx, mat_name)
                        if key not in vt_transform_cache:
                            # الحصول على UV الأصلي
                            if 0 <= vt_idx < len(self._all_texture_vertices):
                                vt = self._all_texture_vertices[vt_idx]
                                u_orig, v_orig = vt.u, vt.v
                                
                                # ========== تصحيح: تطبيع UVs إلى النطاق [0, 1] ==========
                                import math
                                u_orig = u_orig - math.floor(u_orig)
                                v_orig = v_orig - math.floor(v_orig)
                            else:
                                u_orig, v_orig = 0, 0
                            
                            # تطبيق تحويل الأطلس
                            if use_atlas and atlas and orig_texture in atlas.texture_indices:
                                uvs_array = np.array([[u_orig, v_orig]])
                                new_uvs = atlas.get_uv_transform(orig_texture, uvs_array)
                                vt_transform_cache[key] = (new_uvs[0, 0], new_uvs[0, 1])
                            else:
                                vt_transform_cache[key] = (u_orig, v_orig)
        
        # تشخيص: طباعة تحويلات UVs (اختياري، يمكن تعطيله)
        if use_atlas and atlas and False:  # set to True for debugging
            print(f"\n   🔬 UV TRANSFORM DIAGNOSTIC:")
            for mat_name, vt_list in material_vt_map.items():
                orig_texture = "texture.png"
                if mat_name in self.materials and self.materials[mat_name].diffuse_texture:
                    orig_texture = os.path.basename(self.materials[mat_name].diffuse_texture)
                    orig_texture = orig_texture.replace('\\', '/').split('/')[-1]
                
                print(f"\n     Material '{mat_name}' (texture: {orig_texture})")
                for vt_idx in vt_list[:5]:
                    if 0 <= vt_idx < len(self._all_texture_vertices):
                        vt = self._all_texture_vertices[vt_idx]
                        key = (vt_idx, mat_name)
                        if key in vt_transform_cache:
                            new_u, new_v = vt_transform_cache[key]
                            orig_u, orig_v = vt.u, vt.v
                            import math
                            norm_u = orig_u - math.floor(orig_u)
                            norm_v = orig_v - math.floor(orig_v)
                            print(f"       VT {vt_idx}: original=({orig_u:.4f}, {orig_v:.4f}) -> normalized=({norm_u:.4f}, {norm_v:.4f}) -> atlas=({new_u:.4f}, {new_v:.4f})")
        
        print(f"   Cached transforms for {len(vt_transform_cache)} unique (vt, material) pairs")
        
        # ========== بناء بيانات glTF باستخدام cache ==========
        positions = []
        normals = []
        uvs = []
        indices = []
        
        vertex_map = {}  # (v_idx, vt_idx, vn_idx, mat_name) -> vertex_index
        vertex_counter = 0
        
        for obj in self.objects:
            for face in obj.faces:
                mat_name = face.material_name
                
                face_indices = []
                for i in range(len(face.vertex_indices)):
                    v_idx = face.vertex_indices[i] - 1
                    vt_idx = face.texture_indices[i] - 1 if i < len(face.texture_indices) else -1
                    vn_idx = face.normal_indices[i] - 1 if i < len(face.normal_indices) else -1
                    
                    key = (v_idx, vt_idx, vn_idx, mat_name)
                    
                    if key not in vertex_map:
                        vertex_map[key] = vertex_counter
                        
                        # الرأس
                        if 0 <= v_idx < len(self._all_vertices):
                            v = self._all_vertices[v_idx]
                            positions.extend([v.x, v.y, v.z])
                        else:
                            positions.extend([0, 0, 0])
                        
                        # الطبيعية
                        if 0 <= vn_idx < len(self._all_normals):
                            n = self._all_normals[vn_idx]
                            normals.extend([n.x, n.y, n.z])
                        else:
                            normals.extend([0, 0, 0])
                        
                        # UV (من cache)
                        cache_key = (vt_idx, mat_name)
                        if cache_key in vt_transform_cache:
                            u_final, v_final = vt_transform_cache[cache_key]
                        else:
                            u_final, v_final = 0, 0
                        
                        # التأكد من أن القيم في النطاق [0, 1]
                        u_final = max(0.0, min(1.0, u_final))
                        v_final = max(0.0, min(1.0, v_final))
                        
                        uvs.extend([u_final, 1.0 - v_final])  # Flip V for OpenGL
                        
                        vertex_counter += 1
                    
                    face_indices.append(vertex_map[key])
                
                # إضافة الوجه (تثليث المضلعات)
                if len(face_indices) == 3:
                    indices.extend(face_indices)
                elif len(face_indices) == 4:
                    indices.extend([face_indices[0], face_indices[1], face_indices[2]])
                    indices.extend([face_indices[0], face_indices[2], face_indices[3]])
                elif len(face_indices) > 3:
                    for j in range(1, len(face_indices) - 1):
                        indices.extend([face_indices[0], face_indices[j], face_indices[j+1]])
        
        if len(positions) == 0:
            print("No vertices to export")
            return
        
        print(f"   Built: {len(positions)//3} vertices, {len(indices)//3} triangles")
        
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="OBJ Exporter (VT-accurate atlas)", version="2.0")
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(positions)//3, type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # Normals
            norm_bytes = np.array(normals, dtype=np.float32).tobytes()
            norm_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(norm_bytes), target=34962)
            gltf.bufferViews.append(norm_bv)
            binary_data.extend(norm_bytes)
            
            norm_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                count=len(normals)//3, type="VEC3")
            gltf.accessors.append(norm_acc)
            
            # UVs
            uv_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                              count=len(uvs)//2, type="VEC2")
            gltf.accessors.append(uv_acc)
            
            # Indices
            idx_bytes = np.array(indices, dtype=np.uint32).tobytes()
            idx_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(idx_bytes), target=34963)
            gltf.bufferViews.append(idx_bv)
            binary_data.extend(idx_bytes)
            
            idx_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                               count=len(indices), type="SCALAR")
            gltf.accessors.append(idx_acc)
            
            base_filename = os.path.splitext(os.path.basename(output_path))[0]
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_filename}.bin"))
            
            attributes = Attributes(POSITION=0, NORMAL=1, TEXCOORD_0=2)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            node = Node(mesh=0)
            gltf.nodes.append(node)
            scene = Scene(nodes=[0])
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            gltf.save(f"{output_path}.gltf")
            with open(f"{os.path.splitext(output_path)[0]}.bin", 'wb') as f:
                f.write(binary_data)
            
            if use_atlas:
                print(f"   glTF: {output_path}.gltf (using texture atlas with VT-accurate mapping)")
            else:
                print(f"   glTF: {output_path}.gltf")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
            import traceback
            traceback.print_exc()
        
    def export_all_with_atlas(self, output_dir: str, base_name: str, export_formats: List[str] = None):
        """تصدير OBJ إلى جميع الصيغ مع دعم الأطلس"""
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt", "smd", "mdl"]
        
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        print(f"\nExporting OBJ to {output_dir}")
        print("-" * 50)
        
        if "obj" in export_formats:
            export_obj_with_atlas(self, os.path.join(output_dir, base_name))
        
        if "gltf" in export_formats:
            export_gltf_with_atlas(self, os.path.join(output_dir, base_name))
        
        if "json" in export_formats:
            self.export_json(os.path.join(output_dir, f"{base_name}.json"))
        
        if "txt" in export_formats:
            self.export_txt(os.path.join(output_dir, f"{base_name}_info.txt"))
        
        if "smd" in export_formats:
            vertices, faces = self.to_unified_vertices(apply_swizzle=True)
            if len(vertices) > 0:
                smd = self.to_smd()
                smd.export_all(output_dir, base_name, ["obj", "gltf", "json", "txt"])
        
        if "mdl" in export_formats:
            mdl = self.to_mdl_format(base_name)
            mdl.export_all(os.path.join(output_dir, f"{base_name}_mdl"), ["obj", "gltf", "json", "txt"])
        
        print("-" * 50)
        print("OBJ Export completed successfully!")
    
    # تطبيق الدوال الجديدة
    OBJExporter.export_obj = export_obj_with_atlas
    OBJExporter.export_gltf = export_gltf_with_atlas
    OBJExporter.export_all = export_all_with_atlas
    OBJExporter.get_texture_names = get_texture_names_from_obj

def add_atlas_support_to_mdl():
    """إضافة دوال دعم الأطلس إلى StudioHeader (MDL)"""
    
    # حفظ المراجع الأصلية
    original_export_obj = StudioHeader.export_obj
    original_export_gltf = StudioHeader.export_gltf
    original_export_all = StudioHeader.export_all
    
    def get_texture_names_from_mdl(self) -> List[str]:
        """استخراج أسماء القوام من MDL"""
        texture_names = []
        if hasattr(self.header, 'numtextures') and self.header.numtextures > 0:
            # إضافة أسماء افتراضية للقوام
            for i in range(min(self.header.numtextures, 10)):
                texture_names.append(f"texture_{i}.bmp")
        if not texture_names:
            texture_names.append("texture.bmp")
        return texture_names
    
    def export_obj_with_atlas(self, out_dir, base_name):
        """تصدير MDL إلى OBJ مع دعم الأطلس - مع تحديث UVs بشكل صحيح"""
        self.debug_print_geometry()
        if len(self.vertices) == 0 or len(self.triangles) == 0:
            print("No geometry to export")
            return
        
        obj_path = os.path.join(out_dir, f"{base_name}.obj")
        mtl_path = os.path.join(out_dir, f"{base_name}.mtl")
        
        # التحقق من تفعيل الأطلس
        use_atlas = ENABLE_TEXTURE_ATLAS_MDL and PIL_AVAILABLE
        atlas = None
        
        if use_atlas:
            texture_dir = out_dir
            texture_names = self.get_texture_names()
            atlas = create_atlas_for_model(self, texture_dir, base_name, texture_names)
            use_atlas = atlas and atlas.has_multiple_textures()
        
        # تجميع الرؤوس والطبيعيات و UVs
        all_vertices = []
        all_normals = []
        all_uvs = []
        
        for tri in self.triangles:
            for i in range(3):
                vert_idx = tri.vertindex[i]
                norm_idx = tri.normindex[i]
                
                if vert_idx >= 0 and vert_idx < len(self.vertices):
                    v = self.vertices[vert_idx]
                    all_vertices.append((v.x, v.z, v.y))
                    
                    if norm_idx >= 0 and norm_idx < len(self.normals):
                        n = self.normals[norm_idx]
                        all_normals.append((n.x, n.z, n.y))
                    else:
                        all_normals.append((0, 0, 0))
                    
                    u = tri.s / 32768.0 if tri.s != 0 else 0.0
                    vt = tri.t / 32768.0 if tri.t != 0 else 0.0
                    all_uvs.append((u, 1.0 - vt))
        
        if len(all_vertices) == 0:
            print("   No valid vertices to export")
            return
        
        # ========== 🔴 تحديث UVs إذا كان الأطلس مفعلاً ==========
        if use_atlas and atlas:
            print(f"\n   🔧 Updating MDL UVs for atlas...")
            uvs_array = np.array(all_uvs)
            first_texture = list(atlas.texture_names)[0] if atlas.texture_names else "texture.bmp"
            new_uvs = atlas.get_uv_transform(first_texture, uvs_array)
            all_uvs = [(new_uvs[i, 0], new_uvs[i, 1]) for i in range(len(new_uvs))]
            print(f"   ✅ Updated {len(all_uvs)} UV coordinates")
        
        # كتابة ملف MTL
        with open(mtl_path, 'w', encoding='utf-8') as f:
            if use_atlas and atlas:
                atlas_name = f"{base_name}_atlas.png"
                f.write(f"newmtl {base_name}_material\n")
                f.write("Ns 10.0000\n")
                f.write("Ka 1.0000 1.0000 1.0000\n")
                f.write("Kd 1.0000 1.0000 1.0000\n")
                f.write("Ks 0.0000 0.0000 0.0000\n")
                f.write(f"map_Kd {atlas_name}\n")
            else:
                f.write(f"newmtl {base_name}_material\n")
                f.write("Ns 10.0000\n")
                f.write("Ka 1.0000 1.0000 1.0000\n")
                f.write("Kd 1.0000 1.0000 1.0000\n")
                f.write("Ks 0.0000 0.0000 0.0000\n")
                if self.header.numtextures > 0:
                    f.write("map_Kd texture.bmp\n")
        
        # كتابة ملف OBJ مع UVs المحدّثة
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write(f"mtllib {base_name}.mtl\n")
            f.write(f"o {base_name}\n")
            
            for v in all_vertices:
                f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
            
            for uv in all_uvs:
                f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
            
            for n in all_normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
            
            f.write(f"usemtl {base_name}_material\n")
            
            for i in range(0, len(all_vertices), 3):
                a, b, c = i + 1, i + 2, i + 3
                f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
        
        if use_atlas:
            print(f"   OBJ (with atlas, UVs updated): {obj_path}")
        else:
            print(f"   OBJ: {obj_path}")
        print(f"   MTL: {mtl_path}")
    
    def export_gltf_with_atlas(self, out_dir, base_name):
        """تصدير MDL إلى glTF مع دعم الأطلس"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available, skipping glTF export")
            return
        
        if len(self.vertices) == 0 or len(self.triangles) == 0:
            print("No geometry to export")
            return
        
        # التحقق من تفعيل الأطلس
        use_atlas = ENABLE_TEXTURE_ATLAS_MDL and PIL_AVAILABLE
        atlas = None
        
        if use_atlas:
            texture_dir = out_dir
            texture_names = self.get_texture_names()
            atlas = create_atlas_for_model(self, texture_dir, base_name, texture_names)
            use_atlas = atlas and atlas.has_multiple_textures()
        
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="HL MDL Reader (Valve spec)", version="2.0")
            
            positions = []
            indices = []
            
            # تجميع UVs
            all_uvs = []
            for tri in self.triangles:
                a, b, c = tri.vertindex[0], tri.vertindex[1], tri.vertindex[2]
                if a >= 0 and b >= 0 and c >= 0:
                    indices.extend([a, b, c])
                    u = tri.s / 32768.0 if tri.s != 0 else 0.0
                    vt = tri.t / 32768.0 if tri.t != 0 else 0.0
                    all_uvs.append((u, 1.0 - vt))
                    all_uvs.append((u, 1.0 - vt))
                    all_uvs.append((u, 1.0 - vt))
            
            for v in self.vertices:
                positions.extend([v.x, v.z, v.y])
            
            if len(indices) == 0:
                print("   No valid triangles to export")
                return
            
            # ========== 🔴 تحديث UVs إذا كان الأطلس مفعلاً ==========
            if use_atlas and atlas:
                print(f"\n   🔧 Updating MDL UVs for atlas (glTF)...")
                uvs_array = np.array(all_uvs)
                first_texture = list(atlas.texture_names)[0] if atlas.texture_names else "texture.bmp"
                new_uvs = atlas.get_uv_transform(first_texture, uvs_array)
                all_uvs = [(new_uvs[i, 0], new_uvs[i, 1]) for i in range(len(new_uvs))]
                print(f"   ✅ Updated {len(all_uvs)} UV coordinates")
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(self.vertices), type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # UVs
            uv_flat = []
            for uv in all_uvs:
                uv_flat.extend([uv[0], uv[1]])
            uv_bytes = np.array(uv_flat, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(all_uvs), type="VEC2")
            gltf.accessors.append(uv_acc)
            
            # Indices
            idx_bytes = np.array(indices, dtype=np.uint32).tobytes()
            idx_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(idx_bytes), target=34963)
            gltf.bufferViews.append(idx_bv)
            binary_data.extend(idx_bytes)
            
            idx_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                               count=len(indices), type="SCALAR")
            gltf.accessors.append(idx_acc)
            
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_name}.bin"))
            
            attributes = Attributes(POSITION=0, TEXCOORD_0=1)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            # العظام
            if len(self.bones) > 0:
                bone_nodes = []
                for i, bone in enumerate(self.bones):
                    bx, by, bz = bone.value[0], bone.value[1], bone.value[2]
                    node = Node(name=bone.name, translation=[bx, bz, by])
                    gltf.nodes.append(node)
                    bone_nodes.append(len(gltf.nodes)-1)
                
                for i, bone in enumerate(self.bones):
                    if bone.parent >= 0 and bone.parent < len(bone_nodes):
                        if gltf.nodes[bone_nodes[bone.parent]].children is None:
                            gltf.nodes[bone_nodes[bone.parent]].children = []
                        gltf.nodes[bone_nodes[bone.parent]].children.append(bone_nodes[i])
                
                skin = Skin(joints=bone_nodes)
                gltf.skins.append(skin)
                
                node = Node(mesh=0, skin=len(gltf.skins)-1)
                gltf.nodes.append(node)
                scene = Scene(nodes=[len(gltf.nodes)-1])
            else:
                node = Node(mesh=0)
                gltf.nodes.append(node)
                scene = Scene(nodes=[0])
            
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            gltf.save(f"{out_dir}/{base_name}.gltf")
            
            with open(f"{out_dir}/{base_name}.bin", 'wb') as f:
                f.write(binary_data)
            
            if use_atlas:
                print(f"   glTF: {out_dir}/{base_name}.gltf (using texture atlas)")
            else:
                print(f"   glTF: {out_dir}/{base_name}.gltf")
            print(f"   glTF binary: {out_dir}/{base_name}.bin")
            if len(self.bones) > 0:
                print(f"   Bones exported: {len(self.bones)}")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
    
    def export_all_with_atlas(self, out_dir, export_formats=None):
        """تصدير MDL إلى جميع الصيغ مع دعم الأطلس"""
        if export_formats is None:
            export_formats = ["obj"]
        
        base_name = os.path.basename(out_dir)
        self.ensure_dir(out_dir)
        
        print(f"\nExporting MDL to {out_dir}")
        print("-" * 50)
        
        self.debug_print_geometry()
        
        if "obj" in export_formats:
            self.export_obj_as_points(out_dir, base_name)
            export_obj_with_atlas(self, out_dir, base_name)
        
        if "gltf" in export_formats and GLTF_AVAILABLE:
            export_gltf_with_atlas(self, out_dir, base_name)
        
        if "json" in export_formats:
            self.export_json(out_dir, base_name)
        
        if "txt" in export_formats:
            self.export_txt(out_dir, base_name)
        
        print("-" * 50)
        print("Export completed successfully!")
    
    # تطبيق الدوال الجديدة
    StudioHeader.export_obj = export_obj_with_atlas
    StudioHeader.export_gltf = export_gltf_with_atlas
    StudioHeader.export_all = export_all_with_atlas
    StudioHeader.get_texture_names = get_texture_names_from_mdl

def add_atlas_support_to_mdl_model():
    """إضافة دوال دعم الأطلس إلى MdlModel"""
    
    # حفظ المراجع الأصلية
    original_export_obj = MdlModel.export_obj
    
    def get_texture_names_from_mdl_model(self) -> List[str]:
        """استخراج أسماء القوام من MdlModel"""
        texture_names = []
        if hasattr(self, 'textures') and self.textures:
            for tex in self.textures:
                if hasattr(tex, 'name'):
                    texture_names.append(tex.name)
        if not texture_names:
            texture_names.append("texture.bmp")
        return texture_names
    
    def export_obj_with_atlas(self, out_dir, base_name, export_formats=None):
        """تصدير MdlModel إلى OBJ مع دعم الأطلس - مع تحديث UVs بشكل صحيح"""
        if export_formats is None:
            export_formats = ["obj"]
        
        if len(self.vertices) == 0 or len(self.triangles) == 0:
            print("No vertices or triangles to export")
            return
        
        # التحقق من تفعيل الأطلس
        use_atlas = ENABLE_TEXTURE_ATLAS_MDL and PIL_AVAILABLE
        atlas = None
        
        if use_atlas:
            texture_dir = out_dir
            texture_names = self.get_texture_names()
            atlas = create_atlas_for_model(self, texture_dir, base_name, texture_names)
            use_atlas = atlas and atlas.has_multiple_textures()
        
        dtype_out = np.dtype([
            ("px", np.float32), ("py", np.float32), ("pz", np.float32),
            ("nx", np.float32), ("ny", np.float32), ("nz", np.float32),
            ("u", np.float32), ("v", np.float32)
        ])
        
        verts_arr = []
        for v in self.vertices:
            verts_arr.append((
                v.x, v.z, v.y,
                0, 0, 0,
                v.u, 1.0 - v.v
            ))
        
        vertices_transformed = np.array(verts_arr, dtype=dtype_out)
        
        faces_arr = []
        for tri in self.triangles:
            faces_arr.append([tri.indices[0], tri.indices[1], tri.indices[2]])
        faces_array = np.array(faces_arr)
        
        # ========== 🔴 تحديث UVs إذا كان الأطلس مفعلاً ==========
        if use_atlas and atlas:
            print(f"\n   🔧 Updating MdlModel UVs for atlas...")
            uvs_array = np.array([[v['u'], v['v']] for v in vertices_transformed])
            first_texture = list(atlas.texture_names)[0] if atlas.texture_names else "texture.bmp"
            new_uvs = atlas.get_uv_transform(first_texture, uvs_array)
            for i in range(len(vertices_transformed)):
                vertices_transformed[i]['u'] = new_uvs[i, 0]
                vertices_transformed[i]['v'] = new_uvs[i, 1]
            print(f"   ✅ Updated {len(vertices_transformed)} UV coordinates")
        
        if "obj" in export_formats:
            obj_path = os.path.join(out_dir, f"{base_name}.obj")
            mtl_path = os.path.join(out_dir, f"{base_name}.mtl")
            
            with open(mtl_path, "w", encoding="utf-8") as f:
                if use_atlas and atlas:
                    atlas_name = f"{base_name}_atlas.png"
                    f.write(f"newmtl {base_name}_material\n")
                    f.write("Ns 10.0000\n")
                    f.write("Ka 1.0000 1.0000 1.0000\n")
                    f.write("Kd 1.0000 1.0000 1.0000\n")
                    f.write("Ks 0.0000 0.0000 0.0000\n")
                    f.write(f"map_Kd {atlas_name}\n")
                else:
                    f.write(f"newmtl {base_name}_material\n")
                    f.write("Ns 10.0000\n")
                    f.write("Ka 1.0000 1.0000 1.0000\n")
                    f.write("Kd 1.0000 1.0000 1.0000\n")
                    f.write("Ks 0.0000 0.0000 0.0000\n")
                    if self.textures:
                        tex_name = self.textures[0].name
                        if not tex_name.endswith('.bmp') and not tex_name.endswith('.png'):
                            tex_name += ".bmp"
                        f.write(f"map_Kd {tex_name}\n")
            
            with open(obj_path, "w", encoding="utf-8") as f:
                f.write(f"mtllib {base_name}.mtl\n")
                f.write(f"o {base_name}\n")
                
                for v in vertices_transformed:
                    f.write(f"v {v['px']:.6f} {v['py']:.6f} {v['pz']:.6f}\n")
                
                for v in vertices_transformed:
                    f.write(f"vt {v['u']:.6f} {v['v']:.6f}\n")
                
                f.write(f"usemtl {base_name}_material\n")
                
                for face in faces_array:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a} {b}/{b} {c}/{c}\n")
            
            if use_atlas:
                print(f"   OBJ (with atlas, UVs updated): {obj_path}")
            else:
                print(f"   OBJ: {obj_path}")
            print(f"   MTL: {mtl_path}")
        
        if "gltf" in export_formats and GLTF_AVAILABLE:
            self._export_gltf(out_dir, base_name, vertices_transformed, faces_array)
        
        if "dae" in export_formats:
            self._export_collada(out_dir, base_name, vertices_transformed, faces_array)
        
        if "json" in export_formats:
            self._export_json(out_dir, base_name)
        
        if "txt" in export_formats:
            self._export_txt(out_dir, base_name)

def enable_atlas_for_all_formats():
    """تفعيل دعم Texture Atlas لجميع الصيغ المدعومة"""
    add_atlas_support_to_smd()
    add_atlas_support_to_obj()
    add_atlas_support_to_mdl()
    add_atlas_support_to_mdl_model()
    print("✅ Texture Atlas support enabled for SMD, OBJ, and MDL formats")

def add_directx_export_to_mef_model_igi1():
    """إضافة دالة export_to_directx إلى MefModelIGI1"""
    
    def export_to_directx(self, output_path: str):
        """تصدير النموذج إلى DirectX (.X)"""
        from mef_igi2_export import export_to_directx as dx_export
        return dx_export(self, output_path, "igi1", self.debug_params)
    
    MefModelIGI1.export_to_directx = export_to_directx

def add_directx_export_to_mef_model_igi2():
    """إضافة دالة export_to_directx إلى MefModelIGI2"""
    
    def export_to_directx(self, output_path: str):
        """تصدير النموذج إلى DirectX (.X)"""
        from mef_igi2_export import export_to_directx as dx_export
        return dx_export(self, output_path, "igi2", self.debug_params)
    
    MefModelIGI2.export_to_directx = export_to_directx
