"""
exporters/smd/export_extra.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math



# ========== Functions ==========
def convert_smd_to_formats(input_smd: str, output_dir: str, export_formats: List[str] = None):
    """
    دالة مساعدة عامة لتحويل ملف SMD واحد إلى صيغ متعددة.
    (ممرّ آمن للدالة المعرّفة داخل SMDExporter)
    """
    return SMDExporter.convert_smd_to_formats(input_smd, output_dir, export_formats)

def batch_convert_smd(input_dir: str, output_dir: str, export_formats: List[str] = None):
    """
    دالة مساعدة عامة لتحويل جميع ملفات SMD في مجلد.
    (ممرّ آمن للدالة المعرّفة داخل SMDExporter)
    """
    return SMDExporter.batch_convert_smd(input_dir, output_dir, export_formats)

def batch_convert_smd_fixed(input_dir: str, output_dir: str, export_formats: List[str] = None):
    """
    تحويل جميع ملفات SMD في مجلد إلى صيغ متعددة - نسخة مصلحة
    """
    if export_formats is None:
        export_formats = ["obj", "gltf", "json", "txt"]
    
    smd_files = []
    for ext in ['*.smd', '*.SMD']:
        smd_files.extend(Path(input_dir).glob(ext))
    
    if not smd_files:
        print(f"No SMD files found in '{input_dir}'")
        return False
    
    print(f"\nFound {len(smd_files)} SMD file(s):")
    for f in smd_files:
        print(f"  - {f.name}")
    
    successful = 0
    failed = 0
    
    for smd_file in smd_files:
        print(f"\n{'='*60}")
        print(f"Processing: {smd_file.name}")
        print(f"{'='*60}")
        
        output_subdir = os.path.join(output_dir, smd_file.stem)
        
        try:
            smd = SMDExporter.from_file(str(smd_file))
            base_name = smd_file.stem
            smd.export_all(output_subdir, base_name, export_formats)
            successful += 1
            print(f"✓ Successfully processed: {smd_file.name}")
        except Exception as e:
            failed += 1
            print(f"✗ Failed to process: {smd_file.name} - {e}")
    
    print("\n" + "="*60)
    print("SMD BATCH CONVERSION COMPLETE")
    print("="*60)
    print(f"Total files found : {len(smd_files)}")
    print(f"Successfully processed : {successful}")
    print(f"Failed : {failed}")
    print(f"Output folder : {output_dir}")
    print("="*60)
    
    return successful > 0

def convert_smd_to_formats_fixed(input_smd: str, output_dir: str, export_formats: List[str] = None):
    """
    دالة مساعدة لتحويل ملف SMD واحد إلى صيغ متعددة - نسخة مصلحة
    """
    if export_formats is None:
        export_formats = ["obj", "gltf", "json", "txt"]
    
    if not os.path.exists(input_smd):
        print(f"Error: SMD file not found: {input_smd}")
        return False
    
    try:
        print(f"\nReading SMD file: {input_smd}")
        smd = SMDExporter.from_file(input_smd)
        base_name = os.path.splitext(os.path.basename(input_smd))[0]
        smd.export_all(output_dir, base_name, export_formats)
        return True
    except Exception as e:
        print(f"Error converting SMD: {e}")
        import traceback
        traceback.print_exc()
        return False


# ========== Auto-Distributed Functions ==========

    def get_texture_names_from_smd(self) -> List[str]:
        """استخراج أسماء القوام من SMD"""
        # SMD لا يحتوي على معلومات مباشرة عن القوام، نستخدم اسم افتراضي
        return ["texture.png"]

