"""
animation/anim_exporter.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class AnimationExporter:
    """مصدر للرسوم المتحركة من XTRW/ TXAN"""
    
    def __init__(self, model):
        self.model = model
        self.animations: List[Animation] = []
    
    def extract_from_txan(self) -> List[Animation]:
        """استخراج الرسوم المتحركة من بيانات TXAN"""
        if not hasattr(self.model, 'txan_data') or not self.model.txan_data:
            return []
        
        animations = []
        for i, txan in enumerate(self.model.txan_data):
            # تحليل بيانات TXAN
            fields = txan.unknown_fields
            
            # تخمين معنى الحقول
            if len(fields) >= 28:
                bone_count = fields[0] if fields[0] < 100 else 0
                frame_count = fields[1] if fields[1] < 1000 else 0
                duration = fields[2] / 1000.0 if fields[2] > 0 else 1.0
                
                keyframes = []
                for frame in range(min(frame_count, 100)):
                    for bone in range(min(bone_count, 10)):
                        # قراءة الموضع (تخميني - يحتاج لتحليل دقيق)
                        pos = Vector3(
                            fields[4 + bone * 3] if 4 + bone * 3 < len(fields) else 0,
                            fields[5 + bone * 3] if 5 + bone * 3 < len(fields) else 0,
                            fields[6 + bone * 3] if 6 + bone * 3 < len(fields) else 0
                        )
                        
                        keyframes.append(AnimationKeyframe(
                            time=frame / max(frame_count, 1) * duration,
                            bone_id=bone,
                            position=pos,
                            rotation=Vector3(0, 0, 0),
                            scale=Vector3(1, 1, 1)
                        ))
                
                if keyframes:
                    animations.append(Animation(
                        name=f"animation_{i}",
                        duration=duration,
                        fps=30.0,
                        keyframes=keyframes,
                        bone_count=bone_count
                    ))
        
        self.animations = animations
        return animations
    
    def export_to_gltf_animations(self, output_path: str) -> bool:
        """تصدير الرسوم المتحركة إلى glTF (مع دعم الحركة)"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available")
            return False
        
        if not self.animations:
            print("   No animations to export")
            return False
        
        try:
            from pygltflib import GLTF2, Animation as GltfAnimation, AnimationChannel, AnimationSampler
            
            gltf = GLTF2()
            
            # بناء العقد للعظام
            bone_nodes = []
            for i, bone in enumerate(self.model.bones):
                node = Node(name=bone.name)
                gltf.nodes.append(node)
                bone_nodes.append(len(gltf.nodes)-1)
            
            # بناء الرسوم المتحركة
            for anim in self.animations:
                gltf_anim = GltfAnimation()
                gltf_anim.name = anim.name
                
                # تجميع الإطارات المفتاحية لكل عظمة
                for bone_id in range(min(anim.bone_count, len(bone_nodes))):
                    bone_keyframes = [kf for kf in anim.keyframes if kf.bone_id == bone_id]
                    if not bone_keyframes:
                        continue
                    
                    # إعداد sampler للحركة
                    sampler = AnimationSampler()
                    sampler.input = [kf.time for kf in bone_keyframes]
                    sampler.output = [
                        [kf.position.x, kf.position.y, kf.position.z] 
                        for kf in bone_keyframes
                    ]
                    
                    # إضافة channel للعظمة
                    channel = AnimationChannel()
                    channel.sampler = len(gltf_anim.samplers)
                    channel.target.node = bone_nodes[bone_id]
                    channel.target.path = "translation"
                    
                    gltf_anim.samplers.append(sampler)
                    gltf_anim.channels.append(channel)
                
                gltf.animations.append(gltf_anim)
            
            # حفظ الملف
            gltf.save(f"{output_path}_animated.gltf")
            print(f"   🎬 Exported {len(self.animations)} animations to glTF")
            return True
            
        except Exception as e:
            print(f"   Error exporting animations: {e}")
            return False
    
    def export_to_json(self, output_path: str):
        """تصدير الرسوم المتحركة إلى JSON"""
        data = {
            "animations": [
                {
                    "name": anim.name,
                    "duration": anim.duration,
                    "fps": anim.fps,
                    "bone_count": anim.bone_count,
                    "keyframes": [
                        {
                            "time": kf.time,
                            "bone_id": kf.bone_id,
                            "position": [kf.position.x, kf.position.y, kf.position.z],
                            "rotation": [kf.rotation.x, kf.rotation.y, kf.rotation.z],
                            "scale": [kf.scale.x, kf.scale.y, kf.scale.z]
                        }
                        for kf in anim.keyframes
                    ]
                }
                for anim in self.animations
            ]
        }
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        print(f"   🎬 Animations (JSON): {output_path}")

class Animation:
    """رسوم متحركة للنموذج"""
    name: str
    duration: float
    fps: float
    keyframes: List[AnimationKeyframe]
    bone_count: int

class AnimationKeyframe:
    """إطار مفتاحي للحركة"""
    time: float
    bone_id: int
    position: Vector3
    rotation: Vector3
    scale: Vector3


# ========== Functions ==========
def add_animation_support_to_igi2():
    """إضافة دعم الرسوم المتحركة إلى MefModelIGI2"""
    
    def extract_animations(self) -> List[AdvancedAnimation]:
        """استخراج الرسوم المتحركة من النموذج"""
        analyzer = AdvancedAnimationAnalyzer()
        
        # من TXAN
        if hasattr(self, 'txan_data') and self.txan_data:
            bone_count = len(self.bones) if hasattr(self, 'bones') else 0
            animations = analyzer.analyze_txan(self.txan_data, bone_count)
            print(f"   🎬 Extracted {len(animations)} animations from TXAN")
        
        # من Morph Channels
        if hasattr(self, 'morph_channels') and self.morph_channels:
            morph_anims = analyzer.analyze_morph_targets(self.morph_channels)
            animations.extend(morph_anims)
            print(f"   🎬 Extracted {len(morph_anims)} morph animations")
        
        return animations
    
    def export_animations(self, out_dir: str, base_name: str, formats: List[str] = None):
        """تصدير الرسوم المتحركة إلى صيغ متعددة"""
        if formats is None:
            formats = ["json", "mmd"]
        
        animations = self.extract_animations()
        if not animations:
            print("   No animations to export")
            return
        
        analyzer = AdvancedAnimationAnalyzer()
        analyzer.animations = animations
        
        for fmt in formats:
            if fmt == "json":
                analyzer.export_to_fbx_style(os.path.join(out_dir, f"{base_name}_animations.json"))
            elif fmt == "mmd":
                analyzer.export_to_mmd(os.path.join(out_dir, f"{base_name}.vmd"))
    
    # إضافة الدوال إلى الكلاس
    MefModelIGI2.extract_animations = extract_animations
    MefModelIGI2.export_animations = export_animations
    
    print("✅ Animation support added to MefModelIGI2")

    def extract_animations(self) -> List[AdvancedAnimation]:
        """استخراج الرسوم المتحركة من النموذج"""
        analyzer = AdvancedAnimationAnalyzer()
        
        # من TXAN
        if hasattr(self, 'txan_data') and self.txan_data:
            bone_count = len(self.bones) if hasattr(self, 'bones') else 0
            animations = analyzer.analyze_txan(self.txan_data, bone_count)
            print(f"   🎬 Extracted {len(animations)} animations from TXAN")
        
        # من Morph Channels
        if hasattr(self, 'morph_channels') and self.morph_channels:
            morph_anims = analyzer.analyze_morph_targets(self.morph_channels)
            animations.extend(morph_anims)
            print(f"   🎬 Extracted {len(morph_anims)} morph animations")
        
        return animations

    def export_animations(self, out_dir: str, base_name: str, formats: List[str] = None):
        """تصدير الرسوم المتحركة إلى صيغ متعددة"""
        if formats is None:
            formats = ["json", "mmd"]
        
        animations = self.extract_animations()
        if not animations:
            print("   No animations to export")
            return
        
        analyzer = AdvancedAnimationAnalyzer()
        analyzer.animations = animations
        
        for fmt in formats:
            if fmt == "json":
                analyzer.export_to_fbx_style(os.path.join(out_dir, f"{base_name}_animations.json"))
            elif fmt == "mmd":
                analyzer.export_to_mmd(os.path.join(out_dir, f"{base_name}.vmd"))
