"""
animation/txan_analyzer.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class BoneAnimationTrack:
    """مسار حركة لعظمة واحدة"""
    bone_id: int
    bone_name: str
    positions: List[Tuple[float, float, float]] = field(default_factory=list)
    rotations: List[Tuple[float, float, float, float]] = field(default_factory=list)  # quaternion
    scales: List[Tuple[float, float, float]] = field(default_factory=list)
    times: List[float] = field(default_factory=list)

class AdvancedAnimation:
    """رسوم متحركة متقدمة مع جميع البيانات"""
    name: str
    duration: float
    frame_count: int
    fps: float
    bone_tracks: Dict[int, BoneAnimationTrack] = field(default_factory=dict)
    morph_targets: List[str] = field(default_factory=list)  # أهداف التشكل
    event_markers: Dict[float, str] = field(default_factory=dict)  # أحداث في أطر زمنية

class AdvancedAnimationAnalyzer:
    """محلل متقدم للرسوم المتحركة من بيانات MEF"""
    
    def __init__(self):
        self.animations: List[AdvancedAnimation] = []
    
    def analyze_txan(self, txan_data: List, bone_count: int, frame_rate: float = 30.0) -> List[AdvancedAnimation]:
        """تحليل متقدم لبيانات TXAN"""
        animations = []
        
        for txan_idx, txan in enumerate(txan_data):
            fields = txan.unknown_fields
            
            if len(fields) < 28:
                continue
            
            # تحليل الحقول حسب فهم أعمق لـ TXAN
            # ملاحظة: هذه التحليلات تحتاج لاختبار على ملفات حقيقية
            
            # ---- تخمين معنى الحقول ----
            version = fields[0]          # غالباً 1 أو 2
            frame_count = fields[1]      # عدد الإطارات
            duration_ms = fields[2]      # المدة بالميلي ثانية
            bone_count_anim = fields[3]  # عدد العظام المتحركة
            
            duration = duration_ms / 1000.0 if duration_ms > 0 else frame_count / frame_rate
            
            # إنشاء كائن الحركة
            anim = AdvancedAnimation(
                name=f"animation_{txan_idx}",
                duration=duration,
                frame_count=frame_count,
                fps=frame_rate
            )
            
            # استخراج مسارات العظام
            frame_data_size = bone_count_anim * 6  # 3 موضع + 3 دوران (تخميني)
            
            for frame in range(min(frame_count, 100)):  # حد أقصى 100 إطار
                frame_time = frame / frame_count * duration if frame_count > 0 else 0
                
                for bone in range(min(bone_count_anim, bone_count)):
                    # حساب المؤشر في المصفوفة
                    idx = 4 + (frame * bone_count_anim + bone) * 6
                    
                    if idx + 5 < len(fields):
                        # قراءة موضع العظمة
                        px = fields[idx] / 100.0 if fields[idx] != 0 else 0
                        py = fields[idx + 1] / 100.0 if fields[idx + 1] != 0 else 0
                        pz = fields[idx + 2] / 100.0 if fields[idx + 2] != 0 else 0
                        
                        # قراءة دوران العظمة (كأويلر)
                        rx = fields[idx + 3] / 32768.0 * 180.0
                        ry = fields[idx + 4] / 32768.0 * 180.0
                        rz = fields[idx + 5] / 32768.0 * 180.0
                        
                        # إنشاء المسار إذا لم يكن موجوداً
                        if bone not in anim.bone_tracks:
                            anim.bone_tracks[bone] = BoneAnimationTrack(
                                bone_id=bone,
                                bone_name=f"bone_{bone}"
                            )
                        
                        # إضافة البيانات للإطار
                        anim.bone_tracks[bone].times.append(frame_time)
                        anim.bone_tracks[bone].positions.append((px, py, pz))
                        
                        # تحويل أويلر إلى كواترنيون
                        quat = self.euler_to_quaternion(rx, ry, rz)
                        anim.bone_tracks[bone].rotations.append(quat)
                        anim.bone_tracks[bone].scales.append((1.0, 1.0, 1.0))
            
            if anim.bone_tracks:
                animations.append(anim)
        
        self.animations = animations
        return animations
    
    def euler_to_quaternion(self, rx: float, ry: float, rz: float) -> Tuple[float, float, float, float]:
        """تحويل زوايا أويلر (بالدرجات) إلى كواترنيون"""
        # تحويل إلى راديان
        rx_rad = np.radians(rx)
        ry_rad = np.radians(ry)
        rz_rad = np.radians(rz)
        
        # حساب الكواترنيون
        cx = np.cos(rx_rad * 0.5)
        sx = np.sin(rx_rad * 0.5)
        cy = np.cos(ry_rad * 0.5)
        sy = np.sin(ry_rad * 0.5)
        cz = np.cos(rz_rad * 0.5)
        sz = np.sin(rz_rad * 0.5)
        
        qw = cx * cy * cz + sx * sy * sz
        qx = sx * cy * cz - cx * sy * sz
        qy = cx * sy * cz + sx * cy * sz
        qz = cx * cy * sz - sx * sy * cz
        
        return (qx, qy, qz, qw)
    
    def analyze_morph_targets(self, morph_channels: Dict, frame_rate: float = 30.0) -> List[AdvancedAnimation]:
        """تحليل أهداف التشكل للرسوم المتحركة"""
        animations = []
        
        for channel_id, vertices in morph_channels.items():
            if len(vertices) == 0:
                continue
            
            # إنشاء حركة للتشكل
            anim = AdvancedAnimation(
                name=f"morph_channel_{channel_id}",
                duration=1.0,
                frame_count=1,
                fps=frame_rate
            )
            
            # إضافة أهداف التشكل
            for v in vertices[:10]:  # حد أقصى 10 أهداف
                target_name = f"morph_target_{v['index']}"
                anim.morph_targets.append(target_name)
            
            animations.append(anim)
        
        self.animations.extend(animations)
        return animations
    
    def blend_animations(self, anim1: AdvancedAnimation, anim2: AdvancedAnimation, 
                         weight: float) -> AdvancedAnimation:
        """دمج حركتين مع وزن معين"""
        if weight <= 0:
            return anim1
        if weight >= 1:
            return anim2
        
        blended = AdvancedAnimation(
            name=f"blended_{anim1.name}_{anim2.name}",
            duration=max(anim1.duration, anim2.duration),
            frame_count=max(anim1.frame_count, anim2.frame_count),
            fps=anim1.fps
        )
        
        # دمج مسارات العظام المشتركة
        common_bones = set(anim1.bone_tracks.keys()) & set(anim2.bone_tracks.keys())
        
        for bone_id in common_bones:
            track1 = anim1.bone_tracks[bone_id]
            track2 = anim2.bone_tracks[bone_id]
            
            # دمج البيانات
            blended_track = BoneAnimationTrack(
                bone_id=bone_id,
                bone_name=track1.bone_name,
                times=track1.times[:],  # استخدام وقت الحركة الأولى
                positions=[],
                rotations=[],
                scales=[]
            )
            
            # دمج المواضع
            for i in range(min(len(track1.positions), len(track2.positions))):
                pos1 = track1.positions[i]
                pos2 = track2.positions[i]
                blended_pos = (
                    pos1[0] * (1 - weight) + pos2[0] * weight,
                    pos1[1] * (1 - weight) + pos2[1] * weight,
                    pos1[2] * (1 - weight) + pos2[2] * weight
                )
                blended_track.positions.append(blended_pos)
            
            # دمج الدورانات (Slerp للكواترنيونات)
            for i in range(min(len(track1.rotations), len(track2.rotations))):
                quat1 = track1.rotations[i]
                quat2 = track2.rotations[i]
                blended_quat = self.slerp_quaternion(quat1, quat2, weight)
                blended_track.rotations.append(blended_quat)
            
            blended.bone_tracks[bone_id] = blended_track
        
        return blended
    
    def slerp_quaternion(self, q1: Tuple[float, ...], q2: Tuple[float, ...], 
                         t: float) -> Tuple[float, float, float, float]:
        """SLERP بين كواترنيونين"""
        # نُحوّل إلى numpy arrays
        q1_arr = np.array(q1)
        q2_arr = np.array(q2)
        
        # حساب جيب التمام
        dot = np.dot(q1_arr, q2_arr)
        
        # إذا كانت الزاوية صغيرة، استخدم LERP
        if dot < 0:
            q2_arr = -q2_arr
            dot = -dot
        
        if dot > 0.9995:
            # LERP
            result = q1_arr + t * (q2_arr - q1_arr)
            result = result / np.linalg.norm(result)
            return tuple(result)
        
        # SLERP
        theta_0 = np.arccos(dot)
        theta = theta_0 * t
        sin_theta = np.sin(theta)
        sin_theta_0 = np.sin(theta_0)
        
        s1 = np.cos(theta) - dot * sin_theta / sin_theta_0
        s2 = sin_theta / sin_theta_0
        
        result = (q1_arr * s1) + (q2_arr * s2)
        return tuple(result)
    
    def export_to_mmd(self, output_path: str) -> bool:
        """تصدير الحركة إلى صيغة MMD (.vmd)"""
        if not self.animations:
            return False
        
        # MMD VMD format
        # Header: "Vocaloid Motion Data 0002"
        header = b"Vocaloid Motion Data 0002\0"
        
        with open(output_path, 'wb') as f:
            f.write(header)
            
            # عدد الحركات
            f.write(struct.pack('<I', len(self.animations)))
            
            for anim in self.animations:
                # اسم الحركة (15 بايت + null)
                name_bytes = anim.name.encode('utf-8', errors='ignore')[:15]
                f.write(name_bytes.ljust(15, b'\x00'))
                f.write(b'\x00')
                
                # عدد الإطارات
                f.write(struct.pack('<I', anim.frame_count))
                
                # كتابة إطارات الحركة
                for bone_id, track in anim.bone_tracks.items():
                    for i, time in enumerate(track.times):
                        frame_idx = int(time * anim.fps)
                        
                        # بيانات الإطار
                        f.write(struct.pack('<I', frame_idx))  # رقم الإطار
                        
                        # اسم العظمة (15 بايت + null)
                        bone_name = track.bone_name.encode('utf-8', errors='ignore')[:15]
                        f.write(bone_name.ljust(15, b'\x00'))
                        f.write(b'\x00')
                        
                        # الموضع
                        if i < len(track.positions):
                            px, py, pz = track.positions[i]
                            f.write(struct.pack('<fff', px, py, pz))
                        else:
                            f.write(struct.pack('<fff', 0, 0, 0))
                        
                        # الدوران (كواترنيون)
                        if i < len(track.rotations):
                            qx, qy, qz, qw = track.rotations[i]
                            f.write(struct.pack('<ffff', qx, qy, qz, qw))
                        else:
                            f.write(struct.pack('<ffff', 0, 0, 0, 1))
                        
                        # الإقحام (interpolation) - بيانات افتراضية
                        f.write(b'\x00' * 64)
        
        print(f"   🎬 Exported animation to MMD: {output_path}")
        return True
    
    def export_to_fbx_style(self, output_path: str) -> bool:
        """تصدير الحركة إلى صيغة تشبه FBX (JSON)"""
        if not self.animations:
            return False
        
        data = {
            "animations": [],
            "format": "Advanced Animation Data",
            "version": "1.0"
        }
        
        for anim in self.animations:
            anim_data = {
                "name": anim.name,
                "duration": anim.duration,
                "frame_count": anim.frame_count,
                "fps": anim.fps,
                "bone_tracks": [],
                "morph_targets": anim.morph_targets,
                "event_markers": anim.event_markers
            }
            
            for bone_id, track in anim.bone_tracks.items():
                track_data = {
                    "bone_id": bone_id,
                    "bone_name": track.bone_name,
                    "frames": [
                        {
                            "time": track.times[i],
                            "position": list(track.positions[i]) if i < len(track.positions) else [0, 0, 0],
                            "rotation": list(track.rotations[i]) if i < len(track.rotations) else [0, 0, 0, 1],
                            "scale": list(track.scales[i]) if i < len(track.scales) else [1, 1, 1]
                        }
                        for i in range(len(track.times))
                    ]
                }
                anim_data["bone_tracks"].append(track_data)
            
            data["animations"].append(anim_data)
        
        import json
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        
        print(f"   🎬 Exported animation to JSON: {output_path}")
        return True


# ========== Functions ==========