"""
formats/__init__.py - Package initialization
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# ============================================================

__all__ = ['MefModelIGI1', 'MefModelIGI2', 'StudioHeader', 'SMDExporter', 'OBJExporter', 'detect_file_type', 'detect_mef_version']

from .__init__ import MefModelIGI1
from .__init__ import MefModelIGI2
from .__init__ import StudioHeader
from .__init__ import SMDExporter
from .__init__ import OBJExporter
from .__init__ import detect_file_type
from .__init__ import detect_mef_version