"""
formats/mdl_parser.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class MDLHeader:
    """رأس ملف MDL حسب وثائق Valve"""
    id: int                     # 'IDST'
    version: int                # إصدار الملف
    name: str                   # اسم النموذج (64 حرف)
    length: int                 # حجم الملف
    
    eyeposition: Tuple[float, float, float]
    min_corner: Tuple[float, float, float]
    max_corner: Tuple[float, float, float]
    bbmin: Tuple[float, float, float]
    bbmax: Tuple[float, float, float]
    
    flags: int
    
    numbones: int
    boneindex: int
    
    numbonecontrollers: int
    bonecontrollerindex: int
    
    numhitboxes: int
    hitboxindex: int
    
    numseq: int
    seqindex: int
    
    numseqgroups: int
    seqgroupindex: int
    
    numtextures: int
    textureindex: int
    texturedataindex: int
    
    numskinref: int
    numskinfamilies: int
    skinindex: int
    
    numbodyparts: int
    bodypartindex: int
    
    numattachments: int
    attachmentindex: int
    
    soundtable: int
    soundindex: int
    soundgroups: int
    soundgroupindex: int
    
    numtransitions: int
    transitionindex: int
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        id_val = buffer.read_uint32()
        version = buffer.read_uint32()
        name = buffer.read_ascii_string(64)
        length = buffer.read_uint32()
        
        eyeposition = buffer.read_fmt("3f")
        min_corner = buffer.read_fmt("3f")
        max_corner = buffer.read_fmt("3f")
        bbmin = buffer.read_fmt("3f")
        bbmax = buffer.read_fmt("3f")
        
        flags = buffer.read_uint32()
        
        numbones = buffer.read_uint32()
        boneindex = buffer.read_uint32()
        
        numbonecontrollers = buffer.read_uint32()
        bonecontrollerindex = buffer.read_uint32()
        
        numhitboxes = buffer.read_uint32()
        hitboxindex = buffer.read_uint32()
        
        numseq = buffer.read_uint32()
        seqindex = buffer.read_uint32()
        
        numseqgroups = buffer.read_uint32()
        seqgroupindex = buffer.read_uint32()
        
        numtextures = buffer.read_uint32()
        textureindex = buffer.read_uint32()
        texturedataindex = buffer.read_uint32()
        
        numskinref = buffer.read_uint32()
        numskinfamilies = buffer.read_uint32()
        skinindex = buffer.read_uint32()
        
        numbodyparts = buffer.read_uint32()
        bodypartindex = buffer.read_uint32()
        
        numattachments = buffer.read_uint32()
        attachmentindex = buffer.read_uint32()
        
        soundtable = buffer.read_uint32()
        soundindex = buffer.read_uint32()
        soundgroups = buffer.read_uint32()
        soundgroupindex = buffer.read_uint32()
        
        numtransitions = buffer.read_uint32()
        transitionindex = buffer.read_uint32()
        
        return cls(
            id_val, version, name, length,
            eyeposition, min_corner, max_corner, bbmin, bbmax,
            flags,
            numbones, boneindex,
            numbonecontrollers, bonecontrollerindex,
            numhitboxes, hitboxindex,
            numseq, seqindex,
            numseqgroups, seqgroupindex,
            numtextures, textureindex, texturedataindex,
            numskinref, numskinfamilies, skinindex,
            numbodyparts, bodypartindex,
            numattachments, attachmentindex,
            soundtable, soundindex, soundgroups, soundgroupindex,
            numtransitions, transitionindex
        )

class StudioBone:
    """هيكل العظمة"""
    name: str
    parent: int
    flags: int
    bonecontroller: List[int]
    value: List[float]
    scale: List[float]
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        name = buffer.read_ascii_string(32)
        parent = buffer.read_int32()
        flags = buffer.read_int32()
        bonecontroller = [buffer.read_int32() for _ in range(6)]
        value = [buffer.read_float() for _ in range(6)]
        scale = [buffer.read_float() for _ in range(6)]
        return cls(name, parent, flags, bonecontroller, value, scale)

class StudioBodyPart:
    """جزء من الجسم"""
    name: str
    nummodels: int
    base: int
    modelindex: int
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        name = buffer.read_ascii_string(64)
        nummodels = buffer.read_uint32()
        base = buffer.read_uint32()
        modelindex = buffer.read_uint32()
        return cls(name, nummodels, base, modelindex)

class StudioModel:
    """نموذج فرعي"""
    name: str
    type: int
    boundingradius: float
    nummesh: int
    meshindex: int
    numverts: int
    vertinfoindex: int
    vertindex: int
    numnorms: int
    norminfoindex: int
    normindex: int
    numgroups: int
    groupindex: int
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        name = buffer.read_ascii_string(64)
        type_val = buffer.read_uint32()
        boundingradius = buffer.read_float()
        nummesh = buffer.read_uint32()
        meshindex = buffer.read_uint32()
        numverts = buffer.read_uint32()
        vertinfoindex = buffer.read_uint32()
        vertindex = buffer.read_uint32()
        numnorms = buffer.read_uint32()
        norminfoindex = buffer.read_uint32()
        normindex = buffer.read_uint32()
        numgroups = buffer.read_uint32()
        groupindex = buffer.read_uint32()
        return cls(name, type_val, boundingradius, nummesh, meshindex,
                   numverts, vertinfoindex, vertindex, numnorms,
                   norminfoindex, normindex, numgroups, groupindex)

class StudioMesh:
    """شبكة"""
    numtris: int
    triindex: int
    skinref: int
    numnorms: int
    normindex: int
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        numtris = buffer.read_uint32()
        triindex = buffer.read_uint32()
        skinref = buffer.read_uint32()
        numnorms = buffer.read_uint32()
        normindex = buffer.read_uint32()
        return cls(numtris, triindex, skinref, numnorms, normindex)

class StudioVertex:
    """رأس"""
    x: float
    y: float
    z: float
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(buffer.read_float(), buffer.read_float(), buffer.read_float())

class StudioNormal:
    """طبيعية"""
    x: float
    y: float
    z: float
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(buffer.read_float(), buffer.read_float(), buffer.read_float())

class StudioTriangle:
    """مثلث"""
    vertindex: List[int]  # 3 indices
    normindex: List[int]  # 3 indices
    s: int
    t: int
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        vertindex = [buffer.read_int16() for _ in range(3)]
        normindex = [buffer.read_int16() for _ in range(3)]
        s = buffer.read_int16()
        t = buffer.read_int16()
        return cls(vertindex, normindex, s, t)

class StudioVertexInfo:
    """معلومات الرأس (مؤشرات إلى العظام والأوزان)"""
    bone_id: int
    bone_count: int
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        bone_id = buffer.read_uint8()
        bone_count = buffer.read_uint8()
        buffer.read(2)  # padding
        return cls(bone_id, bone_count)

class StudioNormalInfo:
    """معلومات الطبيعية"""
    bone_id: int
    bone_count: int
    
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        bone_id = buffer.read_uint8()
        bone_count = buffer.read_uint8()
        buffer.read(2)  # padding
        return cls(bone_id, bone_count)

class StudioHeader:
    """قارئ ملفات MDL حسب وثائق Valve الرسمية"""
    
    def __init__(self, buffer: Buffer):
        self.buffer = buffer
        self.header: MDLHeader = None
        self.bones: List[StudioBone] = []
        self.bodyparts: List[StudioBodyPart] = []
        self.models: List[StudioModel] = []
        self.meshes: List[StudioMesh] = []
        self.vertices: List[StudioVertex] = []
        self.normals: List[StudioNormal] = []
        self.triangles: List[StudioTriangle] = []
        
        self._parse()
    
    def _parse(self):
        """التحليل الكامل لملف MDL"""
        self.header = MDLHeader.from_buffer(self.buffer)
        print(f"MDL Header: {self.header.name}")
        print(f"  Version: {self.header.version}")
        print(f"  Bones: {self.header.numbones}")
        print(f"  Bodyparts: {self.header.numbodyparts}")
        print(f"  Textures: {self.header.numtextures}")
        print(f"  Sequences: {self.header.numseq}")
        
        # قراءة العظام
        if self.header.numbones > 0 and self.header.boneindex > 0:
            self.buffer.offset = self.header.boneindex
            for i in range(self.header.numbones):
                bone = StudioBone.from_buffer(self.buffer)
                self.bones.append(bone)
            print(f"  Parsed {len(self.bones)} bones")
        
        # قراءة أجزاء الجسم
        if self.header.numbodyparts > 0 and self.header.bodypartindex > 0:
            self.buffer.offset = self.header.bodypartindex
            for bp_idx in range(self.header.numbodyparts):
                bodypart = StudioBodyPart.from_buffer(self.buffer)
                self.bodyparts.append(bodypart)
                print(f"  Bodypart {bp_idx}: {bodypart.name}, models={bodypart.nummodels}")
                
                # قراءة النماذج
                if bodypart.nummodels > 0 and bodypart.modelindex > 0:
                    current_offset = self.buffer.offset
                    self.buffer.offset = bodypart.modelindex
                    
                    for m_idx in range(bodypart.nummodels):
                        model = StudioModel.from_buffer(self.buffer)
                        self.models.append(model)
                        print(f"    Model {m_idx}: {model.name}, meshes={model.nummesh}, verts={model.numverts}")
                        
                        # قراءة الشبكات
                        if model.nummesh > 0 and model.meshindex > 0:
                            mesh_offset_backup = self.buffer.offset
                            self.buffer.offset = model.meshindex
                            
                            for mesh_idx in range(model.nummesh):
                                mesh = StudioMesh.from_buffer(self.buffer)
                                self.meshes.append(mesh)
                                print(f"      Mesh {mesh_idx}: tris={mesh.numtris}")
                            
                            self.buffer.offset = mesh_offset_backup
                    
                    self.buffer.offset = current_offset
        
        # قراءة الرؤوس والمثلثات
        self._parse_geometry()
        
        print(f"  Total vertices: {len(self.vertices)}")
        print(f"  Total triangles: {len(self.triangles)}")
    
    def _parse_geometry(self):
        """قراءة الرؤوس والمثلثات من جميع النماذج مع دعم Triangle Strips/Fans"""
        
        # قوائم مؤقتة للرؤوس والطبيعيات والمثلثات
        all_vertices = []      # الرؤوس الفعلية (x,y,z)
        all_normals = []       # الطبيعيات الفعلية (nx,ny,nz)
        all_vertex_infos = []  # معلومات الرأس (العظام)
        all_normal_infos = []  # معلومات الطبيعية
        all_triangles = []     # المثلثات (مؤشرات إلى all_vertices)
        
        for model in self.models:
            if model.numverts == 0:
                continue
            
            # ========== 1. قراءة معلومات الرؤوس ==========
            if model.vertinfoindex > 0 and model.vertinfoindex <= len(self.buffer.data):
                self.buffer.offset = model.vertinfoindex
                for v in range(model.numverts):
                    vert_info = StudioVertexInfo.from_buffer(self.buffer)
                    all_vertex_infos.append(vert_info)
            
            # ========== 2. قراءة الرؤوس الفعلية ==========
            if model.vertindex > 0 and model.vertindex <= len(self.buffer.data):
                self.buffer.offset = model.vertindex
                for v in range(model.numverts):
                    vertex = StudioVertex.from_buffer(self.buffer)
                    all_vertices.append(vertex)
            
            # ========== 3. قراءة معلومات الطبيعيات ==========
            if model.norminfoindex > 0 and model.norminfoindex <= len(self.buffer.data):
                self.buffer.offset = model.norminfoindex
                for n in range(model.numnorms):
                    norm_info = StudioNormalInfo.from_buffer(self.buffer)
                    all_normal_infos.append(norm_info)
            
            # ========== 4. قراءة الطبيعيات الفعلية ==========
            if model.normindex > 0 and model.normindex <= len(self.buffer.data):
                self.buffer.offset = model.normindex
                for n in range(model.numnorms):
                    normal = StudioNormal.from_buffer(self.buffer)
                    all_normals.append(normal)
            
            # ========== 5. قراءة المثلثات من الشبكات باستخدام Triangle Commands ==========
            for mesh in self.meshes:
                if mesh.numtris == 0 or mesh.triindex == 0:
                    continue
                
                if mesh.triindex <= len(self.buffer.data):
                    self.buffer.offset = mesh.triindex
                    # قراءة المثلثات باستخدام طريقة Strip/Fan
                    self._parse_triangle_commands(all_triangles, mesh.skinref)
        
        # معالجة المثلثات وتحويل المؤشرات
        valid_vertices = []
        valid_normals = []
        valid_triangles = []
        
        for v in all_vertices:
            valid_vertices.append(v)
        
        for n in all_normals:
            valid_normals.append(n)
        
        # تحويل المثلثات: استخراج المؤشرات الصالحة
        for tri in all_triangles:
            if all(0 <= idx < len(valid_vertices) for idx in tri.vertindex):
                valid_triangles.append(tri)
        
        self.vertices = valid_vertices
        self.normals = valid_normals
        self.triangles = valid_triangles
        
        print(f"  Final vertices: {len(self.vertices)}")
        print(f"  Final normals: {len(self.normals)}")
        print(f"  Final triangles: {len(self.triangles)}")
        
        # تحقق أخير
        if self.triangles:
            max_idx = max([max(tri.vertindex) for tri in self.triangles])
            if max_idx >= len(self.vertices):
                print(f"  ⚠️ WARNING: Still have out-of-range indices! max={max_idx}, vertices={len(self.vertices)}")
    
    def _parse_triangle_commands(self, all_triangles: list, skinref: int):
        """
        قراءة Triangle Commands من MDL (Triangle Strips و Fans)
        هذه هي الطريقة الصحيحة التي تستخدمها لعبة Half-Life
        """
        vertex_cache = []  # لتخزين مؤشرات الرؤوس المؤقتة في Strips/Fans
        
        while True:
            # قراءة الأمر (short/int16)
            if self.buffer.offset + 2 > len(self.buffer.data):
                break
            
            command = self.buffer.read_int16()
            
            if command == 0:
                # نهاية قائمة المثلثات
                break
            
            if command > 0:
                # Triangle Strip
                num_vertices = command
                # قراءة الرؤوس
                vertices_in_strip = []
                for i in range(num_vertices):
                    if self.buffer.offset + 8 > len(self.buffer.data):  # 2+2+2+2=8 bytes
                        break
                    vert_idx = self.buffer.read_int16()
                    norm_idx = self.buffer.read_int16()
                    s = self.buffer.read_int16()
                    t = self.buffer.read_int16()
                    vertices_in_strip.append((vert_idx, norm_idx, s, t))
                
                # تحويل Strip إلى مثلثات
                # Strip: 0-1-2, 1-2-3, 2-3-4, ...
                for i in range(len(vertices_in_strip) - 2):
                    a = vertices_in_strip[i]
                    b = vertices_in_strip[i + 1]
                    c = vertices_in_strip[i + 2]
                    
                    # كل 3 رؤوس تشكل مثلثاً (مع تبديل الترتيب لـ Odd/Even)
                    if i % 2 == 0:
                        tri = StudioTriangle(
                            vertindex=[a[0], b[0], c[0]],
                            normindex=[a[1], b[1], c[1]],
                            s=a[2], t=a[3]
                        )
                    else:
                        tri = StudioTriangle(
                            vertindex=[b[0], a[0], c[0]],
                            normindex=[b[1], a[1], c[1]],
                            s=b[2], t=b[3]
                        )
                    all_triangles.append(tri)
                    
            elif command < 0:
                # Triangle Fan
                num_vertices = -command
                # قراءة الرؤوس
                vertices_in_fan = []
                for i in range(num_vertices):
                    if self.buffer.offset + 8 > len(self.buffer.data):
                        break
                    vert_idx = self.buffer.read_int16()
                    norm_idx = self.buffer.read_int16()
                    s = self.buffer.read_int16()
                    t = self.buffer.read_int16()
                    vertices_in_fan.append((vert_idx, norm_idx, s, t))
                
                # تحويل Fan إلى مثلثات
                # Fan: 0-1-2, 0-2-3, 0-3-4, ...
                if len(vertices_in_fan) >= 3:
                    first = vertices_in_fan[0]
                    for i in range(1, len(vertices_in_fan) - 1):
                        b = vertices_in_fan[i]
                        c = vertices_in_fan[i + 1]
                        tri = StudioTriangle(
                            vertindex=[first[0], b[0], c[0]],
                            normindex=[first[1], b[1], c[1]],
                            s=first[2], t=first[3]
                        )
                        all_triangles.append(tri)
    
    def extract_textures(self, output_dir: str):
        """استخراج القوام المدمجة من ملف MDL"""
        if self.header.numtextures == 0 or self.header.textureindex == 0:
            print("  No embedded textures found")
            return
        
        self.buffer.offset = self.header.textureindex
        texture_dir = os.path.join(output_dir, "textures")
        Path(texture_dir).mkdir(parents=True, exist_ok=True)
        
        for i in range(self.header.numtextures):
            # قراءة معلومات القوام
            name = self.buffer.read_ascii_string(64)
            flags = self.buffer.read_uint32()
            width = self.buffer.read_uint32()
            height = self.buffer.read_uint32()
            index = self.buffer.read_uint32()
            
            print(f"  Texture {i}: {name} ({width}x{height})")
            
            # قراءة بيانات القوام من texturedataindex
            if index > 0 and self.header.texturedataindex > 0:
                old_offset = self.buffer.offset
                self.buffer.offset = self.header.texturedataindex + index
                
                # حساب حجم البيانات (8-bit paletted في GoldSrc)
                data_size = width * height
                if data_size > 0 and data_size <= len(self.buffer.data) - self.buffer.offset:
                    # قراءة بيانات البكسل
                    pixel_data = self.buffer.read(data_size)
                    
                    # حفظ كملف TGA
                    tex_path = os.path.join(texture_dir, f"{name}.tga")
                    with open(tex_path, 'wb') as f:
                        # كتابة رأس TGA بسيط (RGB غير مضغوط)
                        # هذا رأس TGA أساسي - يمكن تحسينه
                        header = bytearray([
                            0,  # ID length
                            0,  # Color map type
                            2,  # Image type (RGB)
                            0, 0,  # Color map start
                            0, 0,  # Color map length
                            0,  # Color map bits
                            0, 0,  # X origin
                            0, 0,  # Y origin
                            width & 0xFF, (width >> 8) & 0xFF,  # Width
                            height & 0xFF, (height >> 8) & 0xFF,  # Height
                            24,  # Bits per pixel
                            0   # Image descriptor
                        ])
                        f.write(header)
                        f.write(pixel_data)
                    
                    print(f"    Saved: {tex_path}")
                
                self.buffer.offset = old_offset
    
    def debug_print_geometry(self):
        """طباعة معلومات تشخيصية عن الهندسة"""
        print(f"\n🔍 DEBUG: Total vertices: {len(self.vertices)}")
        print(f"🔍 DEBUG: Total normals: {len(self.normals)}")
        print(f"🔍 DEBUG: Total triangles: {len(self.triangles)}")
        
        if len(self.vertices) > 0:
            print(f"\n🔍 DEBUG: First 5 vertices (raw):")
            for i in range(min(5, len(self.vertices))):
                v = self.vertices[i]
                print(f"  v{i}: ({v.x:.2f}, {v.y:.2f}, {v.z:.2f})")
        
        if len(self.triangles) > 0:
            print(f"\n🔍 DEBUG: First 5 triangles (raw indices):")
            for i in range(min(5, len(self.triangles))):
                tri = self.triangles[i]
                print(f"  tri{i}: verts=({tri.vertindex[0]}, {tri.vertindex[1]}, {tri.vertindex[2]}), "
                      f"norms=({tri.normindex[0]}, {tri.normindex[1]}, {tri.normindex[2]}), "
                      f"uv=({tri.s}, {tri.t})")
        
        # التحقق من صحة المؤشرات
        if self.triangles:
            max_vert_idx = max([max(tri.vertindex) for tri in self.triangles])
            max_norm_idx = max([max(tri.normindex) for tri in self.triangles]) if self.triangles else -1
            print(f"\n🔍 DEBUG: Max vertex index used: {max_vert_idx} (total vertices: {len(self.vertices)})")
            print(f"🔍 DEBUG: Max normal index used: {max_norm_idx} (total normals: {len(self.normals)})")
            
            if max_vert_idx >= len(self.vertices):
                print(f"⚠️ WARNING: Vertex index {max_vert_idx} out of range!")
            if max_norm_idx >= len(self.normals) and len(self.normals) > 0:
                print(f"⚠️ WARNING: Normal index {max_norm_idx} out of range!")
    
    def export_obj_as_points(self, out_dir, base_name):
        """تصدير كل مثلث كثلاث رؤوس منفصلة (حل مؤقت للمؤشرات الخاطئة)"""
        if len(self.vertices) == 0 or len(self.triangles) == 0:
            print("No geometry to export")
            return
        
        obj_path = os.path.join(out_dir, f"{base_name}_points.obj")
        mtl_path = os.path.join(out_dir, f"{base_name}_points.mtl")
        
        with open(mtl_path, 'w', encoding='utf-8') as f:
            f.write(f"newmtl material\n")
            f.write("Ns 10.0000\n")
            f.write("Ka 1.0000 1.0000 1.0000\n")
            f.write("Kd 1.0000 1.0000 1.0000\n")
            f.write("Ks 0.0000 0.0000 0.0000\n")
        
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write(f"mtllib {base_name}_points.mtl\n")
            f.write(f"o {base_name}\n")
            
            # تجميع كل الرؤوس من المثلثات (بدون إعادة استخدام)
            all_points = []
            for tri in self.triangles:
                for idx in tri.vertindex:
                    if 0 <= idx < len(self.vertices):
                        v = self.vertices[idx]
                        # تحويل Y-up إلى Z-up
                        all_points.append((v.x, v.z, v.y))
                    else:
                        # نقطة وهمية للمؤشرات الخاطئة
                        all_points.append((0, 0, 0))
            
            # كتابة الرؤوس
            for p in all_points:
                f.write(f"v {p[0]:.6f} {p[1]:.6f} {p[2]:.6f}\n")
            
            # كتابة الوجوه (كل 3 رؤوس تشكل وجهاً)
            f.write(f"usemtl material\n")
            for i in range(0, len(all_points), 3):
                if i + 2 < len(all_points):
                    f.write(f"f {i+1} {i+2} {i+3}\n")
        
        print(f"   OBJ (points mode): {obj_path}")
    
    def export_obj(self, out_dir, base_name):
        """تصدير إلى OBJ"""
        self.debug_print_geometry()
        if len(self.vertices) == 0 or len(self.triangles) == 0:
            print("No geometry to export")
            return
        
        obj_path = os.path.join(out_dir, f"{base_name}.obj")
        mtl_path = os.path.join(out_dir, f"{base_name}.mtl")
        
        with open(mtl_path, 'w', encoding='utf-8') as f:
            f.write(f"newmtl {base_name}_material\n")
            f.write("Ns 10.0000\n")
            f.write("Ka 1.0000 1.0000 1.0000\n")
            f.write("Kd 1.0000 1.0000 1.0000\n")
            f.write("Ks 0.0000 0.0000 0.0000\n")
            if self.header.numtextures > 0:
                f.write("map_Kd texture.bmp\n")
        
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write(f"mtllib {base_name}.mtl\n")
            f.write(f"o {base_name}\n")
            
            # تجميع كل الرؤوس والطبيعيات و UVs
            all_vertices = []
            all_normals = []
            all_uvs = []
            
            for tri in self.triangles:
                for i in range(3):
                    vert_idx = tri.vertindex[i]
                    norm_idx = tri.normindex[i]
                    
                    if vert_idx >= 0 and vert_idx < len(self.vertices):
                        v = self.vertices[vert_idx]
                        # تحويل Y-up إلى Z-up
                        all_vertices.append((v.x, v.z, v.y))
                        
                        if norm_idx >= 0 and norm_idx < len(self.normals):
                            n = self.normals[norm_idx]
                            # تحويل Y-up إلى Z-up للطبيعيات
                            all_normals.append((n.x, n.z, n.y))
                        else:
                            all_normals.append((0, 0, 0))
                        
                        # UV من s,t (تطبيع)
                        u = tri.s / 32768.0 if tri.s != 0 else 0.0
                        vt = tri.t / 32768.0 if tri.t != 0 else 0.0
                        all_uvs.append((u, 1.0 - vt))
            
            if len(all_vertices) == 0:
                print("   No valid vertices to export")
                return
            
            # كتابة الرؤوس
            for v in all_vertices:
                f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
            
            # كتابة إحداثيات النسيج
            for uv in all_uvs:
                f.write(f"vt {uv[0]:.6f} {uv[1]:.6f}\n")
            
            # كتابة الطبيعيات
            for n in all_normals:
                f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
            
            # كتابة الوجوه (كل 3 رؤوس تشكل وجهاً واحداً)
            f.write(f"usemtl {base_name}_material\n")
            
            for i in range(0, len(all_vertices), 3):
                a, b, c = i + 1, i + 2, i + 3
                f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
        
        print(f"   OBJ: {obj_path}")
        print(f"   MTL: {mtl_path}")
    
    def export_gltf(self, out_dir, base_name):
        """تصدير إلى glTF مع دعم العظام"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available, skipping glTF export")
            return
        
        if len(self.vertices) == 0 or len(self.triangles) == 0:
            print("No geometry to export")
            return
        
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="HL MDL Reader (Valve spec)", version="2.0")
            
            positions = []
            for v in self.vertices:
                # تحويل Y-up إلى Z-up
                positions.extend([v.x, v.z, v.y])
            
            indices = []
            for tri in self.triangles:
                a, b, c = tri.vertindex[0], tri.vertindex[1], tri.vertindex[2]
                if a >= 0 and b >= 0 and c >= 0:
                    indices.extend([a, b, c])
            
            if len(indices) == 0:
                print("   No valid triangles to export")
                return
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(self.vertices), type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # Indices
            idx_bytes = np.array(indices, dtype=np.uint32).tobytes()
            idx_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(idx_bytes), target=34963)
            gltf.bufferViews.append(idx_bv)
            binary_data.extend(idx_bytes)
            
            idx_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                               count=len(indices), type="SCALAR")
            gltf.accessors.append(idx_acc)
            
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_name}.bin"))
            
            attributes = Attributes(POSITION=0)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            # إضافة العظام إذا وجدت
            if len(self.bones) > 0:
                # إنشاء عقد للعظام
                bone_nodes = []
                for i, bone in enumerate(self.bones):
                    # تحويل موقع العظمة
                    bx, by, bz = bone.value[0], bone.value[1], bone.value[2]
                    # تحويل Y-up إلى Z-up
                    node = Node(name=bone.name, translation=[bx, bz, by])
                    gltf.nodes.append(node)
                    bone_nodes.append(len(gltf.nodes)-1)
                
                # بناء التسلسل الهرمي
                for i, bone in enumerate(self.bones):
                    if bone.parent >= 0 and bone.parent < len(bone_nodes):
                        if gltf.nodes[bone_nodes[bone.parent]].children is None:
                            gltf.nodes[bone_nodes[bone.parent]].children = []
                        gltf.nodes[bone_nodes[bone.parent]].children.append(bone_nodes[i])
                
                # إنشاء Skin
                skin = Skin(joints=bone_nodes)
                gltf.skins.append(skin)
                
                # ربط الـ skin بالـ mesh
                node = Node(mesh=0, skin=len(gltf.skins)-1)
                gltf.nodes.append(node)
                scene = Scene(nodes=[len(gltf.nodes)-1])
            else:
                node = Node(mesh=0)
                gltf.nodes.append(node)
                scene = Scene(nodes=[0])
            
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            gltf.save(f"{out_dir}/{base_name}.gltf")
            
            with open(f"{out_dir}/{base_name}.bin", 'wb') as f:
                f.write(binary_data)
            
            print(f"   glTF: {out_dir}/{base_name}.gltf")
            print(f"   glTF binary: {out_dir}/{base_name}.bin")
            if len(self.bones) > 0:
                print(f"   Bones exported: {len(self.bones)}")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
    
    def export_json(self, out_dir, base_name):
        """تصدير بيانات النموذج إلى JSON"""
        data = {
            "header": {
                "name": self.header.name,
                "version": self.header.version,
                "flags": self.header.flags,
                "numbones": self.header.numbones,
                "numtextures": self.header.numtextures,
                "numbodyparts": self.header.numbodyparts,
                "numseq": self.header.numseq
            },
            "bones": [{"name": b.name, "parent": b.parent} for b in self.bones],
            "bodyparts": [{"name": bp.name, "nummodels": bp.nummodels} for bp in self.bodyparts],
            "num_vertices": len(self.vertices),
            "num_triangles": len(self.triangles)
        }
        
        data = convert_to_json_serializable(data)
        json_path = os.path.join(out_dir, f"{base_name}.json")
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        print(f"   JSON: {json_path}")
    
    def export_txt(self, out_dir, base_name):
        """تصدير معلومات النموذج إلى ملف نصي"""
        txt_path = os.path.join(out_dir, f"{base_name}_info.txt")
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write("# Half-Life MDL Model Info (Valve specification)\n")
            f.write(f"File: {self.header.name}\n")
            f.write(f"Version: {self.header.version}\n")
            f.write(f"Flags: {self.header.flags}\n\n")
            
            f.write("Bounding Box:\n")
            f.write(f"  Min: ({self.header.min_corner[0]:.2f}, {self.header.min_corner[1]:.2f}, {self.header.min_corner[2]:.2f})\n")
            f.write(f"  Max: ({self.header.max_corner[0]:.2f}, {self.header.max_corner[1]:.2f}, {self.header.max_corner[2]:.2f})\n\n")
            
            f.write(f"Bones ({len(self.bones)}):\n")
            for i, bone in enumerate(self.bones):
                f.write(f"  {i}: {bone.name} (parent: {bone.parent})\n")
            f.write("\n")
            
            f.write(f"Bodyparts ({len(self.bodyparts)}):\n")
            for bp in self.bodyparts:
                f.write(f"  {bp.name}: {bp.nummodels} models\n")
            f.write("\n")
            
            f.write(f"Geometry:\n")
            f.write(f"  Vertices: {len(self.vertices)}\n")
            f.write(f"  Triangles: {len(self.triangles)}\n")
        
        print(f"   TXT: {txt_path}")
    
    def export_all(self, out_dir, export_formats=None):
        """تصدير كل شيء"""
        if export_formats is None:
            export_formats = ["obj"]
        
        base_name = os.path.basename(out_dir)
        self.ensure_dir(out_dir)
        
        # استخراج القوام المدمجة
        self.extract_textures(out_dir)
        
        print(f"\nExporting MDL to {out_dir}")
        print("-" * 50)
        
        # تشخيص
        self.debug_print_geometry()
        
        if "obj" in export_formats:
            # جرب الطريقة التشخيصية أولاً
            self.export_obj_as_points(out_dir, base_name)
            # ثم الطريقة العادية
            self.export_obj(out_dir, base_name)
        
        if "gltf" in export_formats and GLTF_AVAILABLE:
            self.export_gltf(out_dir, base_name)
        
        if "json" in export_formats:
            self.export_json(out_dir, base_name)
        
        if "txt" in export_formats:
            self.export_txt(out_dir, base_name)
        
        print("-" * 50)
        print("Export completed successfully!")
    
    def ensure_dir(self, path):
        Path(path).mkdir(parents=True, exist_ok=True)

class MdlModel:
    def __init__(self, buffer: Buffer):
        self.buffer = buffer
        self.header: MDLHeader = None
        self.bones: List[MDLBone] = []
        self.textures: List[MDLTexture] = []
        self.bodyparts: List[MDLBodyPart] = []
        self.models: List[MDLModel] = []
        self.meshes: List[MDLMesh] = []
        self.vertices: List[MDLVertex] = []
        self.triangles: List[MDLTriangle] = []
        
        self._parse_header()
        self._parse_bones()
        self._parse_textures()
        self._parse_bodyparts()
        self._parse_vertices_and_triangles()
        
    def _parse_header(self):
        """قراءة رأس الملف"""
        self.header = MDLHeader.from_buffer(self.buffer)
        print(f"MDL Header: {self.header.name}")
        print(f"  Version: {self.header.version}")
        print(f"  Bones: {self.header.num_bones}")
        print(f"  Bodyparts: {self.header.num_bodyparts}")
        print(f"  Textures: {self.header.num_textures}")
        print(f"  Sequences: {self.header.num_seq}")
        
    def _parse_bones(self):
        """قراءة العظام"""
        if self.header.num_bones == 0 or self.header.bone_offset == 0:
            return
        
        self.buffer.offset = self.header.bone_offset
        for i in range(self.header.num_bones):
            bone = MDLBone.from_buffer(self.buffer)
            self.bones.append(bone)
        print(f"  Parsed {len(self.bones)} bones")
        
    def _parse_textures(self):
        """قراءة القوام"""
        if self.header.num_textures == 0 or self.header.texture_offset == 0:
            return
        
        self.buffer.offset = self.header.texture_offset
        for i in range(self.header.num_textures):
            texture = MDLTexture.from_buffer(self.buffer)
            self.textures.append(texture)
        print(f"  Parsed {len(self.textures)} textures")
        
    def _parse_bodyparts(self):
        """قراءة أجزاء الجسم والنماذج والشبكات"""
        if self.header.num_bodyparts == 0 or self.header.bodypart_offset == 0:
            return
        
        self.buffer.offset = self.header.bodypart_offset
        
        for bp_idx in range(self.header.num_bodyparts):
            bodypart = MDLBodyPart.from_buffer(self.buffer)
            self.bodyparts.append(bodypart)
            
            # قراءة النماذج في هذا الجزء
            if bodypart.num_models > 0:
                current_offset = self.buffer.offset
                self.buffer.offset = bodypart.model_offset
                
                for m_idx in range(bodypart.num_models):
                    model = MDLModel.from_buffer(self.buffer)
                    self.models.append(model)
                    
                    # قراءة الشبكات في هذا النموذج
                    if model.num_meshes > 0:
                        mesh_offset_backup = self.buffer.offset
                        self.buffer.offset = model.mesh_offset
                        
                        for mesh_idx in range(model.num_meshes):
                            mesh = MDLMesh.from_buffer(self.buffer)
                            self.meshes.append(mesh)
                        
                        self.buffer.offset = mesh_offset_backup
                
                self.buffer.offset = current_offset
        
        print(f"  Parsed {len(self.bodyparts)} bodyparts, {len(self.models)} models, {len(self.meshes)} meshes")
        
    def _parse_vertices_and_triangles(self):
        """قراءة الرؤوس والمثلثات من جميع النماذج"""
        for model in self.models:
            if model.num_verts == 0:
                continue
            
            # قراءة الرؤوس
            self.buffer.offset = model.vert_offset
            for v_idx in range(model.num_verts):
                vertex = MDLVertex.from_buffer(self.buffer)
                self.vertices.append(vertex)
            
            # قراءة المثلثات
            for mesh in self.meshes:
                if mesh.num_tris == 0:
                    continue
                
                self.buffer.offset = mesh.tri_offset
                for t_idx in range(mesh.num_tris):
                    tri = MDLTriangle.from_buffer(self.buffer)
                    self.triangles.append(tri)
        
        print(f"  Parsed {len(self.vertices)} vertices, {len(self.triangles)} triangles")
    
    # ========== دوال التصدير ==========
    def ensure_dir(self, path):
        Path(path).mkdir(parents=True, exist_ok=True)
    
    def export_obj(self, out_dir, base_name, export_formats=None):
        """تصدير النموذج إلى OBJ"""
        if export_formats is None:
            export_formats = ["obj"]
        
        if len(self.vertices) == 0 or len(self.triangles) == 0:
            print("No vertices or triangles to export")
            return
        
        # تحويل الرؤوس إلى صيغة موحدة
        dtype_out = np.dtype([
            ("px", np.float32), ("py", np.float32), ("pz", np.float32),
            ("nx", np.float32), ("ny", np.float32), ("nz", np.float32),
            ("u", np.float32), ("v", np.float32)
        ])
        
        # تطبيق تحويل المحاور (Half-Life تستخدم Y-up، نحول إلى Z-up)
        verts_arr = []
        for v in self.vertices:
            # تحويل: Y-up -> Z-up (نبدل Y و Z)
            verts_arr.append((
                v.x,      # X
                v.z,      # Z (كان Y)
                v.y,      # Y (كان Z)
                0, 0, 0,  # Normals (مؤقتة)
                v.u, 1.0 - v.v  # UV (نقلب V)
            ))
        
        vertices_transformed = np.array(verts_arr, dtype=dtype_out)
        
        # تجميع المثلثات
        faces_arr = []
        for tri in self.triangles:
            faces_arr.append([tri.indices[0], tri.indices[1], tri.indices[2]])
        faces_array = np.array(faces_arr)
        
        if "obj" in export_formats:
            obj_path = os.path.join(out_dir, f"{base_name}.obj")
            mtl_path = os.path.join(out_dir, f"{base_name}.mtl")
            
            # كتابة ملف MTL
            with open(mtl_path, "w", encoding="utf-8") as f:
                f.write(f"newmtl {base_name}_material\n")
                f.write("Ns 10.0000\n")
                f.write("Ka 1.0000 1.0000 1.0000\n")
                f.write("Kd 1.0000 1.0000 1.0000\n")
                f.write("Ks 0.0000 0.0000 0.0000\n")
                if self.textures:
                    tex_name = self.textures[0].name
                    if not tex_name.endswith('.bmp') and not tex_name.endswith('.png'):
                        tex_name += ".bmp"
                    f.write(f"map_Kd {tex_name}\n")
            
            # كتابة ملف OBJ
            with open(obj_path, "w", encoding="utf-8") as f:
                f.write(f"mtllib {base_name}.mtl\n")
                f.write(f"o {base_name}\n")
                
                # كتابة الرؤوس
                for v in vertices_transformed:
                    f.write(f"v {v['px']:.6f} {v['py']:.6f} {v['pz']:.6f}\n")
                
                # كتابة إحداثيات النسيج
                for v in vertices_transformed:
                    f.write(f"vt {v['u']:.6f} {v['v']:.6f}\n")
                
                f.write(f"usemtl {base_name}_material\n")
                
                # كتابة الوجوه
                for face in faces_array:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a} {b}/{b} {c}/{c}\n")
            
            print(f"   OBJ: {obj_path}")
            print(f"   MTL: {mtl_path}")
        
        # تصدير glTF
        if "gltf" in export_formats and GLTF_AVAILABLE:
            self._export_gltf(out_dir, base_name, vertices_transformed, faces_array)
        
        # تصدير DAE
        if "dae" in export_formats:
            self._export_collada(out_dir, base_name, vertices_transformed, faces_array)
        
        # تصدير JSON
        if "json" in export_formats:
            self._export_json(out_dir, base_name)
        
        # تصدير TXT
        if "txt" in export_formats:
            self._export_txt(out_dir, base_name)
    
    def _export_gltf(self, out_dir, base_name, vertices, faces):
        """تصدير إلى glTF"""
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="HL MDL Exporter", version="2.0")
            
            positions = []
            uvs = []
            for v in vertices:
                positions.extend([v['px'], v['py'], v['pz']])
                uvs.extend([v['u'], v['v']])
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(vertices), type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # UVs
            uv_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                              count=len(vertices), type="VEC2")
            gltf.accessors.append(uv_acc)
            
            # Indices
            indices_list = []
            for face in faces:
                indices_list.extend([face[0], face[1], face[2]])
            
            indices_bytes = np.array(indices_list, dtype=np.uint32).tobytes()
            indices_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(indices_bytes), target=34963)
            gltf.bufferViews.append(indices_bv)
            binary_data.extend(indices_bytes)
            
            indices_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                                   count=len(indices_list), type="SCALAR")
            gltf.accessors.append(indices_acc)
            
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_name}.bin"))
            
            attributes = Attributes(POSITION=0, TEXCOORD_0=1)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            node = Node(mesh=0)
            gltf.nodes.append(node)
            scene = Scene(nodes=[0])
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            gltf.save(f"{out_dir}/{base_name}.gltf")
            
            with open(f"{out_dir}/{base_name}.bin", 'wb') as f:
                f.write(binary_data)
            
            print(f"   glTF: {out_dir}/{base_name}.gltf")
            print(f"   glTF binary: {out_dir}/{base_name}.bin")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
    
    def _export_collada(self, out_dir, base_name, vertices, faces):
        """تصدير إلى Collada DAE"""
        try:
            root = ET.Element("COLLADA", xmlns="http://www.collada.org/2005/11/COLLADASchema", version="1.4.1")
            
            asset = ET.SubElement(root, "asset")
            contrib = ET.SubElement(asset, "contributor")
            ET.SubElement(contrib, "authoring_tool").text = "HL MDL Exporter"
            ET.SubElement(asset, "created").text = datetime.now().isoformat()
            ET.SubElement(asset, "modified").text = datetime.now().isoformat()
            ET.SubElement(asset, "unit", name="meter", meter="1")
            ET.SubElement(asset, "up_axis").text = "Y_UP"
            
            lib_geo = ET.SubElement(root, "library_geometries")
            geometry = ET.SubElement(lib_geo, "geometry", id=f"{base_name}-mesh", name=base_name)
            mesh = ET.SubElement(geometry, "mesh")
            
            source_pos = ET.SubElement(mesh, "source", id=f"{base_name}-mesh-positions")
            float_array_pos = ET.SubElement(source_pos, "float_array", id=f"{base_name}-mesh-positions-array",
                                           count=str(len(vertices) * 3))
            pos_str = " ".join([f"{v['px']} {v['py']} {v['pz']}" for v in vertices])
            float_array_pos.text = pos_str
            technique_common_pos = ET.SubElement(source_pos, "technique_common")
            accessor_pos = ET.SubElement(technique_common_pos, "accessor",
                                        source=f"#{base_name}-mesh-positions-array",
                                        count=str(len(vertices)), stride="3")
            ET.SubElement(accessor_pos, "param", name="X", type="float")
            ET.SubElement(accessor_pos, "param", name="Y", type="float")
            ET.SubElement(accessor_pos, "param", name="Z", type="float")
            
            source_uv = ET.SubElement(mesh, "source", id=f"{base_name}-mesh-uvs")
            float_array_uv = ET.SubElement(source_uv, "float_array", id=f"{base_name}-mesh-uvs-array",
                                          count=str(len(vertices) * 2))
            uv_str = " ".join([f"{v['u']} {1.0 - v['v']}" for v in vertices])
            float_array_uv.text = uv_str
            technique_common_uv = ET.SubElement(source_uv, "technique_common")
            accessor_uv = ET.SubElement(technique_common_uv, "accessor",
                                       source=f"#{base_name}-mesh-uvs-array",
                                       count=str(len(vertices)), stride="2")
            ET.SubElement(accessor_uv, "param", name="S", type="float")
            ET.SubElement(accessor_uv, "param", name="T", type="float")
            
            vertices_elem = ET.SubElement(mesh, "vertices", id=f"{base_name}-mesh-vertices")
            ET.SubElement(vertices_elem, "input", semantic="POSITION", source=f"#{base_name}-mesh-positions")
            
            triangles = ET.SubElement(mesh, "triangles", count=str(len(faces)))
            ET.SubElement(triangles, "input", semantic="VERTEX", source=f"#{base_name}-mesh-vertices", offset="0")
            ET.SubElement(triangles, "input", semantic="TEXCOORD", source=f"#{base_name}-mesh-uvs", offset="1")
            
            p = ET.SubElement(triangles, "p")
            indices = []
            for face in faces:
                a, b, c = face[0], face[1], face[2]
                indices.extend([a, a, b, b, c, c])
            p.text = " ".join(str(i) for i in indices)
            
            lib_vis = ET.SubElement(root, "library_visual_scenes")
            vis_scene = ET.SubElement(lib_vis, "visual_scene", id="Scene", name="Scene")
            node = ET.SubElement(vis_scene, "node", id=base_name, name=base_name)
            ET.SubElement(node, "instance_geometry", url=f"#{base_name}-mesh")
            
            scene = ET.SubElement(root, "scene")
            ET.SubElement(scene, "instance_visual_scene", url="#Scene")
            
            xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
            dae_path = os.path.join(out_dir, f"{base_name}.dae")
            with open(dae_path, 'w', encoding='utf-8') as f:
                f.write(xml_str)
            
            print(f"   DAE: {dae_path}")
            
        except Exception as e:
            print(f"   Error exporting Collada: {e}")
    
    def _export_json(self, out_dir, base_name):
        """تصدير بيانات النموذج إلى JSON"""
        data = {
            "header": {
                "name": self.header.name,
                "version": self.header.version,
                "checksum": self.header.checksum,
                "num_bones": self.header.num_bones,
                "num_textures": self.header.num_textures,
                "num_bodyparts": self.header.num_bodyparts,
                "num_seq": self.header.num_seq
            },
            "bones": [{"name": b.name, "parent": b.parent} for b in self.bones],
            "textures": [{"name": t.name, "width": t.width, "height": t.height} for t in self.textures],
            "bodyparts": [{"name": bp.name, "num_models": bp.num_models} for bp in self.bodyparts],
            "num_vertices": len(self.vertices),
            "num_triangles": len(self.triangles)
        }
        
        data = convert_to_json_serializable(data)
        json_path = os.path.join(out_dir, f"{base_name}.json")
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        print(f"   JSON: {json_path}")
    
    def _export_txt(self, out_dir, base_name):
        """تصدير معلومات النموذج إلى ملف نصي"""
        txt_path = os.path.join(out_dir, f"{base_name}_info.txt")
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write("# Half-Life MDL Model Info\n")
            f.write(f"File: {self.header.name}\n")
            f.write(f"Version: {self.header.version}\n")
            f.write(f"Checksum: {self.header.checksum}\n\n")
            
            f.write("Bounding Box:\n")
            f.write(f"  Min: ({self.header.min[0]:.2f}, {self.header.min[1]:.2f}, {self.header.min[2]:.2f})\n")
            f.write(f"  Max: ({self.header.max[0]:.2f}, {self.header.max[1]:.2f}, {self.header.max[2]:.2f})\n\n")
            
            f.write(f"Bones ({len(self.bones)}):\n")
            for i, bone in enumerate(self.bones):
                f.write(f"  {i}: {bone.name} (parent: {bone.parent})\n")
            f.write("\n")
            
            f.write(f"Textures ({len(self.textures)}):\n")
            for tex in self.textures:
                f.write(f"  {tex.name}: {tex.width}x{tex.height}\n")
            f.write("\n")
            
            f.write(f"Bodyparts ({len(self.bodyparts)}):\n")
            for bp in self.bodyparts:
                f.write(f"  {bp.name}: {bp.num_models} models\n")
            f.write("\n")
            
            f.write(f"Geometry:\n")
            f.write(f"  Vertices: {len(self.vertices)}\n")
            f.write(f"  Triangles: {len(self.triangles)}\n")
        
        print(f"   TXT: {txt_path}")
    
    def export_all(self, out_dir, export_formats=None):
        """تصدير كل شيء"""
        if export_formats is None:
            export_formats = ["obj"]
        
        base_name = os.path.splitext(os.path.basename(out_dir))[0]
        if not base_name:
            base_name = "model"
        
        self.ensure_dir(out_dir)
        
        print(f"\nExporting MDL to {out_dir}")
        print("-" * 50)
        
        self.export_obj(out_dir, base_name, export_formats)
        
        print("-" * 50)
        print("Export completed successfully!")


# ========== Functions ==========