"""
formats/mef_base.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class ChunkHeader:
    def __init__(self, ident: bytes, data_size: int, align: int, offset: int):
        self.ident = ident
        self.data_size = data_size
        self.align = align
        self.offset = offset

class Chunk:
    def __init__(self, header: ChunkHeader, buffer: Buffer):
        self.header = header
        self.buffer = buffer
        self.data = buffer.data  # ✅ احتفظ بنسخة من البيانات الأصلية

class LoopFile:
    def __init__(self, buffer: Buffer, flip_ident: bool = False):
        self.buffer = buffer
        self.flip_ident = flip_ident
        self.chunks = []
        self.index = 0
        self._parse_header()

    def _parse_header(self):
        signature = self.buffer.read(4)
        if signature != b'ILFF':
            raise ValueError(f"Not an ILFF file: {signature}")
        self.file_size = self.buffer.read_uint32()
        align = self.buffer.read_uint32()
        offset = self.buffer.read_uint32()
        formatsig = self.buffer.read(4)
        if formatsig != b'OCEM':
            raise ValueError(f"Expected OCEM, got {formatsig}")
        
        chunk_count = 0
        while not self.buffer.eof():
            ident = self.buffer.read(4)
            data_size = self.buffer.read_uint32()
            chunk_align = self.buffer.read_uint32()
            chunk_offset = self.buffer.read_uint32()
            header = ChunkHeader(ident, data_size, chunk_align, chunk_offset)
            
            # ✅ تحقق من أن data_size معقول
            if data_size > self.buffer.size():
                print(f"   WARNING: Chunk {ident} claims size {data_size} but only {self.buffer.size()} bytes left")
                break
                
            data = self.buffer.read(data_size)
            print(f"   DEBUG: Read chunk {ident} with {len(data)} bytes")  # ✅ طباعة تشخيصية
            
            self.buffer.align(4)
            chunk_buffer = Buffer(data)
            self.chunks.append(Chunk(header, chunk_buffer))
            chunk_count += 1
        
        print(f"Found {chunk_count} chunks in file")

    def next_chunk(self) -> Chunk:
        if self.index >= len(self.chunks):
            return None
        chunk = self.chunks[self.index]
        self.index += 1
        if self.flip_ident:
            chunk.header.ident = chunk.header.ident[::-1]
        return chunk

    def expect_chunk(self, ident: str) -> Chunk:
        ident_bytes = ident.encode('ascii')
        if self.flip_ident:
            ident_bytes = ident_bytes[::-1]
        for i in range(self.index, len(self.chunks)):
            if self.chunks[i].header.ident == ident_bytes:
                chunk = self.chunks[i]
                self.index = i + 1
                return chunk
        raise ValueError(f"Expected chunk {ident} not found")

    def has_chunk(self, ident: str) -> bool:
        ident_bytes = ident.encode('ascii')
        if self.flip_ident:
            ident_bytes = ident_bytes[::-1]
        for i in range(self.index, len(self.chunks)):
            if self.chunks[i].header.ident == ident_bytes:
                return True
        return False

    def print_all_chunks(self):
        print("\nAll chunks in file:")
        for i, chunk in enumerate(self.chunks):
            ident = chunk.header.ident
            if self.flip_ident:
                ident = ident[::-1]
            try:
                ident_str = ident.decode('ascii')
            except:
                ident_str = str(ident)
            print(f"  [{i}] {ident_str}: size={chunk.header.data_size}")

    def __bool__(self):
        return self.index < len(self.chunks)


# ========== Functions ==========