"""
formats/obj_parser.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class OBJVertex:
    """رأس في OBJ (v)"""
    x: float
    y: float
    z: float

class OBJTextureVertex:
    """إحداثيات نسيج في OBJ (vt)"""
    u: float
    v: float
    w: float = 0.0  # اختياري للـ 3D textures

class OBJNormal:
    """طبيعية في OBJ (vn)"""
    x: float
    y: float
    z: float

class OBJFace:
    """وجه في OBJ (f) - يدعم جميع التنسيقات"""
    # يمكن أن تكون المؤشرات بأشكال متعددة:
    # v, v/vt, v/vt/vn, v//vn
    vertex_indices: List[int] = field(default_factory=list)
    texture_indices: List[int] = field(default_factory=list)
    normal_indices: List[int] = field(default_factory=list)
    material_name: str = "default"

class OBJMaterial:
    """مادة في OBJ (ملف MTL)"""
    name: str
    ambient: Tuple[float, float, float] = (1.0, 1.0, 1.0)
    diffuse: Tuple[float, float, float] = (1.0, 1.0, 1.0)
    specular: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    emissive: Tuple[float, float, float] = (0.0, 0.0, 0.0)
    shininess: float = 10.0
    transparency: float = 1.0
    diffuse_texture: str = ""
    bump_texture: str = ""
    specular_texture: str = ""
    alpha_texture: str = ""

class OBJObject:
    """كائن (مجموعة) في OBJ (o أو g)"""
    name: str
    material_name: str = "default"
    vertices: List[OBJVertex] = field(default_factory=list)
    texture_vertices: List[OBJTextureVertex] = field(default_factory=list)
    normals: List[OBJNormal] = field(default_factory=list)
    faces: List[OBJFace] = field(default_factory=list)
    smoothing_groups: Dict[int, List[OBJFace]] = field(default_factory=dict)

class OBJExporter:
    """
    قارئ ومصدر لملفات OBJ (Wavefront)
    يدعم:
    - جميع أنواع الرؤوس (v, vt, vn, vp)
    - جميع تنسيقات الوجوه (f v, f v/vt, f v/vt/vn, f v//vn)
    - مجموعات الكائنات (o, g)
    - المواد (ملفات MTL)
    - مجموعات التنعيم (s)
    - القطع (l, p, usemtl, mtllib)
    """
    
    def __init__(self):
        self.objects: List[OBJObject] = []
        self.materials: Dict[str, OBJMaterial] = {}
        self.material_libs: List[str] = []
        self.current_object: OBJObject = None
        self.current_material: str = "default"
        self.current_smoothing: int = 0
        
        # بيانات عامة للتحليل
        self._all_vertices: List[OBJVertex] = []
        self._all_texture_vertices: List[OBJTextureVertex] = []
        self._all_normals: List[OBJNormal] = []
        
    @classmethod
    def from_file(cls, filepath: str, mtl_search_paths: List[str] = None) -> 'OBJExporter':
        """قراءة ملف OBJ من القرص مع دعم ملفات MTL"""
        exporter = cls()
        
        if mtl_search_paths is None:
            mtl_search_paths = [os.path.dirname(filepath), os.getcwd()]
        
        # قراءة ملف OBJ
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        
        exporter.parse_obj_content(content, filepath, mtl_search_paths)
        return exporter
    
    @classmethod
    def from_string(cls, content: str, base_path: str = "", mtl_search_paths: List[str] = None) -> 'OBJExporter':
        """قراءة OBJ من نص"""
        exporter = cls()
        if mtl_search_paths is None:
            mtl_search_paths = [os.getcwd()]
        exporter.parse_obj_content(content, base_path, mtl_search_paths)
        return exporter
    
    def parse_obj_content(self, content: str, base_path: str, mtl_search_paths: List[str]):
        """تحليل محتوى ملف OBJ"""
        lines = content.strip().split('\n')
        
        for line in lines:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            parts = line.split()
            cmd = parts[0].lower()
            
            if cmd == 'v':  # رأس
                self._parse_vertex(parts)
            elif cmd == 'vt':  # إحداثيات نسيج
                self._parse_texture_vertex(parts)
            elif cmd == 'vn':  # طبيعية
                self._parse_normal(parts)
            elif cmd == 'vp':  # رأس معلمي (نتخطى)
                pass
            elif cmd == 'f':  # وجه
                self._parse_face(parts)
            elif cmd == 'o':  # كائن جديد
                self._new_object(parts[1] if len(parts) > 1 else f"object_{len(self.objects)}")
            elif cmd == 'g':  # مجموعة (نفس o)
                if len(parts) > 1:
                    self._new_object(parts[1])
            elif cmd == 'usemtl':  # استخدام مادة
                if len(parts) > 1:
                    self.current_material = parts[1]
                    if self.current_object:
                        self.current_object.material_name = self.current_material
            elif cmd == 'mtllib':  # مكتبة مواد
                if len(parts) > 1:
                    mtl_file = parts[1]
                    self.material_libs.append(mtl_file)
                    self._load_mtl_file(mtl_file, base_path, mtl_search_paths)
            elif cmd == 's':  # مجموعة تنعيم
                if len(parts) > 1:
                    try:
                        self.current_smoothing = int(parts[1])
                    except:
                        self.current_smoothing = 0 if parts[1] == 'off' else 0
            elif cmd == 'l':  # خط (نتخطى)
                pass
            elif cmd == 'p':  # نقطة (نتخطى)
                pass
        
        # ✅ إنشاء كائن افتراضي إذا لم يكن هناك كائنات
        if not self.objects and (self._all_vertices or self._all_texture_vertices or self._all_normals):
            self._new_object("default")
        
        print(f"   OBJ Parsed: {len(self.objects)} objects, {len(self._all_vertices)} vertices, "
              f"{len(self._all_texture_vertices)} UVs, {len(self._all_normals)} normals, "
              f"{len(self.materials)} materials")
              
    def _new_object(self, name: str):
        """إنشاء كائن جديد"""
        obj = OBJObject(
            name=name,
            material_name=self.current_material,
            vertices=[],
            texture_vertices=[],
            normals=[],
            faces=[],
            smoothing_groups={}
        )
        self.objects.append(obj)
        self.current_object = obj
    
    def _parse_vertex(self, parts: List[str]):
        """تحليل رأس (v x y z [w])"""
        x = float(parts[1])
        y = float(parts[2])
        z = float(parts[3]) if len(parts) > 3 else 0.0
        
        vertex = OBJVertex(x, y, z)
        self._all_vertices.append(vertex)
        if self.current_object:
            self.current_object.vertices.append(vertex)
    
    def _parse_texture_vertex(self, parts: List[str]):
        """تحليل إحداثيات نسيج (vt u [v [w]])"""
        u = float(parts[1])
        v = float(parts[2]) if len(parts) > 2 else 0.0
        w = float(parts[3]) if len(parts) > 3 else 0.0
        
        tex_vert = OBJTextureVertex(u, v, w)
        self._all_texture_vertices.append(tex_vert)
        if self.current_object:
            self.current_object.texture_vertices.append(tex_vert)
    
    def _parse_normal(self, parts: List[str]):
        """تحليل طبيعية (vn x y z)"""
        x = float(parts[1])
        y = float(parts[2])
        z = float(parts[3]) if len(parts) > 3 else 0.0
        
        normal = OBJNormal(x, y, z)
        self._all_normals.append(normal)
        if self.current_object:
            self.current_object.normals.append(normal)
    
    def _parse_face(self, parts: List[str]):
        """
        تحليل وجه (f v1 v2 v3 ...)
        يدعم التنسيقات:
        - f v1 v2 v3
        - f v1/vt1 v2/vt2 v3/vt3
        - f v1/vt1/vn1 v2/vt2/vn2 v3/vt3/vn3
        - f v1//vn1 v2//vn2 v3//vn3
        """
        # ✅ التصحيح: إنشاء كائن افتراضي إذا لم يكن موجوداً
        if self.current_object is None:
            self._new_object("default")
        
        face = OBJFace(material_name=self.current_material)
        
        for i in range(1, len(parts)):
            token = parts[i]
            
            if '/' in token:
                # تنسيق مع مؤشرات إضافية
                indices = token.split('/')
                v_idx = int(indices[0]) if indices[0] else 0
                vt_idx = int(indices[1]) if len(indices) > 1 and indices[1] else 0
                vn_idx = int(indices[2]) if len(indices) > 2 and indices[2] else 0
                
                face.vertex_indices.append(v_idx)
                face.texture_indices.append(vt_idx)
                face.normal_indices.append(vn_idx)
            else:
                # تنسيق بسيط (فقط رؤوس)
                v_idx = int(token)
                face.vertex_indices.append(v_idx)
                # لا توجد مؤشرات نسيج أو طبيعيات
        
        if len(face.vertex_indices) >= 3:
            self.current_object.faces.append(face)
            
    def _load_mtl_file(self, mtl_filename: str, base_path: str, search_paths: List[str]):
        """تحميل ملف مواد MTL"""
        # البحث عن ملف MTL
        mtl_path = None
        for search_path in search_paths:
            candidate = os.path.join(search_path, mtl_filename)
            if os.path.exists(candidate):
                mtl_path = candidate
                break
            # جرب بدون مسار
            candidate = os.path.join(search_path, os.path.basename(mtl_filename))
            if os.path.exists(candidate):
                mtl_path = candidate
                break
        
        if not mtl_path:
            # جرب نسبة إلى ملف OBJ
            if base_path:
                candidate = os.path.join(os.path.dirname(base_path), mtl_filename)
                if os.path.exists(candidate):
                    mtl_path = candidate
        
        if not mtl_path:
            print(f"   Warning: MTL file not found: {mtl_filename}")
            return
        
        try:
            with open(mtl_path, 'r', encoding='utf-8', errors='ignore') as f:
                self._parse_mtl_content(f.read())
        except Exception as e:
            print(f"   Warning: Could not read MTL file {mtl_filename}: {e}")
    
    def _parse_mtl_content(self, content: str):
        """تحليل محتوى ملف MTL"""
        lines = content.strip().split('\n')
        current_material = None
        
        for line in lines:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            parts = line.split()
            cmd = parts[0].lower()
            
            if cmd == 'newmtl':
                if len(parts) > 1:
                    current_material = OBJMaterial(name=parts[1])
                    self.materials[current_material.name] = current_material
            elif current_material:
                if cmd == 'ka':  # Ambient
                    vals = [float(p) for p in parts[1:]]
                    current_material.ambient = tuple(vals + [1.0, 1.0, 1.0])[:3]
                elif cmd == 'kd':  # Diffuse
                    vals = [float(p) for p in parts[1:]]
                    current_material.diffuse = tuple(vals + [1.0, 1.0, 1.0])[:3]
                elif cmd == 'ks':  # Specular
                    vals = [float(p) for p in parts[1:]]
                    current_material.specular = tuple(vals + [1.0, 1.0, 1.0])[:3]
                elif cmd == 'ke':  # Emissive
                    vals = [float(p) for p in parts[1:]]
                    current_material.emissive = tuple(vals + [1.0, 1.0, 1.0])[:3]
                elif cmd == 'ns':  # Shininess
                    current_material.shininess = float(parts[1])
                elif cmd == 'd' or cmd == 'tr':  # Transparency
                    current_material.transparency = float(parts[1])
                elif cmd == 'map_kd':  # Diffuse texture
                    current_material.diffuse_texture = ' '.join(parts[1:]).strip('"')
                elif cmd == 'map_bump' or cmd == 'bump':  # Bump texture
                    current_material.bump_texture = ' '.join(parts[1:]).strip('"')
                elif cmd == 'map_ks':  # Specular texture
                    current_material.specular_texture = ' '.join(parts[1:]).strip('"')
                elif cmd == 'map_d':  # Alpha texture
                    current_material.alpha_texture = ' '.join(parts[1:]).strip('"')
        
        print(f"   Loaded {len(self.materials)} materials from MTL")
    
    # ========== دوال التحويل إلى صيغ أخرى ==========
    
    def to_unified_vertices(self, apply_swizzle: bool = True, swizzle_mode: str = "XZY") -> np.ndarray:
        """
        تحويل جميع الوجوه إلى مصفوفة رؤوس موحدة مع طبيعيات و UVs
        
        Args:
            apply_swizzle: تطبيق تحويل المحاور
            swizzle_mode: نمط التحويل (XYZ, XZY, YXZ, etc.)
        """
        vertices = []
        faces = []
        vertex_counter = 0
        
        for obj in self.objects:
            for face in obj.faces:
                face_indices = []
                for i in range(len(face.vertex_indices)):
                    v_idx = face.vertex_indices[i] - 1  # OBJ تستخدم 1-indexed
                    
                    # الحصول على الرأس
                    if 0 <= v_idx < len(self._all_vertices):
                        v = self._all_vertices[v_idx]
                        px, py, pz = v.x, v.y, v.z
                    else:
                        px, py, pz = 0, 0, 0
                    
                    # الحصول على إحداثيات النسيج
                    vt_idx = face.texture_indices[i] - 1 if i < len(face.texture_indices) else -1
                    if 0 <= vt_idx < len(self._all_texture_vertices):
                        vt = self._all_texture_vertices[vt_idx]
                        u, vt_val = vt.u, vt.v
                    else:
                        u, vt_val = 0, 0
                    
                    # الحصول على الطبيعية
                    vn_idx = face.normal_indices[i] - 1 if i < len(face.normal_indices) else -1
                    if 0 <= vn_idx < len(self._all_normals):
                        n = self._all_normals[vn_idx]
                        nx, ny, nz = n.x, n.y, n.z
                    else:
                        nx, ny, nz = 0, 0, 0
                    
                    # تطبيق تحويل المحاور إذا لزم الأمر
                    if apply_swizzle:
                        mode = swizzle_mode.upper()
                        if mode == "XZY":
                            px, py, pz = px, pz, -py
                            nx, ny, nz = nx, nz, -ny
                        elif mode == "XYZ":
                            pass
                        elif mode == "YXZ":
                            px, py, pz = py, px, pz
                            nx, ny, nz = ny, nx, nz
                        elif mode == "ZXY":
                            px, py, pz = pz, px, py
                            nx, ny, nz = nz, nx, ny
                    
                    vertices.append({
                        'px': px, 'py': py, 'pz': pz,
                        'nx': nx, 'ny': ny, 'nz': nz,
                        'u': u, 'v': vt_val,
                        'material': face.material_name
                    })
                    face_indices.append(vertex_counter)
                    vertex_counter += 1
                
                if len(face_indices) >= 3:
                    faces.append(face_indices[:3])
        
        if not vertices:
            return np.array([]), np.array([])
        
        dtype_out = np.dtype([
            ("px", np.float32), ("py", np.float32), ("pz", np.float32),
            ("nx", np.float32), ("ny", np.float32), ("nz", np.float32),
            ("u", np.float32), ("v", np.float32),
            ("material", 'U64')
        ])
        
        verts_arr = np.array([(v['px'], v['py'], v['pz'],
                               v['nx'], v['ny'], v['nz'],
                               v['u'], v['v'],
                               v['material']) for v in vertices], dtype=dtype_out)
        
        faces_arr = np.array(faces)
        
        return verts_arr, faces_arr
    
    def to_smd(self) -> SMDExporter:
        """تحويل OBJ إلى SMD (StudioMDL)"""
        smd = SMDExporter()
        
        # إنشاء عظمة افتراضية واحدة
        smd.nodes = [SMDNode(id=0, name="root", parent_id=-1)]
        
        vertices, faces = self.to_unified_vertices(apply_swizzle=True)
        
        if len(vertices) == 0:
            return smd
        
        # تجميع الرؤوس حسب المادة
        material_vertices = {}
        for i, v in enumerate(vertices):
            mat = v['material']
            if mat not in material_vertices:
                material_vertices[mat] = []
            material_vertices[mat].append((i, v))
        
        # إنشاء مثلثات SMD لكل مادة
        face_idx = 0
        for mat, verts in material_vertices.items():
            # تجميع الرؤوس المتتالية
            vert_indices = [v[0] for v in verts]
            
            # البحث عن الوجوه التي تنتمي لهذه المادة
            material_faces = []
            for face in faces:
                if all(idx in vert_indices for idx in face):
                    material_faces.append(face)
            
            for face in material_faces:
                tri_vertices = []
                tri_normals = []
                tri_uvs = []
                tri_links = []
                
                for idx in face:
                    v = vertices[idx]
                    tri_vertices.append((v['px'], v['py'], v['pz']))
                    tri_normals.append((v['nx'], v['ny'], v['nz']))
                    tri_uvs.append((v['u'], 1.0 - v['v']))
                    tri_links.append([(0, 1.0)])
                
                triangle = SMDTriangle(
                    parent_bone=0,
                    vertices=tri_vertices,
                    normals=tri_normals,
                    uvs=tri_uvs,
                    link_count=1,
                    links=tri_links
                )
                smd.triangles.append(triangle)
                face_idx += 1
        
        print(f"   Converted OBJ to SMD: {len(smd.triangles)} triangles, {len(vertices)} vertices")
        return smd
    
    def to_mdl_format(self, model_name: str = "obj_model") -> StudioHeader:
        """
        تحويل OBJ إلى هيكل مشابه لـ MDL (بقدر الإمكان)
        """
        # إنشاء Buffer فارغ مؤقت (لن نستخدمه فعلياً)
        dummy_buffer = Buffer(b'')
        header = StudioHeader(dummy_buffer)
        
        vertices, faces = self.to_unified_vertices(apply_swizzle=True)
        
        if len(vertices) == 0:
            return header
        
        # تحويل الرؤوس إلى صيغة StudioVertex
        header.vertices = []
        for v in vertices:
            header.vertices.append(StudioVertex(v['px'], v['py'], v['pz']))
        
        # تحويل الطبيعيات
        header.normals = []
        for v in vertices:
            header.normals.append(StudioNormal(v['nx'], v['ny'], v['nz']))
        
        # تحويل الوجوه إلى مثلثات MDL
        header.triangles = []
        for face in faces:
            if len(face) == 3:
                tri = StudioTriangle(
                    vertindex=[face[0], face[1], face[2]],
                    normindex=[face[0], face[1], face[2]],
                    s=0, t=0
                )
                header.triangles.append(tri)
        
        # إنشاء هيكل عظمي افتراضي
        header.bones = [StudioBone(name="root", parent=-1, flags=0, 
                                    bonecontroller=[0]*6, value=[0]*6, scale=[1]*6)]
        
        # إنشاء BodyPart افتراضي
        header.bodyparts = [StudioBodyPart(name=model_name, nummodels=1, base=0, modelindex=0)]
        
        # إنشاء Model افتراضي
        header.models = [StudioModel(name=model_name, type=0, boundingradius=1.0,
                                      nummesh=1, meshindex=0,
                                      numverts=len(vertices), vertinfoindex=0, vertindex=0,
                                      numnorms=len(vertices), norminfoindex=0, normindex=0,
                                      numgroups=0, groupindex=0)]
        
        # إنشاء Mesh افتراضي
        header.meshes = [StudioMesh(numtris=len(header.triangles), triindex=0,
                                     skinref=0, numnorms=0, normindex=0)]
        
        print(f"   Converted OBJ to MDL-like format: {len(header.vertices)} vertices, {len(header.triangles)} triangles")
        return header
    
    def export_obj(self, output_path: str):
        """تصدير OBJ مع الحفاظ على البيانات الأصلية دون تغيير"""
        # بدلاً من استخدام to_unified_vertices، اكتب البيانات مباشرة من self._all_vertices
        
        base_name = os.path.splitext(output_path)[0]
        obj_path = f"{base_name}.obj"
        mtl_path = f"{base_name}.mtl"
        
        # كتابة ملف MTL
        with open(mtl_path, 'w', encoding='utf-8') as f:
            for name, mat in self.materials.items():
                f.write(f"newmtl {mat.name}\n")
                f.write(f"Ns {mat.shininess:.6f}\n")
                f.write(f"Ka {mat.ambient[0]:.6f} {mat.ambient[1]:.6f} {mat.ambient[2]:.6f}\n")
                f.write(f"Kd {mat.diffuse[0]:.6f} {mat.diffuse[1]:.6f} {mat.diffuse[2]:.6f}\n")
                f.write(f"Ks {mat.specular[0]:.6f} {mat.specular[1]:.6f} {mat.specular[2]:.6f}\n")
                if mat.diffuse_texture:
                    f.write(f"map_Kd {mat.diffuse_texture}\n")
                f.write("\n")
        
        # كتابة ملف OBJ مع الحفاظ على الترتيب الأصلي
        with open(obj_path, 'w', encoding='utf-8') as f:
            # كتابة مكتبة المواد
            if self.material_libs:
                for lib in self.material_libs:
                    f.write(f"mtllib {lib}\n")
            elif self.materials:
                f.write(f"mtllib {os.path.basename(mtl_path)}\n")
            
            # كتابة جميع الرؤوس بالترتيب الأصلي
            for v in self._all_vertices:
                f.write(f"v {v.x:.6f} {v.y:.6f} {v.z:.6f}\n")
            
            # كتابة إحداثيات النسيج بالترتيب الأصلي
            for vt in self._all_texture_vertices:
                if vt.w != 0.0:
                    f.write(f"vt {vt.u:.6f} {vt.v:.6f} {vt.w:.6f}\n")
                else:
                    f.write(f"vt {vt.u:.6f} {vt.v:.6f}\n")
            
            # كتابة الطبيعيات بالترتيب الأصلي
            for vn in self._all_normals:
                f.write(f"vn {vn.x:.6f} {vn.y:.6f} {vn.z:.6f}\n")
            
            # كتابة الكائنات والوجوه مع الحفاظ على المواد
            for obj in self.objects:
                if obj.name:
                    f.write(f"o {obj.name}\n")
                
                # كتابة usemtl إذا كانت المادة مختلفة
                current_mat = None
                for face in obj.faces:
                    if face.material_name != current_mat:
                        current_mat = face.material_name
                        f.write(f"usemtl {current_mat}\n")
                    
                    # كتابة الوجه مع الحفاظ على التنسيق الأصلي
                    f.write("f")
                    for i in range(len(face.vertex_indices)):
                        v_idx = face.vertex_indices[i]
                        vt_idx = face.texture_indices[i] if i < len(face.texture_indices) else 0
                        vn_idx = face.normal_indices[i] if i < len(face.normal_indices) else 0
                        
                        if vt_idx > 0 and vn_idx > 0:
                            f.write(f" {v_idx}/{vt_idx}/{vn_idx}")
                        elif vt_idx > 0:
                            f.write(f" {v_idx}/{vt_idx}")
                        elif vn_idx > 0:
                            f.write(f" {v_idx}//{vn_idx}")
                        else:
                            f.write(f" {v_idx}")
                    f.write("\n")
        
        print(f"   OBJ: {obj_path}")
        print(f"   MTL: {mtl_path}")
    
    def _get_original_vertices_for_gltf(self):
        """استخراج الرؤوس والوجوه من البيانات الأصلية مع الحفاظ على UVs"""
        vertices = []
        faces = []
        vertex_counter = 0
        vertex_map = {}  # لتجنب تكرار الرؤوس المتطابقة
        
        for obj in self.objects:
            for face in obj.faces:
                face_indices = []
                for i in range(len(face.vertex_indices)):
                    v_idx = face.vertex_indices[i] - 1
                    vt_idx = face.texture_indices[i] - 1 if i < len(face.texture_indices) else -1
                    vn_idx = face.normal_indices[i] - 1 if i < len(face.normal_indices) else -1
                    
                    # إنشاء مفتاح فريد للرأس (موقع + UV + طبيعية)
                    v = self._all_vertices[v_idx] if 0 <= v_idx < len(self._all_vertices) else OBJVertex(0,0,0)
                    vt = self._all_texture_vertices[vt_idx] if 0 <= vt_idx < len(self._all_texture_vertices) else OBJTextureVertex(0,0)
                    vn = self._all_normals[vn_idx] if 0 <= vn_idx < len(self._all_normals) else OBJNormal(0,0,0)
                    
                    key = (v_idx, vt_idx, vn_idx)
                    
                    if key not in vertex_map:
                        vertex_map[key] = vertex_counter
                        vertices.append({
                            'px': v.x, 'py': v.y, 'pz': v.z,
                            'nx': vn.x, 'ny': vn.y, 'nz': vn.z,
                            'u': vt.u, 'v': vt.v
                        })
                        vertex_counter += 1
                    
                    face_indices.append(vertex_map[key])
                
                if len(face_indices) == 3:
                    faces.append(face_indices)
                elif len(face_indices) > 3:
                    # تقسيم المضلع إلى مثلثات (تثليث بسيط)
                    for i in range(1, len(face_indices) - 1):
                        faces.append([face_indices[0], face_indices[i], face_indices[i+1]])
        
        return vertices, faces
        
    def export_gltf(self, output_path: str):
        """تصدير OBJ إلى glTF مع الحفاظ على البيانات الأصلية"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available, skipping glTF export")
            return
        
        # استخدم البيانات الأصلية بدلاً من تحويلها
        vertices, faces = self._get_original_vertices_for_gltf()
        
        if len(vertices) == 0:
            print("No vertices to export")
            return
        
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="OBJ Exporter (preserve UVs)", version="2.0")
            
            positions = []
            normals = []
            uvs = []
            
            for v in vertices:
                positions.extend([v['px'], v['py'], v['pz']])
                normals.extend([v['nx'], v['ny'], v['nz']])
                uvs.extend([v['u'], 1.0 - v['v']])  # Flip V for OpenGL
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(vertices), type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # Normals
            norm_bytes = np.array(normals, dtype=np.float32).tobytes()
            norm_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(norm_bytes), target=34962)
            gltf.bufferViews.append(norm_bv)
            binary_data.extend(norm_bytes)
            
            norm_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                count=len(vertices), type="VEC3")
            gltf.accessors.append(norm_acc)
            
            # UVs
            uv_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                              count=len(vertices), type="VEC2")
            gltf.accessors.append(uv_acc)
            
            # Indices
            indices_list = []
            for face in faces:
                indices_list.extend([face[0], face[1], face[2]])
            
            indices_bytes = np.array(indices_list, dtype=np.uint32).tobytes()
            indices_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(indices_bytes), target=34963)
            gltf.bufferViews.append(indices_bv)
            binary_data.extend(indices_bytes)
            
            indices_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                                   count=len(indices_list), type="SCALAR")
            gltf.accessors.append(indices_acc)
            
            base_filename = os.path.splitext(os.path.basename(output_path))[0]
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_filename}.bin"))
            
            attributes = Attributes(POSITION=0, NORMAL=1, TEXCOORD_0=2)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            node = Node(mesh=0)
            gltf.nodes.append(node)
            scene = Scene(nodes=[0])
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            gltf.save(f"{output_path}.gltf")
            with open(f"{os.path.splitext(output_path)[0]}.bin", 'wb') as f:
                f.write(binary_data)
            
            print(f"   glTF: {output_path}.gltf (UVs preserved)")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
            import traceback
            traceback.print_exc()
    
    def export_json(self, output_path: str):
        """تصدير بيانات OBJ إلى JSON"""
        vertices, faces = self.to_unified_vertices(apply_swizzle=False)
        
        data = {
            "format": "OBJ (Wavefront)",
            "objects": [],
            "materials": {name: {"diffuse": list(mat.diffuse), "diffuse_texture": mat.diffuse_texture}
                         for name, mat in self.materials.items()}
        }
        
        for obj in self.objects:
            obj_data = {
                "name": obj.name,
                "material": obj.material_name,
                "vertices_count": len(obj.vertices),
                "texture_vertices_count": len(obj.texture_vertices),
                "normals_count": len(obj.normals),
                "faces_count": len(obj.faces)
            }
            data["objects"].append(obj_data)
        
        data["total_vertices"] = len(self._all_vertices)
        data["total_texture_vertices"] = len(self._all_texture_vertices)
        data["total_normals"] = len(self._all_normals)
        data["total_faces"] = sum(len(obj.faces) for obj in self.objects)
        
        data = convert_to_json_serializable(data)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        
        print(f"   JSON: {output_path}")
    
    def export_txt(self, output_path: str):
        """تصدير معلومات OBJ إلى ملف نصي"""
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# OBJ (Wavefront) File Information\n\n")
            
            f.write("=== OBJECTS ===\n")
            for obj in self.objects:
                f.write(f"  {obj.name}: material={obj.material_name}, "
                       f"vertices={len(obj.vertices)}, UVs={len(obj.texture_vertices)}, "
                       f"normals={len(obj.normals)}, faces={len(obj.faces)}\n")
            
            f.write(f"\n=== MATERIALS ===\n")
            for name, mat in self.materials.items():
                f.write(f"  {name}: diffuse={mat.diffuse}, texture={mat.diffuse_texture}\n")
            
            f.write(f"\n=== STATISTICS ===\n")
            f.write(f"  Total vertices: {len(self._all_vertices)}\n")
            f.write(f"  Total texture vertices: {len(self._all_texture_vertices)}\n")
            f.write(f"  Total normals: {len(self._all_normals)}\n")
            f.write(f"  Total faces: {sum(len(obj.faces) for obj in self.objects)}\n")
            f.write(f"  Total objects: {len(self.objects)}\n")
            f.write(f"  Total materials: {len(self.materials)}\n")
        
        print(f"   TXT: {output_path}")
    
    def export_all(self, output_dir: str, base_name: str, export_formats: List[str] = None):
        """تصدير OBJ إلى جميع الصيغ المطلوبة مع الحفاظ على البيانات الأصلية"""
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt", "smd", "mdl"]
        
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        print(f"\nExporting OBJ to {output_dir}")
        print("-" * 50)
        
        if "obj" in export_formats:
            self.export_obj(os.path.join(output_dir, base_name))
        
        if "gltf" in export_formats:
            self.export_gltf(os.path.join(output_dir, base_name))
        
        if "json" in export_formats:
            self.export_json(os.path.join(output_dir, f"{base_name}.json"))
        
        if "txt" in export_formats:
            self.export_txt(os.path.join(output_dir, f"{base_name}_info.txt"))
        
        if "smd" in export_formats:
            # عند التصدير إلى SMD، استخدم البيانات المحولة (مع swizzle)
            vertices, faces = self.to_unified_vertices(apply_swizzle=True)
            if len(vertices) > 0:
                smd = self.to_smd()
                smd.export_all(output_dir, base_name, ["obj", "gltf", "json", "txt"])
        
        if "mdl" in export_formats:
            mdl = self.to_mdl_format(base_name)
            mdl.export_all(os.path.join(output_dir, f"{base_name}_mdl"), ["obj", "gltf", "json", "txt"])
        
        print("-" * 50)
        print("OBJ Export completed successfully!")


# ========== دوال مساعدة لمعالجة ملفات OBJ ==========

    def convert_obj_to_formats(input_obj: str, output_dir: str, export_formats: List[str] = None):
        """
        دالة مساعدة لتحويل ملف OBJ واحد إلى صيغ متعددة
        
        Args:
            input_obj: مسار ملف OBJ
            output_dir: مجلد الإخراج
            export_formats: قائمة الصيغ المطلوبة (obj, gltf, json, txt, smd, mdl)
        """
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt", "smd", "mdl"]
        
        if not os.path.exists(input_obj):
            print(f"Error: OBJ file not found: {input_obj}")
            return False
        
        try:
            print(f"\nReading OBJ file: {input_obj}")
            obj = OBJExporter.from_file(input_obj)
            
            base_name = os.path.splitext(os.path.basename(input_obj))[0]
            obj.export_all(output_dir, base_name, export_formats)
            
            return True
        except Exception as e:
            print(f"Error converting OBJ: {e}")
            import traceback
            traceback.print_exc()
            return False


    def batch_convert_obj(input_dir: str, output_dir: str, export_formats: List[str] = None):
        """
        تحويل جميع ملفات OBJ في مجلد إلى صيغ متعددة
        
        Args:
            input_dir: المجلد الذي يحتوي على ملفات OBJ
            output_dir: مجلد الإخراج
            export_formats: قائمة الصيغ المطلوبة
        """
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt", "smd", "mdl"]
        
        obj_files = []
        for ext in ['*.obj', '*.OBJ']:
            obj_files.extend(Path(input_dir).glob(ext))
        
        if not obj_files:
            print(f"No OBJ files found in '{input_dir}'")
            return False
        
        print(f"\nFound {len(obj_files)} OBJ file(s):")
        for f in obj_files:
            print(f"  - {f.name}")
        
        successful = 0
        failed = 0
        
        for obj_file in obj_files:
            print(f"\n{'='*60}")
            print(f"Processing: {obj_file.name}")
            print(f"{'='*60}")
            
            output_subdir = os.path.join(output_dir, obj_file.stem)
            
            if convert_obj_to_formats(str(obj_file), output_subdir, export_formats):
                successful += 1
                print(f"✓ Successfully processed: {obj_file.name}")
            else:
                failed += 1
                print(f"✗ Failed to process: {obj_file.name}")
        
        print("\n" + "="*60)
        print("OBJ BATCH CONVERSION COMPLETE")
        print("="*60)
        print(f"Total files found : {len(obj_files)}")
        print(f"Successfully processed : {successful}")
        print(f"Failed : {failed}")
        print(f"Output folder : {output_dir}")
        print("="*60)
        
        return successful > 0


# ========== Functions ==========