"""
formats/smd_parser.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class SMDNode:
    """عقدة في هيكل SMD (عظمة)"""
    id: int
    name: str
    parent_id: int

class SMDVertex:
    """رأس في SMD"""
    bone_id: int      # مؤشر العظمة المرتبطة
    pos: Tuple[float, float, float]
    normal: Tuple[float, float, float]
    uv: Tuple[float, float]
    link_count: int = 1  # عدد العظام المرتبطة (1-4)
    links: List[Tuple[int, float]] = field(default_factory=list)  # (bone_id, weight)

class SMDFace:
    """وجه مثلث في SMD"""
    vertices: List[SMDVertex]  # 3 رؤوس

class SMDTriangle:
    """مثلث في SMD (صيغة Crowbar)"""
    parent_bone: int
    vertices: List[Tuple[float, float, float]]  # 3 رؤوس
    normals: List[Tuple[float, float, float]]   # 3 طبيعيات
    uvs: List[Tuple[float, float]]              # 3 UVs
    link_count: int = 1
    links: List[Tuple[int, float]] = field(default_factory=list)

class SMDExporter:
    """
    مصدر نماذج SMD (StudioMDL) - صيغة Crowbar
    يمكنه قراءة SMD وتصديره إلى صيغ أخرى
    """
    
    def __init__(self):
        self.nodes: List[SMDNode] = []      # العظام
        self.triangles: List[SMDTriangle] = []  # المثلثات
        self.vertices: List[SMDVertex] = []     # الرؤوس (للتزين)
        self.animations: Dict[str, any] = {}    # الرسوم المتحركة (اختياري)
        # ✅ المتغيرات الجديدة للمواد
        self.materials: List[str] = []           # أسماء المواد (القوام)
        self.material_triangle_indices: Dict[str, List[int]] = {}  # المادة -> قائمة مؤشرات المثلثات
        self.current_material: str = None        # المادة الحالية أثناء القراءة
        
    @classmethod
    def from_file(cls, filepath: str) -> 'SMDExporter':
        """قراءة ملف SMD من قرص"""
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        return cls.from_string(content)
    
    @classmethod
    def from_string(cls, content: str) -> 'SMDExporter':
        """قراءة SMD من نص - نسخة محسنة لـ Crowbar مع حفظ المواد"""
        exporter = cls()
        lines = content.strip().split('\n')
        
        i = 0
        current_material = None  # ✅ جديد: تتبع المادة الحالية
        material_faces = {}      # ✅ جديد: تخزين الوجوه لكل مادة
        
        while i < len(lines):
            line = lines[i].strip()
            
            if line == "nodes":
                # قراءة العظام
                i += 1
                while i < len(lines):
                    line = lines[i].strip()
                    if not line:
                        i += 1
                        continue
                    if line == "end":
                        break
                    
                    parts = line.split('"')
                    if len(parts) >= 3:
                        try:
                            node_id = int(parts[0].strip())
                            node_name = parts[1].strip()
                            parent_id = int(parts[2].strip())
                            exporter.nodes.append(SMDNode(node_id, node_name, parent_id))
                        except ValueError as e:
                            print(f"   Warning: Could not parse node line: {line}")
                    i += 1
                    
            elif line == "skeleton":
                # قراءة الهيكل العظمي (للتزين) - نتخطى مؤقتاً
                i += 1
                while i < len(lines):
                    line = lines[i].strip()
                    i += 1
                    if line == "end":
                        break
                        
            elif line == "triangles":
                # قراءة المثلثات (الشبكة)
                i += 1
                while i < len(lines):
                    line = lines[i].strip()
                    if not line:
                        i += 1
                        continue
                    if line == "end":
                        break
                    
                    # ✅ التصحيح: السطر الأول هو اسم المادة (القوام)
                    current_material = line.strip()
                    i += 1
                    
                    # ✅ تخزين الوجوه لهذه المادة
                    if current_material not in material_faces:
                        material_faces[current_material] = []
                    
                    vertices = []
                    normals = []
                    uvs = []
                    links = []
                    link_count = 1
                    
                    for v in range(3):
                        if i >= len(lines):
                            break
                        vert_line = lines[i].strip()
                        i += 1
                        
                        # تحليل الرأس: parent_bone pos_x pos_y pos_z norm_x norm_y norm_z u v [link_count [bone_id weight ...]]
                        vert_parts = vert_line.split()
                        if len(vert_parts) >= 9:
                            try:
                                parent_bone = int(vert_parts[0])
                                pos = (float(vert_parts[1]), float(vert_parts[2]), float(vert_parts[3]))
                                norm = (float(vert_parts[4]), float(vert_parts[5]), float(vert_parts[6]))
                                uv = (float(vert_parts[7]), float(vert_parts[8]))
                                
                                vertices.append(pos)
                                normals.append(norm)
                                uvs.append(uv)
                                
                                # قراءة الروابط (للتزين المتعدد)
                                if len(vert_parts) > 9:
                                    lcount = int(vert_parts[9])
                                    link_count = lcount
                                    vlinks = []
                                    for l in range(lcount):
                                        idx = 10 + l * 2
                                        if idx + 1 < len(vert_parts):
                                            bone_id = int(vert_parts[idx])
                                            weight = float(vert_parts[idx + 1])
                                            vlinks.append((bone_id, weight))
                                    links.append(vlinks)
                                else:
                                    links.append([(parent_bone, 1.0)])
                            except ValueError as e:
                                print(f"   Warning: Could not parse vertex line: {vert_line}")
                                continue
                    
                    if len(vertices) == 3:
                        triangle = SMDTriangle(parent_bone, vertices, normals, uvs, link_count, links)
                        exporter.triangles.append(triangle)
                        # ✅ تخزين المادة مع المثلث
                        material_faces[current_material].append(len(exporter.triangles) - 1)
                        
            elif line == "vertexanimation":
                # قراءة رسوم متحركة للرؤوس (اختياري)
                i += 1
                while i < len(lines):
                    line = lines[i].strip()
                    i += 1
                    if line == "end":
                        break
                        
            else:
                i += 1
        
        # ✅ حفظ المواد المستخرجة في كائن SMDExporter
        exporter.materials = list(material_faces.keys())
        exporter.material_triangle_indices = material_faces
        exporter.current_material = current_material
        
        print(f"   Parsed {len(exporter.nodes)} nodes, {len(exporter.triangles)} triangles")
        print(f"   Found materials: {exporter.materials}")
        return exporter
    
    def to_vertices_array(self) -> np.ndarray:
        """
        تحويل المثلثات إلى مصفوفة رؤوس موحدة
        """
        vertices = []
        faces = []
        vertex_counter = 0
        
        for tri in self.triangles:
            face_indices = []
            for v in range(3):
                pos = tri.vertices[v]
                norm = tri.normals[v]
                uv = tri.uvs[v]
                
                # استخدام أول رابط فقط إذا كان موجوداً
                bone_id = tri.links[v][0][0] if v < len(tri.links) and tri.links[v] else 0
                weight = tri.links[v][0][1] if v < len(tri.links) and tri.links[v] else 1.0
                
                vertices.append({
                    'px': pos[0], 'py': pos[1], 'pz': pos[2],
                    'nx': norm[0], 'ny': norm[1], 'nz': norm[2],
                    'u': uv[0], 'v': uv[1],
                    'bone_id': bone_id,
                    'weight': weight
                })
                face_indices.append(vertex_counter)
                vertex_counter += 1
            
            faces.append(face_indices)
        
        dtype_out = np.dtype([
            ("px", np.float32), ("py", np.float32), ("pz", np.float32),
            ("nx", np.float32), ("ny", np.float32), ("nz", np.float32),
            ("u", np.float32), ("v", np.float32),
            ("bone_id", np.uint16), ("weight", np.float32)
        ])
        
        verts_arr = np.array([(v['px'], v['py'], v['pz'],
                               v['nx'], v['ny'], v['nz'],
                               v['u'], v['v'],
                               v['bone_id'], v['weight']) 
                              for v in vertices], dtype=dtype_out)
        
        faces_arr = np.array(faces)
        
        return verts_arr, faces_arr
    
    def to_bones_list(self) -> List[Dict]:
        """تحويل العظام إلى قائمة"""
        bones = []
        for node in self.nodes:
            bones.append({
                'id': node.id,
                'name': node.name,
                'parent_id': node.parent_id
            })
        return bones
    
    def export_obj(self, output_path: str):
        """تصدير SMD إلى OBJ مع دعم المواد المتعددة من SMD"""
        vertices, faces = self.to_vertices_array()
        
        if len(vertices) == 0:
            print("No vertices to export")
            return
        
        base_name = os.path.splitext(output_path)[0]
        obj_path = f"{base_name}.obj"
        mtl_path = f"{base_name}.mtl"
        
        # ========== إعادة بناء المواد من بيانات SMD ==========
        # إذا كانت لدينا معلومات المواد من SMD
        material_names = []
        
        if hasattr(self, 'materials') and self.materials:
            # استخدام المواد المستخرجة من SMD
            material_names = self.materials
            print(f"   Using {len(material_names)} materials from SMD: {material_names}")
        else:
            # الحالة القديمة: مادة واحدة افتراضية
            material_names = ["smd_material"]
            print(f"   No materials found in SMD, using default material")
        
        # ========== إنشاء قاموس لتعيين كل وجه إلى مادته ==========
        face_to_material = {}
        
        if hasattr(self, 'material_triangle_indices') and self.material_triangle_indices:
            # بناء تعيين من مؤشر الوجه إلى اسم المادة
            for mat_name, tri_indices in self.material_triangle_indices.items():
                for tri_idx in tri_indices:
                    face_to_material[tri_idx] = mat_name
            print(f"   Mapped {len(face_to_material)} faces to materials")
        
        # ========== تجميع الوجوه حسب المادة ==========
        material_faces_map = {}
        for mat_name in material_names:
            material_faces_map[mat_name] = []
        
        # توزيع الوجوه على المواد
        if face_to_material:
            for face_idx, face in enumerate(faces):
                mat_name = face_to_material.get(face_idx, material_names[0])
                if mat_name not in material_faces_map:
                    material_faces_map[mat_name] = []
                material_faces_map[mat_name].append(face)
        else:
            # بدون معلومات المواد، كل الوجوه في مادة واحدة
            material_faces_map[material_names[0]] = faces
        
        # ========== كتابة ملف MTL (مواد متعددة) ==========
        with open(mtl_path, 'w', encoding='utf-8') as f:
            for mat_name in material_names:
                # تنظيف اسم المادة (إزالة المسارات وجعلها صالحة لاسم الملف)
                clean_mat_name = mat_name.replace('\\', '/').split('/')[-1]
                clean_mat_name = clean_mat_name.split('.')[0] if '.' in clean_mat_name else clean_mat_name
                clean_mat_name = clean_mat_name.replace(' ', '_').replace('-', '_')
                if not clean_mat_name:
                    clean_mat_name = f"material_{material_names.index(mat_name)}"
                
                # اسم ملف القوام
                tex_file = mat_name
                if not tex_file.endswith('.tga') and not tex_file.endswith('.png') and not tex_file.endswith('.bmp'):
                    tex_file = f"{clean_mat_name}.png"
                
                f.write(f"newmtl {clean_mat_name}\n")
                f.write("Ns 10.0000\n")
                f.write("Ka 1.0000 1.0000 1.0000\n")
                f.write("Kd 1.0000 1.0000 1.0000\n")
                f.write("Ks 0.0000 0.0000 0.0000\n")
                f.write(f"map_Kd {tex_file}\n")
                f.write("\n")
        
        # ========== كتابة ملف OBJ مع وجوه مادة تلو الأخرى ==========
        with open(obj_path, 'w', encoding='utf-8') as f:
            f.write(f"mtllib {os.path.basename(mtl_path)}\n")
            f.write(f"o {os.path.basename(base_name)}\n")
            
            # كتابة الرؤوس
            for v in vertices:
                f.write(f"v {v['px']:.6f} {v['py']:.6f} {v['pz']:.6f}\n")
            
            # كتابة إحداثيات النسيج (UV)
            for v in vertices:
                f.write(f"vt {v['u']:.6f} {1.0 - v['v']:.6f}\n")
            
            # كتابة الطبيعيات
            for v in vertices:
                f.write(f"vn {v['nx']:.6f} {v['ny']:.6f} {v['nz']:.6f}\n")
            
            # كتابة الوجوه حسب المادة
            total_faces_written = 0
            for mat_name, material_faces in material_faces_map.items():
                if not material_faces:
                    continue
                
                # تنظيف اسم المادة ليتوافق مع MTL
                clean_mat_name = mat_name.replace('\\', '/').split('/')[-1]
                clean_mat_name = clean_mat_name.split('.')[0] if '.' in clean_mat_name else clean_mat_name
                clean_mat_name = clean_mat_name.replace(' ', '_').replace('-', '_')
                if not clean_mat_name:
                    clean_mat_name = f"material_{material_names.index(mat_name)}"
                
                f.write(f"usemtl {clean_mat_name}\n")
                
                for face in material_faces:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
                    total_faces_written += 1
            
            if total_faces_written == 0:
                # Fallback: كتابة كل الوجوه بمادة واحدة
                f.write(f"usemtl smd_material\n")
                for face in faces:
                    a, b, c = face[0] + 1, face[1] + 1, face[2] + 1
                    f.write(f"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}\n")
        
        print(f"   OBJ: {obj_path} (with {len(material_names)} materials)")
        print(f"   MTL: {mtl_path}")
    
    def get_material_for_triangle(self, triangle_index: int) -> str:
        """الحصول على اسم المادة لمثلث معين"""
        if hasattr(self, 'material_triangle_indices') and self.material_triangle_indices:
            for mat_name, tri_indices in self.material_triangle_indices.items():
                if triangle_index in tri_indices:
                    return mat_name
        return "default_material"
    
    def get_materials_list(self) -> List[str]:
        """الحصول على قائمة المواد الفريدة"""
        if hasattr(self, 'materials') and self.materials:
            return self.materials
        return ["default_material"]
        
    def export_gltf(self, output_path: str):
        """تصدير SMD إلى glTF"""
        if not GLTF_AVAILABLE:
            print("   pygltflib not available, skipping glTF export")
            return
        
        vertices, faces = self.to_vertices_array()
        
        if len(vertices) == 0:
            print("No vertices to export")
            return
        
        try:
            from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
            
            gltf = GLTF2()
            gltf.asset = Asset(generator="SMD Exporter (Crowbar)", version="2.0")
            
            positions = []
            normals = []
            uvs = []
            weights = []
            joints = []
            
            for v in vertices:
                positions.extend([v['px'], v['py'], v['pz']])
                normals.extend([v['nx'], v['ny'], v['nz']])
                uvs.extend([v['u'], 1.0 - v['v']])
                weights.extend([v['weight'], 0.0, 0.0, 0.0])  # padding to 4
                joints.extend([v['bone_id'], 0, 0, 0])
            
            binary_data = bytearray()
            
            # Positions
            pos_bytes = np.array(positions, dtype=np.float32).tobytes()
            pos_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(pos_bytes), target=34962)
            gltf.bufferViews.append(pos_bv)
            binary_data.extend(pos_bytes)
            
            pos_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                               count=len(vertices), type="VEC3")
            gltf.accessors.append(pos_acc)
            
            # Normals
            norm_bytes = np.array(normals, dtype=np.float32).tobytes()
            norm_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(norm_bytes), target=34962)
            gltf.bufferViews.append(norm_bv)
            binary_data.extend(norm_bytes)
            
            norm_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                count=len(vertices), type="VEC3")
            gltf.accessors.append(norm_acc)
            
            # UVs
            uv_bytes = np.array(uvs, dtype=np.float32).tobytes()
            uv_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(uv_bytes), target=34962)
            gltf.bufferViews.append(uv_bv)
            binary_data.extend(uv_bytes)
            
            uv_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                              count=len(vertices), type="VEC2")
            gltf.accessors.append(uv_acc)
            
            # Weights
            weights_bytes = np.array(weights, dtype=np.float32).tobytes()
            weights_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(weights_bytes), target=34962)
            gltf.bufferViews.append(weights_bv)
            binary_data.extend(weights_bytes)
            
            weights_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5126,
                                   count=len(vertices), type="VEC4")
            gltf.accessors.append(weights_acc)
            
            # Joints
            joints_bytes = np.array(joints, dtype=np.uint16).tobytes()
            joints_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(joints_bytes), target=34962)
            gltf.bufferViews.append(joints_bv)
            binary_data.extend(joints_bytes)
            
            joints_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5123,
                                  count=len(vertices), type="VEC4")
            gltf.accessors.append(joints_acc)
            
            # Indices
            indices_list = []
            for face in faces:
                indices_list.extend([face[0], face[1], face[2]])
            
            indices_bytes = np.array(indices_list, dtype=np.uint32).tobytes()
            indices_bv = BufferView(buffer=0, byteOffset=len(binary_data), byteLength=len(indices_bytes), target=34963)
            gltf.bufferViews.append(indices_bv)
            binary_data.extend(indices_bytes)
            
            indices_acc = Accessor(bufferView=len(gltf.bufferViews)-1, componentType=5125,
                                   count=len(indices_list), type="SCALAR")
            gltf.accessors.append(indices_acc)
            
            # Buffer - استخدم اسم الملف الأساسي من output_path
            base_filename = os.path.splitext(os.path.basename(output_path))[0]
            gltf.buffers.append(Buffer(byteLength=len(binary_data), uri=f"{base_filename}.bin"))
            
            attributes = Attributes(POSITION=0, NORMAL=1, TEXCOORD_0=2, WEIGHTS_0=3, JOINTS_0=4)
            primitive = Primitive(attributes=attributes, indices=len(gltf.accessors)-1, material=0)
            mesh = Mesh(primitives=[primitive])
            gltf.meshes.append(mesh)
            
            # إضافة العظام إذا وجدت
            if self.nodes:
                bone_nodes = []
                for node in self.nodes:
                    gltf_node = Node(name=node.name)
                    gltf.nodes.append(gltf_node)
                    bone_nodes.append(len(gltf.nodes)-1)
                
                # بناء التسلسل الهرمي
                for i, node in enumerate(self.nodes):
                    if node.parent_id >= 0:
                        parent_idx = None
                        for j, n in enumerate(self.nodes):
                            if n.id == node.parent_id:
                                parent_idx = bone_nodes[j]
                                break
                        if parent_idx is not None:
                            if gltf.nodes[parent_idx].children is None:
                                gltf.nodes[parent_idx].children = []
                            gltf.nodes[parent_idx].children.append(bone_nodes[i])
                
                skin = Skin(joints=bone_nodes)
                gltf.skins.append(skin)
                
                node = Node(mesh=0, skin=len(gltf.skins)-1)
                gltf.nodes.append(node)
                scene = Scene(nodes=[len(gltf.nodes)-1])
            else:
                node = Node(mesh=0)
                gltf.nodes.append(node)
                scene = Scene(nodes=[0])
            
            gltf.scenes.append(scene)
            gltf.scene = 0
            
            # حفظ ملفات glTF
            gltf.save(f"{output_path}.gltf")
            with open(f"{os.path.splitext(output_path)[0]}.bin", 'wb') as f:
                f.write(binary_data)
            
            print(f"   glTF: {output_path}.gltf")
            print(f"   glTF binary: {os.path.splitext(output_path)[0]}.bin")
            
        except Exception as e:
            print(f"   Error exporting glTF: {e}")
            import traceback
            traceback.print_exc()
    
    def export_json(self, output_path: str):
        """تصدير بيانات SMD إلى JSON"""
        vertices, faces = self.to_vertices_array()
        
        data = {
            "format": "SMD (StudioMDL)",
            "nodes": [{"id": n.id, "name": n.name, "parent_id": n.parent_id} for n in self.nodes],
            "triangles_count": len(self.triangles),
            "vertices_count": len(vertices),
            "faces_count": len(faces),
            "vertices": [{"pos": [v['px'], v['py'], v['pz']],
                         "norm": [v['nx'], v['ny'], v['nz']],
                         "uv": [v['u'], v['v']],
                         "bone_id": v['bone_id'],
                         "weight": v['weight']} for v in vertices],
            "faces": [{"indices": list(f)} for f in faces]
        }
        
        data = convert_to_json_serializable(data)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2)
        
        print(f"   JSON: {output_path}")
    
    def export_txt(self, output_path: str):
        """تصدير معلومات SMD إلى ملف نصي"""
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# SMD (StudioMDL) File Information\n")
            f.write(f"# Source: Crowbar decompile\n\n")
            
            f.write("=== NODES (Bones) ===\n")
            for node in self.nodes:
                f.write(f"  {node.id}: {node.name} (parent: {node.parent_id})\n")
            
            f.write(f"\n=== TRIANGLES ===\n")
            f.write(f"Total triangles: {len(self.triangles)}\n")
            
            vertices, faces = self.to_vertices_array()
            f.write(f"\n=== GEOMETRY ===\n")
            f.write(f"Total vertices: {len(vertices)}\n")
            f.write(f"Total faces: {len(faces)}\n")
            
            if self.animations:
                f.write(f"\n=== ANIMATIONS ===\n")
                for name, anim in self.animations.items():
                    f.write(f"  {name}: {anim}\n")
        
        print(f"   TXT: {output_path}")
    
    def export_all(self, output_dir: str, base_name: str, export_formats: List[str] = None):
        """تصدير SMD إلى جميع الصيغ المطلوبة"""
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt"]
        
        self.ensure_dir(output_dir)
        
        print(f"\nExporting SMD to {output_dir}")
        print("-" * 50)
        
        if "obj" in export_formats:
            self.export_obj(os.path.join(output_dir, base_name))
        
        if "gltf" in export_formats:
            self.export_gltf(os.path.join(output_dir, base_name))
        
        if "json" in export_formats:
            self.export_json(os.path.join(output_dir, f"{base_name}.json"))
        
        if "txt" in export_formats:
            self.export_txt(os.path.join(output_dir, f"{base_name}_info.txt"))
        
        print("-" * 50)
        print("Export completed successfully!")
    
    def ensure_dir(self, path):
        Path(path).mkdir(parents=True, exist_ok=True)


    def convert_smd_to_formats(input_smd: str, output_dir: str, export_formats: List[str] = None):
        """
        دالة مساعدة لتحويل ملف SMD واحد إلى صيغ متعددة
        """
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt"]
        
        if not os.path.exists(input_smd):
            print(f"Error: SMD file not found: {input_smd}")
            return False
        
        try:
            print(f"\nReading SMD file: {input_smd}")
            smd = SMDExporter.from_file(input_smd)
            
            base_name = os.path.splitext(os.path.basename(input_smd))[0]
            smd.export_all(output_dir, base_name, export_formats)
            
            return True
        except Exception as e:
            print(f"Error converting SMD: {e}")
            import traceback
            traceback.print_exc()
            return False


    def batch_convert_smd(input_dir: str, output_dir: str, export_formats: List[str] = None):
        """
        تحويل جميع ملفات SMD في مجلد إلى صيغ متعددة
        
        Args:
            input_dir: المجلد الذي يحتوي على ملفات SMD
            output_dir: مجلد الإخراج
            export_formats: قائمة الصيغ المطلوبة
        """
        if export_formats is None:
            export_formats = ["obj", "gltf", "json", "txt"]
        
        smd_files = []
        for ext in ['*.smd', '*.SMD']:
            smd_files.extend(Path(input_dir).glob(ext))
        
        if not smd_files:
            print(f"No SMD files found in '{input_dir}'")
            return False
        
        print(f"\nFound {len(smd_files)} SMD file(s):")
        for f in smd_files:
            print(f"  - {f.name}")
        
        successful = 0
        failed = 0
        
        for smd_file in smd_files:
            print(f"\n{'='*60}")
            print(f"Processing: {smd_file.name}")
            print(f"{'='*60}")
            
            output_subdir = os.path.join(output_dir, smd_file.stem)
            
            if convert_smd_to_formats(str(smd_file), output_subdir, export_formats):
                successful += 1
                print(f"✓ Successfully processed: {smd_file.name}")
            else:
                failed += 1
                print(f"✗ Failed to process: {smd_file.name}")
        
        print("\n" + "="*60)
        print("SMD BATCH CONVERSION COMPLETE")
        print("="*60)
        print(f"Total files found : {len(smd_files)}")
        print(f"Successfully processed : {successful}")
        print(f"Failed : {failed}")
        print(f"Output folder : {output_dir}")
        print("="*60)
        
        return successful > 0


# ========== Functions ==========