"""
core/buffer.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class Buffer:
    def __init__(self, data: bytes):
        self.data = data
        self.offset = 0

    def read(self, size: int = None) -> bytes:
        if size is None:
            size = len(self.data) - self.offset
        if self.offset + size > len(self.data):
            raise ValueError(f"Buffer overflow: trying to read {size} bytes at offset {self.offset}")
        d = self.data[self.offset:self.offset+size]
        self.offset += size
        return d

    def read_uint8(self) -> int:
        return struct.unpack('<B', self.read(1))[0]

    def read_int8(self) -> int:
        return struct.unpack('<b', self.read(1))[0]

    def read_uint16(self) -> int:
        return struct.unpack('<H', self.read(2))[0]

    def read_int16(self) -> int:
        return struct.unpack('<h', self.read(2))[0]

    def read_uint32(self) -> int:
        return struct.unpack('<I', self.read(4))[0]

    def read_int32(self) -> int:
        return struct.unpack('<i', self.read(4))[0]

    def read_float(self) -> float:
        return struct.unpack('<f', self.read(4))[0]

    def read_fmt(self, fmt: str):
        size = struct.calcsize('<' + fmt)
        data = self.read(size)
        return struct.unpack('<' + fmt, data)

    def read_ascii_string(self, length: int) -> str:
        data = self.read(length)
        return data.split(b'\x00')[0].decode('ascii', errors='ignore')

    def align(self, alignment: int):
        skip = (alignment - (self.offset % alignment)) % alignment
        self.offset += skip

    def size(self) -> int:
        return len(self.data) - self.offset

    def eof(self) -> bool:
        return self.offset >= len(self.data)


# ========== Functions ==========