"""
core/types.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class Vector3:
    x: float
    y: float
    z: float

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(buffer.read_float(), buffer.read_float(), buffer.read_float())

    def to_list(self):
        return [self.x, self.y, self.z]

    def to_array(self):
        return np.array([self.x, self.y, self.z], dtype=np.float32)

class Sphere:
    pos: Vector3
    radius: float

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(Vector3.from_buffer(buffer), buffer.read_float())

class MeshInfo:
    face_count: int
    vertex_count: int
    buffer_size: int

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(buffer.read_uint32(), buffer.read_uint32(), buffer.read_uint32())

class Bone:
    name: str
    pos: Vector3
    parent_id: int

class TextureReference:
    """مرجع قوام من قطعة XTXM"""
    index: int
    name: str

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        # الصيغة تعتمد على التطبيق الفعلي، هذه صيغة تقريبية
        index = buffer.read_uint32()
        name = buffer.read_ascii_string(32)
        return cls(index, name)

class XTRWEntry:
    """مفردة وزن عظم (Vertex weight) من قطعة XTRW"""
    vertex_id: int
    bone_id: int
    weight: float

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        vertex_id = buffer.read_uint32()
        bone_id = buffer.read_uint32()
        weight = buffer.read_float()
        return cls(vertex_id, bone_id, weight)

class MefDebugParams:
    """Dynamic parameters for coordinate and scale experiments."""
    v_scale: float = SCALE           # Multiplier for raw vertex floats
    b_scale: float = SCALE           # Multiplier for raw bone floats
    swizzle_mode: str = "XZY"        # Axis mapping (e.g. "XYZ", "XZY", "YXZ", etc.)
    bone_mode: str = "REL"           # "REL" (to parent), "ABS" (ignore hierarchy), "ROOT" (to bone 0)
    bone_id_bias: int = 0            # Offset applied to b_id (0, -1, 1)
    flip_x: bool = False
    flip_y: bool = False
    flip_z: bool = False

    def swizzle(self, x: float, y: float, z: float, scale: float = None) -> tuple:
        """Apply dynamic axis mapping and scaling."""
        if scale is None:
            scale = self.v_scale
        
        tx, ty, tz = x, y, z
        if self.flip_x: tx = -tx
        if self.flip_y: ty = -ty
        if self.flip_z: tz = -tz
        
        mode = self.swizzle_mode.upper()
        if mode == "XZY":  # Standard IGI->GL (X->X, Z->Y, Y->Z)
            return tx * scale, tz * scale, ty * scale
        elif mode == "XYZ":  # No mapping
            return tx * scale, ty * scale, tz * scale
        elif mode == "YXZ":  # Swap X/Y
            return ty * scale, tx * scale, tz * scale
        elif mode == "ZXY":
            return tz * scale, tx * scale, ty * scale
        elif mode == "YZX":
            return ty * scale, tz * scale, tx * scale
        elif mode == "ZYX":
            return tz * scale, ty * scale, tx * scale
        return tx * scale, ty * scale, tz * scale

class Attachment:
    name: str
    pos: Vector3
    rotMat: list[float]
    unk: int
    bone_id: int

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        name = buffer.read_ascii_string(16)
        pos = Vector3.from_buffer(buffer)
        rotMat = list(buffer.read_fmt("9f"))
        unk = buffer.read_uint32()
        bone_id = buffer.read_uint32()
        return cls(name, pos, rotMat, unk, bone_id)

class AttachmentIGI1:
    name: str
    pos: Vector3
    rotMat: list[float]
    unk: int

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        name = buffer.read_ascii_string(16)
        pos = Vector3.from_buffer(buffer)
        rotMat = list(buffer.read_fmt("9f"))
        unk = buffer.read_uint32()
        return cls(name, pos, rotMat, unk)

class MagicVertex:
    pos: Vector3
    type: int

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        pos = Vector3.from_buffer(buffer)
        typ = buffer.read_uint32()
        return cls(pos, typ)

class Portal:
    start_vertex: int
    num_vertices: int
    start_face: int
    num_faces: int
    portal_id: int

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(*buffer.read_fmt("5I"))

class PortalVertex:
    pos: Vector3

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(Vector3.from_buffer(buffer))

class PortalFace:
    a: int
    b: int
    c: int

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(*buffer.read_fmt("3I"))

class GlowSprite:
    pos: Vector3
    radius: float
    color_r: float
    color_g: float
    color_b: float
    unk: int

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        pos = Vector3.from_buffer(buffer)
        radius = buffer.read_float()
        r, g, b = buffer.read_fmt("3f")
        unk = buffer.read_uint32()
        return cls(pos, radius, r, g, b, unk)

class CollisionMaterialIGI1:
    fields: list[int]  # 6 int16

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        fields = list(buffer.read_fmt("6h"))
        return cls(fields)

class CollisionMaterialIGI2:
    opacity: int           # uint32
    portal_id: int         # uint16
    texture_id: int        # uint16
    unknown1: int          # uint32
    game_material_id: int  # uint16
    unknown2: int          # uint16

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        opacity = buffer.read_uint32()
        portal_id = buffer.read_uint16()
        texture_id = buffer.read_uint16()
        unknown1 = buffer.read_uint32()
        game_material_id = buffer.read_uint16()
        unknown2 = buffer.read_uint16()
        return cls(opacity, portal_id, texture_id, unknown1, game_material_id, unknown2)

class LightmapData:
    width: int
    height: int
    format: int
    data: bytes

class TXANData:
    unknown_fields: list[int]

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        fields = list(buffer.read_fmt("28I"))
        return cls(fields)

class HSEMInfo:
    """هيكل HSEM المعاد هيكلته حسب المواصفات الرسمية لـ IGI2"""
    version: float
    model_type: int
    bound_min: Vector3
    bound_max: Vector3
    radius: float

    @classmethod
    def from_buffer(cls, buffer: Buffer):
        """قراءة صحيحة حسب ترتيب البايتات الفعلي في IGI2"""
        # الترتيب الصحيح (من الوثائق + اختبار على الملفات):
        version = buffer.read_float()           # أول float = version
        model_type = buffer.read_uint32()       # model_type
        bound_min = Vector3.from_buffer(buffer)
        bound_max = Vector3.from_buffer(buffer)
        radius = buffer.read_float()

        # باقي البايتات (padding أو حقول إضافية) يتم تجاهلها تلقائياً
        return cls(version, model_type, bound_min, bound_max, radius)

class TextureCoordinateSet:
    """مجموعة إحداثيات نسيج من قطعة TCST"""
    index: int
    uvs: List[Tuple[float, float]] = field(default_factory=list)

    @classmethod
    def from_buffer(cls, buffer: Buffer, count: int):
        uvs = []
        for _ in range(count):
            u = buffer.read_float()
            v = buffer.read_float()
            uvs.append((u, v))
        return cls(0, uvs)



# ========== Auto-Distributed Classes ==========

class DateTime(datetime):
    @classmethod
    def from_buffer(cls, buffer: Buffer):
        return cls(
            buffer.read_uint32(), buffer.read_uint32(), buffer.read_uint32(),
            buffer.read_uint32(), buffer.read_uint32(), buffer.read_uint32(),
            buffer.read_uint32(),
        )

