"""
core/utils.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math



# ========== Functions ==========
def convert_to_json_serializable(obj):
    """تحويل الكائنات إلى صيغة قابلة للتسلسل في JSON"""
    if isinstance(obj, np.float32):
        return float(obj)
    elif isinstance(obj, np.float64):
        return float(obj)
    elif isinstance(obj, np.int32):
        return int(obj)
    elif isinstance(obj, np.int64):
        return int(obj)
    elif isinstance(obj, np.uint16):
        return int(obj)
    elif isinstance(obj, np.uint32):
        return int(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, dict):
        return {k: convert_to_json_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, (list, tuple)):
        return [convert_to_json_serializable(item) for item in obj]
    return obj

def get_texture_name(texture_index: int, base_name: str, material_index: int, 
                     texture_references: Optional[List[TextureReference]] = None) -> str:
    """
    تحويل مؤشر القوام إلى اسم ملف.
    يدعم الآن TextureReference من قطعة XTXM.
    """
    # أولاً: البحث في texture_references إذا كانت متوفرة
    if texture_references:
        for ref in texture_references:
            if ref.index == texture_index:
                # استخراج اسم الملف من المسار إذا لزم الأمر
                ref_name = ref.name
                if ref_name.endswith('.tga') or ref_name.endswith('.dds') or ref_name.endswith('.png'):
                    return ref_name
                else:
                    return f"{ref_name}.tga"
    
    # ثانياً: الأسماء الافتراضية
    if texture_index == 0:
        return f"{base_name}.tga"
    elif texture_index == 1:
        return f"{base_name}_bump.tga"
    elif texture_index == 2:
        return f"{base_name}_reflection.tga"
    else:
        return f"{base_name}_mat{material_index}.tga"

def make_translation_matrix(x, y, z):
    m = np.identity(4, dtype=np.float32)
    m[0, 3] = x
    m[1, 3] = y
    m[2, 3] = z
    return m

def apply_igi_swizzle(x: float, y: float, z: float, scale: float = SCALE) -> tuple:
    """
    تحويل الإحداثيات من صيغة IGI2 إلى الصيغة القياسية (Unity/Blender)
    الصيغة: (x, z, -y) * scale
    """
    return (x * scale, z * scale, -y * scale)

def apply_igi_swizzle_to_vector3(vec: Vector3, scale: float = SCALE) -> Vector3:
    """تطبيق التحويل على كائن Vector3"""
    x, y, z = apply_igi_swizzle(vec.x, vec.y, vec.z, scale)
    return Vector3(x, y, z)

def save_lightmap_as_png(lightmap_data, output_path):
    if not PIL_AVAILABLE:
        return False
    
    try:
        width = lightmap_data.width
        height = lightmap_data.height
        data = lightmap_data.data
        
        if len(data) == width * height * 3:
            img = Image.frombytes('RGB', (width, height), data)
        elif len(data) == width * height * 4:
            img = Image.frombytes('RGBA', (width, height), data)
        elif len(data) == width * height:
            img = Image.frombytes('L', (width, height), data)
        else:
            print(f"      Unknown lightmap format, size: {len(data)} bytes")
            return False
        
        img.save(output_path, 'PNG')
        return True
    except Exception as e:
        print(f"      Error converting to PNG: {e}")
        return False

def save_lightmap_as_dds(lightmap_data, output_path):
    try:
        with open(output_path, 'wb') as f:
            f.write(lightmap_data.data)
        return True
    except Exception as e:
        print(f"      Error saving DDS: {e}")
        return False

def set_global_debug_params(debug_params: 'MefDebugParams'):
    """تعيين معاملات التصحيح العامة للاستخدام في جميع أنحاء السكربت"""
    global global_debug_params
    global_debug_params = debug_params
    print(f"✅ Global debug parameters set: scale={debug_params.v_scale}, swizzle={debug_params.swizzle_mode}")

def get_global_debug_params() -> Optional[MefDebugParams]:
    """الحصول على معاملات التصحيح العامة"""
    return global_debug_params

def reset_global_debug_params():
    """إعادة تعيين المعاملات العامة إلى القيم الافتراضية"""
    global global_debug_params
    global_debug_params = MefDebugParams()
    print("✅ Global debug parameters reset to defaults")

def quick_validate(filepath: str, debug_params: Optional[MefDebugParams] = None) -> bool:
    """التحقق السريع من صحة ملف MEF مع دعم معاملات التصحيح"""
    if debug_params is None:
        debug_params = global_debug_params
    
    try:
        with open(filepath, "rb") as f:
            result = f.read(4) == b'ILFF'
            if debug_params:
                print(f"   Quick validate: {filepath} -> {'valid' if result else 'invalid'} (debug mode)")
            return result
    except:
        return False

def detect_file_type(buffer: Buffer, filename: str = "") -> str:
    """تحديد نوع الملف: MEF, MDL, SMD, أو OBJ"""
    saved_pos = buffer.offset
    buffer.offset = 0
    
    try:
        # التحقق من توقيع MDL (IDST)
        magic = buffer.read(4)
        buffer.offset = saved_pos
        
        if magic == b'IDST':
            return "MDL"
        elif magic == b'ILFF':
            return "MEF"
        else:
            # التحقق من SMD بناءً على الامتداد أو أول سطر
            if filename.lower().endswith('.smd'):
                return "SMD"
            
            # ✅ أضف هذا الجزء الجديد لـ OBJ
            if filename.lower().endswith('.obj'):
                return "OBJ"
            
            # محاولة قراءة أول سطر للتحقق من صيغة OBJ
            try:
                first_line = buffer.data[:200].decode('ascii', errors='ignore')
                if first_line.startswith('v ') or first_line.startswith('vt ') or first_line.startswith('vn ') or first_line.startswith('f ') or first_line.startswith('o ') or first_line.startswith('g '):
                    return "OBJ"
            except:
                pass
            
            # محاولة قراءة أول سطر للتحقق من صيغة SMD
            try:
                first_line = buffer.data[:200].decode('ascii', errors='ignore')
                if 'version' in first_line and 'nodes' in first_line and 'triangles' in first_line:
                    return "SMD"
            except:
                pass
            
            return "UNKNOWN"
    except:
        buffer.offset = saved_pos
        return "UNKNOWN"

def detect_mef_version(buffer: Buffer, debug_params=None) -> str:
    """تحديد إصدار MEF (IGI1 أو IGI2)"""
    saved_pos = buffer.offset
    buffer.offset = 0
    
    try:
        signature = buffer.read(4)
        if signature != b'ILFF':
            raise ValueError("Not an ILFF file")
        
        file_size = buffer.read_uint32()
        align = buffer.read_uint32()
        offset = buffer.read_uint32()
        formatsig = buffer.read(4)
        
        ident = buffer.read(4)
        data_size = buffer.read_uint32()
        
        buffer.offset = saved_pos
        
        if data_size == 156 or data_size == 172:
            return "IGI1"
        elif data_size == 212:
            return "IGI2"
        
        return "IGI2"  # افتراضي
    except:
        buffer.offset = saved_pos
        return "IGI2"


# ========== Auto-Distributed Functions ==========

            def print_tree(bone_idx, level=0, prefix=""):
                bone = bone_data[bone_idx]
                indent = "  " * level
                marker = "├─ " if level > 0 else "└─ "
                f.write(f"{indent}{marker}{bone['name']} [ID:{bone_idx}, Parent:{bone['parent_id']}]\n")
                f.write(f"{indent}   pos: ({bone['position'][0]:.2f}, {bone['position'][1]:.2f}, {bone['position'][2]:.2f})\n")
                
                for i, child in enumerate(bone['children']):
                    is_last = (i == len(bone['children']) - 1)
                    child_prefix = prefix + ("    " if is_last else "│   ")
                    print_tree(child, level + 1, child_prefix)

