"""
exporters/mdl/export_extra.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math



# ========== Functions ==========
    def get_texture_names_from_mdl(self) -> List[str]:
        """استخراج أسماء القوام من MDL"""
        texture_names = []
        if hasattr(self.header, 'numtextures') and self.header.numtextures > 0:
            # إضافة أسماء افتراضية للقوام
            for i in range(min(self.header.numtextures, 10)):
                texture_names.append(f"texture_{i}.bmp")
        if not texture_names:
            texture_names.append("texture.bmp")
        return texture_names


# ========== Auto-Distributed Functions ==========

def fix_directx_mdl_extraction():
    """تصحيح استخراج العظام من MDL لـ DirectXExporter"""
    
    def from_mdl_model_fixed(self, model):
        if hasattr(model, 'bones') and model.bones:
            for i, bone in enumerate(model.bones):
                parent_id = bone.parent if hasattr(bone, 'parent') else -1
                
                frame = DXFrame(
                    name=bone.name,
                    parent_id=parent_id,
                    parent_name=model.bones[parent_id].name if parent_id >= 0 and parent_id < len(model.bones) else "",
                    position=(bone.value[0] if len(bone.value) > 0 else 0,
                             bone.value[1] if len(bone.value) > 1 else 0,
                             bone.value[2] if len(bone.value) > 2 else 0)
                )
                self.frames.append(frame)
            
            for i, bone in enumerate(model.bones):
                parent_id = bone.parent if hasattr(bone, 'parent') else -1
                if parent_id >= 0 and parent_id < len(self.frames):
                    self.frames[i].parent_id = parent_id
            
            print(f"   🦴 Extracted {len(self.frames)} bones/frames from MDL")
        
        if hasattr(model, 'header') and hasattr(model.header, 'numtextures') and model.header.numtextures > 0:
            for i in range(min(model.header.numtextures, 10)):
                self.materials.append({
                    "name": f"material_{i}",
                    "texture": f"texture_{i}.bmp"
                })
            print(f"   🎨 Extracted {len(self.materials)} materials from MDL")
        
        return self
    
    def _extract_mesh_from_mdl_fixed(self, model):
        if not hasattr(model, 'vertices') or not model.vertices:
            return
        
        for i, v in enumerate(model.vertices):
            px, py, pz = v.x, v.z, v.y
            self.frames[0].vertices.append((px, py, pz))
            self.frames[0].normals.append((0, 0, 0))
            self.frames[0].uvs.append((0, 0))
        
        for tri in model.triangles:
            if len(tri.vertindex) >= 3:
                self.frames[0].faces.append((tri.vertindex[0], tri.vertindex[1], tri.vertindex[2]))
        
        print(f"   📦 Extracted mesh from MDL: {len(self.frames[0].vertices)} vertices, {len(self.frames[0].faces)} faces")
    
    DirectXExporter.from_mdl_model = from_mdl_model_fixed
    DirectXExporter._extract_mesh_from_mdl = _extract_mesh_from_mdl_fixed
    print("✅ Added MDL support to DirectXExporter")

    def get_texture_names_from_mdl_model(self) -> List[str]:
        """استخراج أسماء القوام من MdlModel"""
        texture_names = []
        if hasattr(self, 'textures') and self.textures:
            for tex in self.textures:
                if hasattr(tex, 'name'):
                    texture_names.append(tex.name)
        if not texture_names:
            texture_names.append("texture.bmp")
        return texture_names

