"""
__init__.py - Package initialization
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# ============================================================

__all__ = ['main', 'optimized_convert_file', 'parallel_process_folder', 'Buffer', 'MefModelIGI1', 'MefModelIGI2', 'StudioHeader', 'SMDExporter', 'OBJExporter', 'SCALE', 'ModelType', 'MefDebugParams']

from . import main
from . import optimized_convert_file
from . import parallel_process_folder
from . import Buffer
from . import MefModelIGI1
from . import MefModelIGI2
from . import StudioHeader
from . import SMDExporter
from . import OBJExporter
from . import SCALE
from . import ModelType
from . import MefDebugParams

__version__ = "3.0.0"