"""
main.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math

# ========== Constants ==========


# ========== Functions ==========
def main():
    parser = argparse.ArgumentParser(description="IGI1/IGI2 MEF & Half-Life MDL Model Exporter")
    parser.add_argument("input", nargs="?", default=INPUT_DIR,
                       help=f"Input file or folder (default: {INPUT_DIR})")
    parser.add_argument("-o", "--output", default=OUTPUT_DIR,
                       help=f"Output directory (default: {OUTPUT_DIR})")
    parser.add_argument("-m", "--mode", choices=["simple", "multi"], default="simple",
                       help="Export mode: simple (single file) or multi (separate material groups)")
    parser.add_argument("-f", "--file", action="store_true",
                       help="Treat input as single file (default: folder mode)")
    parser.add_argument("-F", "--format", choices=["obj", "dae", "gltf", "json", "txt", "directx", "all"], default="obj",
                       help="Export format: obj, dae, gltf, json, txt, directx, or all")
    parser.add_argument("-L", "--lightmap-format", choices=["tga", "png", "dds", "both"], default="png",
                       help="Lightmap format (for MEF only)")
    parser.add_argument("--force-version", choices=["IGI1", "IGI2", "auto"], default="auto",
                       help="Force MEF version (default: auto-detect)")
    parser.add_argument("--atlas", choices=["true", "false", "smd", "obj", "mdl"], default=None,
                       help="Enable/disable texture atlas: true, false, smd, obj, mdl (default: None)")
    parser.add_argument("--atlas-mode", choices=["preserve", "merge"], default="preserve",
                       help="Texture atlas mode: preserve (keep materials) or merge (single material)")
                   
    args = parser.parse_args()
    
    # ========== معالجة وسيط الأطلس ==========
    if args.atlas == "true":
        enable_texture_atlas_for_all(True)
    elif args.atlas == "false":
        enable_texture_atlas_for_all(False)
    elif args.atlas == "smd":
        global ENABLE_TEXTURE_ATLAS_SMD, ENABLE_TEXTURE_ATLAS_OBJ, ENABLE_TEXTURE_ATLAS_MDL
        ENABLE_TEXTURE_ATLAS_SMD = True
        ENABLE_TEXTURE_ATLAS_OBJ = False
        ENABLE_TEXTURE_ATLAS_MDL = False
        print("✅ Texture Atlas enabled only for SMD")
    elif args.atlas == "obj":
        ENABLE_TEXTURE_ATLAS_SMD = False
        ENABLE_TEXTURE_ATLAS_OBJ = True
        ENABLE_TEXTURE_ATLAS_MDL = False
        print("✅ Texture Atlas enabled only for OBJ")
    elif args.atlas == "mdl":
        ENABLE_TEXTURE_ATLAS_SMD = False
        ENABLE_TEXTURE_ATLAS_OBJ = False
        ENABLE_TEXTURE_ATLAS_MDL = True
        print("✅ Texture Atlas enabled only for MDL")
    
    # ========== معالجة وسيط وضع الأطلس ==========
    global ATLAS_MODE
    ATLAS_MODE = args.atlas_mode
    print(f"✅ Texture Atlas mode: {ATLAS_MODE}")
    # ============================================
    
    export_formats = ["obj"]
    if args.format == "dae":
        export_formats = ["dae"]
    elif args.format == "gltf":
        export_formats = ["gltf"]
    elif args.format == "json":
        export_formats = ["json"]
    elif args.format == "txt":
        export_formats = ["txt"]
    elif args.format == "directx":
        export_formats = ["directx"]
    elif args.format == "all":
        export_formats = ["obj", "dae", "gltf", "json", "txt", "directx"]
    
    print(f"\nMulti-Format Model Exporter (MEF + MDL)")
    print("=" * 60)
    print(f"Export mode : {args.mode}")
    print(f"Export formats : {', '.join(export_formats)}")
    print(f"Output dir : {args.output}")
    print("=" * 60)
    
    Path(args.output).mkdir(parents=True, exist_ok=True)
    
    # دعم صيغة SMD (Crowbar)
    if args.input.endswith('.smd') or args.input.endswith('.SMD'):
        print(f"\nSMD file detected - converting to {', '.join(export_formats)}")
        success = convert_smd_to_formats_fixed(args.input, args.output, export_formats)  # استخدم الدالة المصلحة
        
        # DirectX export for SMD
        if success and "directx" in export_formats:
            try:
                with open(args.input, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                smd = SMDExporter.from_string(content)
                dx_path = os.path.join(args.output, f"{Path(args.input).stem}.x")
                export_to_directx(smd, dx_path, "smd")
                print(f"   ✅ DirectX export completed: {dx_path}")
            except Exception as e:
                print(f"   ⚠️ DirectX export failed: {e}")
        
        if success:
            print(f"\n✓ Successfully converted SMD: {args.input}")
        else:
            print(f"\n✗ Failed to convert SMD: {args.input}")
        return
    
    # دعم صيغة OBJ
    if args.input.endswith('.obj') or args.input.endswith('.OBJ'):
        print(f"\nOBJ file detected - converting to {', '.join(export_formats)}")
        success = convert_obj_to_formats_fixed(args.input, args.output, export_formats)  # استخدم الدالة المصلحة
        
        # DirectX export for OBJ
        if success and "directx" in export_formats:
            try:
                obj = OBJExporter.from_file(args.input)
                dx_path = os.path.join(args.output, f"{Path(args.input).stem}.x")
                export_to_directx(obj, dx_path, "obj")
                print(f"   ✅ DirectX export completed: {dx_path}")
            except Exception as e:
                print(f"   ⚠️ DirectX export failed: {e}")
        
        if success:
            print(f"\n✓ Successfully converted OBJ: {args.input}")
        else:
            print(f"\n✗ Failed to convert OBJ: {args.input}")
        return
    
    # معالجة ملف واحد
    if args.file or (os.path.isfile(args.input) and not os.path.isdir(args.input)):
        input_path = args.input
        if not os.path.isfile(input_path):
            print(f"\nError: File not found: {input_path}")
            sys.exit(1)
        
        output_subdir = os.path.join(args.output, Path(input_path).stem)
        
        print(f"\nProcessing single file: {input_path}")
        print(f"Output folder: {output_subdir}")
        print("=" * 60)
        
        try:
            with open(input_path, "rb") as f:
                data = f.read()
            
            print(f"File size: {len(data)} bytes")
            buffer = Buffer(data)
            
            file_type = detect_file_type(buffer, str(input_path))
            print(f"Detected file type: {file_type}")
            
            model = None
            
            if file_type == "MDL":
                model = StudioHeader(buffer)
                model.export_all(output_subdir, export_formats)
            elif file_type == "MEF":
                version = detect_mef_version(buffer)
                if version == "IGI2":
                    model = MefModelIGI2(buffer, export_mode=args.mode)
                else:
                    model = MefModelIGI1(buffer, export_mode=args.mode)
                model.export_all(output_subdir, export_formats, args.lightmap_format)
            else:
                print(f"Unknown file type: {file_type}")
                sys.exit(1)
            
            # تصدير DirectX - استخدم الدالة المساعدة
            fix_export_to_directx_in_main(input_path, output_subdir, file_type, model, export_formats)
            
            print(f"\n✓ Successfully processed: {Path(input_path).name}")
            print(f"   Output folder: {output_subdir}")
            
        except Exception as e:
            print(f"\n✗ Error processing {input_path}: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)
    
    else:
        input_dir = args.input
        if not os.path.exists(input_dir):
            print(f"\nError: Input folder '{input_dir}' not found!")
            sys.exit(1)
        
        # البحث عن الملفات
        mef_files = set()
        for ext in ['*.mef', '*.MEF']:
            mef_files.update(Path(input_dir).glob(ext))

        mdl_files = set()
        for ext in ['*.mdl', '*.MDL']:
            mdl_files.update(Path(input_dir).glob(ext))

        smd_files = set()
        for ext in ['*.smd', '*.SMD']:
            smd_files.update(Path(input_dir).glob(ext))
        
        obj_files = set()
        for ext in ['*.obj', '*.OBJ']:
            obj_files.update(Path(input_dir).glob(ext))

        all_files = list(mef_files.union(mdl_files).union(smd_files).union(obj_files))
        
        if not all_files:
            print(f"\nNo .mef, .mdl, .smd, or .obj files found in '{input_dir}' folder.")
            sys.exit(1)
        
        all_files.sort()
        
        print(f"\nFound {len(all_files)} file(s) to process:")
        for f in all_files:
            print(f"  - {f.name}")
        
        print("\n" + "=" * 60)
        
        successful = 0
        failed = 0
        
        for file_path in all_files:
            print(f"\n{'=' * 60}")
            print(f"Processing: {file_path.name}")
            print(f"{'=' * 60}")
            
            output_subdir = os.path.join(args.output, file_path.stem)
            
            try:
                if file_path.suffix.lower() in ['.smd']:
                    # معالجة SMD
                    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                        content = f.read()
                    smd = SMDExporter.from_string(content)
                    base_name = file_path.stem
                    smd.export_all(output_subdir, base_name, export_formats)
                    
                    # DirectX for SMD
                    if "directx" in export_formats:
                        dx_path = os.path.join(output_subdir, f"{base_name}.x")
                        export_to_directx(smd, dx_path, "smd")
                    
                elif file_path.suffix.lower() in ['.obj']:
                    # معالجة OBJ
                    obj = OBJExporter.from_file(str(file_path))
                    base_name = file_path.stem
                    obj.export_all(output_subdir, base_name, export_formats)
                    
                    # DirectX for OBJ
                    if "directx" in export_formats:
                        dx_path = os.path.join(output_subdir, f"{base_name}.x")
                        export_to_directx(obj, dx_path, "obj")
                    
                else:
                    # معالجة MEF أو MDL
                    with open(file_path, "rb") as f:
                        data = f.read()
                    
                    buffer = Buffer(data)
                    file_type = detect_file_type(buffer, str(file_path))
                    
                    if file_type == "MDL":
                        model = StudioHeader(buffer)
                        model.export_all(output_subdir, export_formats)
                    else:
                        version = detect_mef_version(buffer)
                        if version == "IGI2":
                            model = MefModelIGI2(buffer, export_mode=args.mode)
                        else:
                            model = MefModelIGI1(buffer, export_mode=args.mode)
                        model.export_all(output_subdir, export_formats, args.lightmap_format)
                    
                    # DirectX for MEF/MDL
                    fix_export_to_directx_in_main(str(file_path), output_subdir, file_type, model, export_formats)
                
                successful += 1
                print(f"\n✓ Successfully processed: {file_path.name}")
                
            except Exception as e:
                failed += 1
                print(f"\n✗ Error processing {file_path.name}: {e}")
                import traceback
                traceback.print_exc()
        
        print("\n" + "=" * 60)
        print("BATCH PROCESSING COMPLETE")
        print("=" * 60)
        print(f"Total files found : {len(all_files)}")
        print(f"Successfully processed : {successful}")
        print(f"Failed : {failed}")
        print(f"Output folder : {args.output}")
        print("=" * 60)

def main_optimized():
    """الدالة الرئيسية المحسنة مع خيارات متقدمة"""
    
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Optimized MEF Model Exporter for IGI1/IGI2 (with caching & parallel processing)"
    )
    parser.add_argument("input", nargs="?", default=INPUT_DIR,
                       help=f"Input file or folder (default: {INPUT_DIR})")
    parser.add_argument("-o", "--output", default=OUTPUT_DIR,
                       help=f"Output directory (default: {OUTPUT_DIR})")
    parser.add_argument("-f", "--format", choices=["obj", "dae", "gltf", "json", "txt", "all"], 
                       default="obj", help="Export format")
    parser.add_argument("--parallel", action="store_true", default=True,
                       help="Enable parallel processing (default: True)")
    parser.add_argument("--no-parallel", action="store_false", dest="parallel",
                       help="Disable parallel processing")
    parser.add_argument("--cache", action="store_true", default=True,
                       help="Enable caching (default: True)")
    parser.add_argument("--no-cache", action="store_false", dest="cache",
                       help="Disable caching")
    parser.add_argument("--animations", action="store_true", default=True,
                       help="Extract animations (default: True)")
    parser.add_argument("--no-animations", action="store_false", dest="animations",
                       help="Disable animation extraction")
    parser.add_argument("--workers", type=int, default=None,
                       help=f"Number of parallel workers (default: CPU count)")
    parser.add_argument("--clear-cache", action="store_true",
                       help="Clear cache before processing")
    
    args = parser.parse_args()
    
    # إعدادات التصدير
    export_formats = ["obj"]
    if args.format == "dae":
        export_formats = ["dae"]
    elif args.format == "gltf":
        export_formats = ["gltf"]
    elif args.format == "json":
        export_formats = ["json"]
    elif args.format == "txt":
        export_formats = ["txt"]
    elif args.format == "directx":
        export_formats = ["directx"]
    elif args.format == "all":
        export_formats = ["obj", "dae", "gltf", "json", "txt", "directx"]
    
    print("\n" + "=" * 70)
    print("🚀 OPTIMIZED MEF MODEL EXPORTER")
    print("=" * 70)
    print(f"   Parallel processing : {args.parallel}")
    print(f"   Caching            : {args.cache}")
    print(f"   Extract animations : {args.animations}")
    print(f"   Workers            : {args.workers or 'auto'}")
    print(f"   Export formats     : {', '.join(export_formats)}")
    print("=" * 70)
    
    # مسح التخزين المؤقت إذا طلب
    if args.clear_cache:
        cache = MefCache(enabled=True)
        cache.clear_cache()
    
    # إنشاء مجلد الإخراج
    Path(args.output).mkdir(parents=True, exist_ok=True)
    
    # معالجة ملف واحد أو مجلد
    if os.path.isfile(args.input):
        result = optimized_convert_file(
            args.input, args.output,
            use_parallel=args.parallel,
            use_cache=args.cache,
            extract_animations=args.animations,
            export_formats=export_formats
        )
        
        if result["success"]:
            print(f"\n✅ Successfully converted: {Path(args.input).name}")
            if result.get("cached"):
                print(f"   (Result from cache)")
            if result.get("animations_found", 0) > 0:
                print(f"   🎬 Found {result['animations_found']} animations")
        else:
            print(f"\n❌ Failed to convert: {Path(args.input).name}")
            
    elif os.path.isdir(args.input):
        # معالجة متوازية للمجلد
        result = parallel_process_folder(
            args.input, args.output,
            max_workers=args.workers,
            use_cache=args.cache,
            export_formats=export_formats
        )
    else:
        print(f"\n❌ Error: Input '{args.input}' not found!")
        sys.exit(1)

def optimized_convert_file(input_path: str, output_dir: str, 
                          use_parallel: bool = True,
                          use_cache: bool = True,
                          extract_animations: bool = True,
                          export_formats: List[str] = None) -> dict:
    """
    دالة تحويل محسنة مع دعم متقدم
    
    Args:
        input_path: مسار ملف الإدخال
        output_dir: مجلد الإخراج
        use_parallel: استخدام المعالجة المتوازية
        use_cache: استخدام التخزين المؤقت
        extract_animations: استخراج الرسوم المتحركة
        export_formats: صيغ التصدير المطلوبة
    
    Returns:
        قاموس يحتوي على نتائج التحويل
    """
    
    if export_formats is None:
        export_formats = ["obj", "gltf", "json", "txt"]
    
    monitor = PerformanceMonitor()
    cache = MefCache(enabled=use_cache)
    
    result = {
        "success": False,
        "input": input_path,
        "output": output_dir,
        "metrics": {},
        "animations_found": 0,
        "cached": False
    }
    
    # التحقق من التخزين المؤقت
    if use_cache:
        cached_result = cache.get_cached_result(input_path, "full_export")
        if cached_result:
            result["cached"] = True
            result["success"] = True
            result["metrics"] = cached_result.get("metrics", {})
            print(f"   ✅ Using cached result for {Path(input_path).name}")
            return result
    
    try:
        # قراءة الملف
        with monitor.measure("File read"):
            with open(input_path, "rb") as f:
                data = f.read()
        
        # إنشاء النموذج المحسن
        with monitor.measure("Model parsing"):
            buffer = Buffer(data)
            model = OptimizedMefModelIGI2(buffer, export_mode="multi", 
                                          use_parallel=use_parallel)
        
        # استخراج الرسوم المتحركة
        if extract_animations and hasattr(model, 'txan_data') and model.txan_data:
            with monitor.measure("Animation extraction"):
                anim_exporter = AnimationExporter(model)
                animations = anim_exporter.extract_from_txan()
                result["animations_found"] = len(animations)
                
                if animations and "gltf" in export_formats:
                    anim_exporter.export_to_gltf_animations(
                        os.path.join(output_dir, Path(input_path).stem)
                    )
                
                if animations and "json" in export_formats:
                    anim_exporter.export_to_json(
                        os.path.join(output_dir, f"{Path(input_path).stem}_animations.json")
                    )
        
        # تصدير النموذج
        with monitor.measure("Model export"):
            base_name = Path(input_path).stem
            out_path = os.path.join(output_dir, base_name)
            if hasattr(model, 'export_all_enhanced'):
                model.export_all_enhanced(out_path, export_formats)
            else:
                model.export_all(out_path, export_formats)
        
        # تخزين النتيجة في التخزين المؤقت
        if use_cache:
            cache.store_cached_result(input_path, "full_export", {
                "metrics": monitor.metrics,
                "animations": result["animations_found"],
                "export_formats": export_formats
            })
        
        result["success"] = True
        result["metrics"] = monitor.metrics
        
        # طباعة تقرير الأداء
        monitor.print_report()
        
        return result
        
    except Exception as e:
        print(f"   ❌ Error: {e}")
        import traceback
        traceback.print_exc()
        result["error"] = str(e)
        return result

def parallel_process_folder(input_dir: str, output_dir: str,
                           max_workers: int = None,
                           use_cache: bool = True,
                           export_formats: List[str] = None) -> dict:
    """
    معالجة مجلد كامل من ملفات MEF بشكل متوازي
    
    Args:
        input_dir: مجلد الإدخال
        output_dir: مجلد الإخراج
        max_workers: عدد العمليات المتوازية
        use_cache: استخدام التخزين المؤقت
        export_formats: صيغ التصدير
    
    Returns:
        قاموس بنتائج المعالجة
    """
    
    if max_workers is None:
        max_workers = mp.cpu_count()
    
    # البحث عن ملفات MEF
    mef_files = []
    for ext in ['*.mef', '*.MEF']:
        mef_files.extend(Path(input_dir).glob(ext))
    
    if not mef_files:
        print(f"No MEF files found in {input_dir}")
        return {"total": 0, "successful": 0, "failed": 0}
    
    print(f"\n📁 Found {len(mef_files)} MEF files")
    print(f"🚀 Using {max_workers} parallel workers")
    print("=" * 60)
    
    # إعداد المعالجة المتوازية
    results = []
    successful = 0
    failed = 0
    
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        # تجهيز المهام
        futures = []
        for mef_file in mef_files:
            output_subdir = os.path.join(output_dir, mef_file.stem)
            future = executor.submit(
                optimized_convert_file,
                str(mef_file),
                output_subdir,
                True,  # use_parallel
                use_cache,
                True,  # extract_animations
                export_formats
            )
            futures.append((mef_file.name, future))
        
        # جمع النتائج
        for filename, future in futures:
            try:
                result = future.result()
                if result["success"]:
                    successful += 1
                    print(f"   ✅ {filename}: success (cached={result.get('cached', False)})")
                else:
                    failed += 1
                    print(f"   ❌ {filename}: failed - {result.get('error', 'Unknown error')}")
                results.append(result)
            except Exception as e:
                failed += 1
                print(f"   ❌ {filename}: exception - {e}")
    
    # تقرير نهائي
    print("\n" + "=" * 60)
    print("📊 BATCH PROCESSING REPORT")
    print("=" * 60)
    print(f"   Total files    : {len(mef_files)}")
    print(f"   Successful     : {successful}")
    print(f"   Failed         : {failed}")
    print(f"   Output folder  : {output_dir}")
    print("=" * 60)
    
    return {
        "total": len(mef_files),
        "successful": successful,
        "failed": failed,
        "results": results
    }

def comprehensive_test(input_file: str, output_dir: str = "test_output"):
    """اختبار شامل للمحلل المحسن"""
    
    print("\n" + "=" * 70)
    print("🧪 COMPREHENSIVE TEST - Enhanced MEF Parser")
    print("=" * 70)
    
    with open(input_file, "rb") as f:
        data = f.read()
    
    buffer = Buffer(data)
    model = MefModelIGI2(buffer, export_mode="multi")
    
    # اختبار التصدير المحسن
    base_name = Path(input_file).stem
    out_path = os.path.join(output_dir, base_name)
    model.export_all_enhanced(out_path, export_formats=["obj", "json", "txt"])
    
    # طباعة التقرير
    print("\n" + "=" * 70)
    print("📊 TEST REPORT")
    print("=" * 70)
    
    report = {
        "File": input_file,
        "File size": f"{len(data)} bytes",
        "Model type": model.model_info.model_type.name if model.model_info else "Unknown",
        "Bones": len(model.bones),
        "Bone names": len(model.bone_names),
        "Bone extra params (HPRM)": len(model.bone_extra_params) if hasattr(model, 'bone_extra_params') else 0,
        "Attachments": len(model.attachments),
        "Magic vertices": len(model.magic_vertices),
        "Portals": len(model.portals),
        "Portal faces": len(model.portal_faces),
        "Portal vertices": len(model.portal_vertices),
        "Glow sprites": len(model.glow_sprites),
        "Lightmaps": len(model.lightmaps),
        "TXAN chunks": len(model.txan_data),
        "XTRW weights": len(model.vertex_weights),
        "XTXM textures": len(model.texture_references),
        "TCST UV sets": len(model.extra_uv_sets),
        "External refs (XTRN)": len(model.external_refs) if hasattr(model, 'external_refs') else 0,
        "Skeleton hints (NHSA)": len(model.skeleton_hints) if hasattr(model, 'skeleton_hints') else 0,
        "Shadow faces detailed": len(model.shadow_faces_detailed) if hasattr(model, 'shadow_faces_detailed') else 0,
        "Output directory": out_path,
    }
    
    for key, value in report.items():
        print(f"   {key:28}: {value}")
    
    print("=" * 70)
    print("✅ Test complete!")
    
    return report

def test_enhanced_parser(filepath: str, output_dir: str = "output_enhanced"):
    """اختبار المحلل المحسن على ملف MEF"""
    
    print(f"\n🔬 Testing enhanced MEF parser on: {filepath}")
    print("=" * 60)
    
    with open(filepath, "rb") as f:
        data = f.read()
    
    buffer = Buffer(data)
    model = MefModelIGI2_V2(buffer, export_mode="multi")
    
    # إنشاء المجلد
    base_name = Path(filepath).stem
    out_dir = os.path.join(output_dir, base_name)
    
    # تصدير كل شيء
    model.export_all(out_dir, export_formats=["obj", "json", "txt"])
    
    print(f"\n✅ Test complete! Output: {out_dir}")
    
    # طباعة إحصائيات
    print("\n📊 Statistics:")
    print(f"   Bones: {len(model.bones)}")
    print(f"   Shadow vertices: {len(model.shadow_vertices) if model.shadow_vertices is not None else 0}")
    print(f"   Shadow faces: {len(model.shadow_faces)}")
    print(f"   Shadow edges: {len(model.shadow_edges)}")
    print(f"   External refs: {len(model.external_refs)}")
    print(f"   Skeleton hints: {len(model.skeleton_hints)}")

def test_animation_extraction(filepath: str, output_dir: str = "animation_test"):
    """اختبار استخراج الرسوم المتحركة من ملف MEF"""
    
    print(f"\\n🎬 Testing animation extraction on: {filepath}")
    print("=" * 60)
    
    with open(filepath, "rb") as f:
        data = f.read()
    
    buffer = Buffer(data)
    model = MefModelIGI2(buffer, export_mode="multi")
    
    # استخراج الرسوم المتحركة
    animations = model.extract_animations()
    
    print(f"\\n📊 Found {len(animations)} animations:")
    for anim in animations:
        print(f"   - {anim.name}: {anim.duration:.2f}s, {anim.frame_count} frames, {len(anim.bone_tracks)} bone tracks")
    
    # تصدير الرسوم المتحركة
    base_name = Path(filepath).stem
    out_path = os.path.join(output_dir, base_name)
    os.makedirs(out_path, exist_ok=True)
    
    model.export_animations(out_path, base_name, ["json", "mmd"])
    
    print(f"\\n✅ Animation export complete! Output: {out_path}")
    return animations

def create_addon_files(output_dir: str = "."):
    """إنشاء ملفات الإضافات في المجلد المحدد"""
    create_blender_addon_script(os.path.join(output_dir, "blender_addon.py"))
    create_gui_launcher_script(os.path.join(output_dir, "mef_gui_launcher.py"))
    print(f"\\n📁 Addon files created in: {output_dir}")

def create_blender_addon_script(output_path: str):
    """إنشاء سكربت Blender Add-on جاهز للاستخدام"""
    
    addon_script = '''# ============================================================
# blender_addon.py - إضافة Blender لاستيراد ملفات MEF/MDL
# ============================================================
# وضع هذا الملف في: %APPDATA%\\Blender Foundation\\Blender\\X.XX\\scripts\\addons\\
# أو: ~/.config/blender/X.XX/scripts/addons/

bl_info = {
    "name": "IGI & Half-Life Model Importer",
    "author": "Tavrixender",
    "version": (2, 0, 0),
    "blender": (3, 0, 0),
    "location": "File > Import > IGI Model (.mef/.mdl)",
    "description": "Import IGI1/IGI2 MEF and Half-Life MDL models with full animation support",
    "category": "Import-Export",
}

import bpy
import bmesh
from bpy_extras.io_utils import ImportHelper
from bpy.props import StringProperty, BoolProperty, EnumProperty, FloatProperty
import struct
import numpy as np
from mathutils import Matrix, Vector, Quaternion
import os
import sys

# إضافة مسار السكربت الرئيسي
blend_dir = os.path.dirname(__file__)
if blend_dir not in sys.path:
    sys.path.append(blend_dir)

# ============================================================
# كلاس استيراد IGI
# ============================================================

class ImportIGIModel(bpy.types.Operator, ImportHelper):
    """استيراد نموذج من IGI1/IGI2 أو Half-Life MDL"""
    bl_idname = "import_scene.igi_model"
    bl_label = "Import IGI Model"
    bl_options = {'UNDO', 'PRESET'}
    
    # خيارات الملف
    files: bpy.props.CollectionProperty(
        type=bpy.types.OperatorFileListElement,
        options={'HIDDEN', 'SKIP_SAVE'}
    )
    directory: StringProperty(subtype='DIR_PATH')
    
    # خيارات الاستيراد
    import_animations: BoolProperty(
        name="Import Animations",
        description="Import skeletal animations if available",
        default=True
    )
    
    import_textures: BoolProperty(
        name="Import Textures",
        description="Import and assign textures",
        default=True
    )
    
    scale: FloatProperty(
        name="Scale",
        description="Model scale",
        default=1.0,
        min=0.01,
        max=100.0
    )
    
    create_atlas: BoolProperty(
        name="Create Texture Atlas",
        description="Merge multiple textures into one atlas",
        default=False
    )
    
    import_type: EnumProperty(
        name="Model Type",
        description="Type of model to import",
        items=[
            ('AUTO', "Auto-detect", "Automatically detect file type"),
            ('IGI1', "IGI1", "Project IGI 1 model"),
            ('IGI2', "IGI2", "Project IGI 2 model"),
            ('MDL', "Half-Life MDL", "Half-Life/Counter-Strike model"),
            ('SMD', "SMD", "StudioMDL file"),
            ('OBJ', "OBJ", "Wavefront OBJ file"),
        ],
        default='AUTO'
    )
    
    # خيارات متقدمة
    use_parallel: BoolProperty(
        name="Parallel Processing",
        description="Use multiple CPU cores for faster loading",
        default=True
    )
    
    load_collision: BoolProperty(
        name="Load Collision Mesh",
        description="Import collision mesh as separate object",
        default=False
    )
    
    load_shadow: BoolProperty(
        name="Load Shadow Mesh",
        description="Import shadow mesh as separate object",
        default=False
    )
    
    def execute(self, context):
        """تنفيذ الاستيراد"""
        self.report({'INFO'}, f"Importing {len(self.files)} file(s)")
        self.report({'INFO'}, "IGI Model Importer - Requires main script to be installed")
        return {'FINISHED'}


def menu_func_import(self, context):
    self.layout.operator(ImportIGIModel.bl_idname, text="IGI Model (.mef/.mdl)")


def register():
    bpy.utils.register_class(ImportIGIModel)
    bpy.types.TOPBAR_MT_file_import.append(menu_func_import)


def unregister():
    bpy.utils.unregister_class(ImportIGIModel)
    bpy.types.TOPBAR_MT_file_import.remove(menu_func_import)


if __name__ == "__main__":
    register()
'''
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(addon_script)
    
    print(f"✅ Blender Add-on script created: {output_path}")
    print("   Installation: Copy this file to Blender's addons folder")

def create_gui_launcher_script(output_path: str):
    """إنشاء سكربت تشغيل واجهة PyQt5"""
    
    gui_script = '''#!/usr/bin/env python3
# ============================================================
# mef_gui_launcher.py - تشغيل واجهة MEF Converter
# ============================================================

import sys
import os
from pathlib import Path

# إضافة مسار السكربت الرئيسي
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.append(script_dir)

def launch_gui():
    """تشغيل واجهة PyQt5"""
    try:
        from PyQt5.QtWidgets import QApplication
        from mef_gui import MEFConverterGUI
        
        app = QApplication(sys.argv)
        app.setStyle("Fusion")
        
        window = MEFConverterGUI()
        window.show()
        
        sys.exit(app.exec_())
    except ImportError as e:
        print(f"Error: {e}")
        print("\\nPlease install required packages:")
        print("  pip install PyQt5 numpy pillow pygltflib")
        sys.exit(1)
    except Exception as e:
        print(f"Error launching GUI: {e}")
        sys.exit(1)

if __name__ == "__main__":
    launch_gui()
'''
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(gui_script)
    
    print(f"✅ GUI launcher script created: {output_path}")

def launch_gui():
    """تشغيل واجهة PyQt5"""
    try:
        from PyQt5.QtWidgets import QApplication
        from mef_gui import MEFConverterGUI
        
        app = QApplication(sys.argv)
        app.setStyle("Fusion")
        
        window = MEFConverterGUI()
        window.show()
        
        sys.exit(app.exec_())
    except ImportError as e:
        print(f"Error: {e}")
        print("\nPlease install required packages:")
        print("  pip install PyQt5 numpy pillow pygltflib")
        sys.exit(1)
    except Exception as e:
        print(f"Error launching GUI: {e}")
        sys.exit(1)

def apply_all_fixes():
    """تطبيق جميع الإصلاحات والإضافات"""
    
    # إضافة دوال DirectX إلى MefModelIGI2 و MefModelIGI1
    add_directx_export_to_mef_model_igi2()
    add_directx_export_to_mef_model_igi1()
    
    # إعادة تعريف دوال SMD و OBJ العامة
    # (هذه الدوال موجودة بالفعل في السكربت، فقط نحتاج للتأكد من أنها معرفة بشكل صحيح)
    
    print("✅ All fixes applied successfully")
