"""
parallel/cache.py
"""

# ============================================================
# AUTO-GENERATED BY MEF SCRIPT SPLITTER
# DO NOT EDIT - ALL FUNCTIONALITY PRESERVED
# ============================================================

# ========== Imports ==========
import os
import sys
import numpy
import math
from pathlib import Path
from dataclasses import dataclass, field
from datetime import datetime
from enum import IntEnum
import struct
import argparse
import json
import xml.etree.ElementTree
from xml.dom import minidom
from typing import List, Tuple, Optional, Dict
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from functools import partial
import hashlib
import pickle
import time
from contextlib import contextmanager
import struct
import numpy
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field
from PIL import Image
import io
import pygltflib
import argparse
from mef_igi2_export import export_to_directx
from mef_igi2_export import export_to_directx
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
import math
import math
import json
import hashlib
from PyQt5.QtWidgets import QApplication
from mef_gui import MEFConverterGUI
import traceback
import traceback
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
import traceback
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node
from pygltflib import GLTF2, Buffer, BufferView, Accessor, Mesh, Primitive, Attributes, Asset, Scene, Node, Skin
from pygltflib import GLTF2, Animation, AnimationChannel, AnimationSampler
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import traceback
import math
import math
import math


# ========== Classes ==========
class MefCache:
    """نظام تخزين مؤقت لنتائج تحويل النماذج"""
    
    CACHE_DIR = ".mef_cache"
    
    def __init__(self, enabled: bool = True, max_size_mb: int = 500):
        self.enabled = enabled
        self.max_size_mb = max_size_mb
        self.cache = {}
        self._ensure_cache_dir()
    
    def _ensure_cache_dir(self):
        """إنشاء مجلد التخزين المؤقت"""
        if self.enabled:
            Path(self.CACHE_DIR).mkdir(exist_ok=True)
    
    def _get_file_hash(self, filepath: str) -> str:
        """حساب هاش للملف لتحديد فريد"""
        hasher = hashlib.sha256()
        with open(filepath, 'rb') as f:
            for chunk in iter(lambda: f.read(65536), b''):
                hasher.update(chunk)
        return hasher.hexdigest()
    
    def _get_cache_path(self, file_hash: str, format_name: str) -> Path:
        """الحصول على مسار ملف التخزين المؤقت"""
        return Path(self.CACHE_DIR) / f"{file_hash}_{format_name}.cache"
    
    def get_cached_result(self, filepath: str, format_name: str):
        """استرجاع نتيجة مخزنة مؤقتاً"""
        if not self.enabled:
            return None
        
        file_hash = self._get_file_hash(filepath)
        cache_path = self._get_cache_path(file_hash, format_name)
        
        if cache_path.exists():
            try:
                with open(cache_path, 'rb') as f:
                    result = pickle.load(f)
                print(f"   📦 Cache hit for {Path(filepath).name} ({format_name})")
                return result
            except Exception as e:
                print(f"   ⚠️ Cache read error: {e}")
        return None
    
    def store_cached_result(self, filepath: str, format_name: str, result: any):
        """تخزين نتيجة في التخزين المؤقت"""
        if not self.enabled:
            return
        
        file_hash = self._get_file_hash(filepath)
        cache_path = self._get_cache_path(file_hash, format_name)
        
        try:
            with open(cache_path, 'wb') as f:
                pickle.dump(result, f)
            print(f"   💾 Cached result for {Path(filepath).name} ({format_name})")
        except Exception as e:
            print(f"   ⚠️ Cache write error: {e}")
    
    def clear_cache(self):
        """مسح جميع الملفات المخزنة مؤقتاً"""
        if self.enabled:
            for cache_file in Path(self.CACHE_DIR).glob("*.cache"):
                cache_file.unlink()
            print(f"   🧹 Cache cleared: {self.CACHE_DIR}")
    
    def get_cache_size(self) -> int:
        """الحصول على حجم التخزين المؤقت بالبايت"""
        if not self.enabled:
            return 0
        total = sum(f.stat().st_size for f in Path(self.CACHE_DIR).glob("*.cache"))
        return total


# ========== Functions ==========